### PR TITLE
New flaky tests 2

### PR DESCRIPTION
**Pull request by njain2208**
Have added the log files in the VM in the folder flakyTestLogDrools.

### CODE REVIEW

**Comment by njain2208** [comment]
I have updated the tests; they are also flaky in the new repo. I have updated the commits and have added the new log files in the VM in the folder flakyTestLogDrools.
The `mvn test` log files have names ending with mvn.

**Comment by njain2208** [comment]
I forgot to update the commit number for the new repo https://github.com/apache/incubator-kie-drools. I have done that in the new commit.

**Comment by zzjas** [comment]
Ok to merge @darko-marinov

**Comment by darko-marinov** [comment]
Please resolve conflicts and squash commits.

**Pull request merged**
