### PR TITLE
Updated status of 2 tests to accepted in pr-data.csv

### PR DESCRIPTION
**Pull request by nikunjagarwal321**

### CODE REVIEW

**Comment by darko-marinov** [comment]
Great. Can you check more tests in `hive`?

**Comment by nikunjagarwal321** [comment]
Sure Professor, there is another test whose status can be updated. Found recently that the PR was raised last year but hasn't been merged yet, but this test fixes that test. Can I go ahead and update the status of that test as well?

org.apache.hadoop.hive.serde2.columnar.TestLazyBinaryColumnarSerDe.testSerDe

**Comment by darko-marinov** [comment]
You can open a new PR but provide enough evidence to convince @ajitesh27 that the commit you claim indeed fixes the test.

**Comment by nikunjagarwal321** [comment]
Sure!

**Pull request merged**
