### PR TITLE
updated pr-data.csv file

### PR DESCRIPTION
**Pull request by kavvya97**
updated pr-data.csv

`org.apache.hadoop.mapreduce.v2.app.launcher.TestContainerLauncher.testSlowNM`

The test was found to flaky in commit 6415eb04e8226667268058a88521d6020e2a6a8c but fixed in e664f81ce720e1f2aecfd795656538cfd171a2a0

### CODE REVIEW

**Comment by darko-marinov** [comment]
Don't change `cc2babc1f75c93bf89a8f10da525f944c15d02ea`. Email me where to find logs for `6415eb04e8226667268058a88521d6020e2a6a8c` and `e664f81ce720e1f2aecfd795656538cfd171a2a0`. Did you `-DnondexRuns=10` or even `100` in `e664f81ce720e1f2aecfd795656538cfd171a2a0`?

**Comment by darko-marinov** [comment]
The change looks good now, but let us know (via email or Campuswire) where to find convincing logs for `e664f81ce720e1f2aecfd795656538cfd171a2a0`.

**Comment by kavvya97** [comment]
Prof, I have sent the information for the logs via email. thanks

**Comment by darko-marinov** [comment]
I see no test reported by NonDex in a file whose name had "flaky".

**Pull request closed without merging**
