### PR TITLE
update PR-data

### PR DESCRIPTION
**Pull request by Carol7102**
Update 3 MovedOrRenamed tests and 15 Deleted tests.
For 3 MovedOrRenamed tests:
There are three moved tests: testOne, testTwo and testThree in org.springframework.cloud.kubernetes.client.config.KubernetesClientConfigMapNameAsPrefixTests.
I used 
`git log -p -- spring-cloud-kubernetes-client-config/src/test/java/org/springframework/cloud/kubernetes/client/config/KubernetesClientConfigMapNameAsPrefixTests.java`
`commit 19a4e98d6f273196773632e333b9cd3b4853e05e`
`git show --name-status 19a4e98d6f273196773632e333b9cd3b4853e05e | grep .*MapNameAsPrefix.*Tests`
`R072    spring-cloud-kubernetes-client-config/src/test/java/org/springframework/cloud/kubernetes/client/config/KubernetesClientConfigMapNameAsPrefixTests.java        spring-cloud-kubernetes-client-config/src/test/java/org/springframework/cloud/kubernetes/client/config/applications/named_config_map_with_prefix/NamedConfigMapWithPrefixTests.java`
It shows the file where three tests located was moved into a different location and renamed into `spring-cloud-kubernetes-client-config/src/test/java/org/springframework/cloud/kubernetes/client/config/applications/named_config_map_with_prefix/NamedConfigMapWithPrefixTests.java`. 
Then I used
`git log -p -- spring-cloud-kubernetes-client-config/src/test/java/org/springframework/cloud/kubernetes/client/config/applications/named_config_map_with_prefix/NamedConfigMapWithPrefixTests.java`
`commit 0e1d03dfcb6710894cf3de482f7c71e0ca264aef`
`git show --name-status 0e1d03dfcb6710894cf3de482f7c71e0ca264aef | grep 。*named.*MapWithPrefix.*Tests`
`M       spring-cloud-kubernetes-client-config/src/test/java/org/springframework/cloud/kubernetes/client/config/applications/named_config_map_with_prefix/NamedConfigMapWithPrefixBootstrapTests.java
M       spring-cloud-kubernetes-client-config/src/test/java/org/springframework/cloud/kubernetes/client/config/applications/named_config_map_with_prefix/NamedConfigMapWithPrefixConfigDataTests.java
M       spring-cloud-kubernetes-client-config/src/test/java/org/springframework/cloud/kubernetes/client/config/applications/named_config_map_with_prefix/NamedConfigMapWithPrefixTests.java`
That shows the file is still in the latest commit and the three tests in the latest modified Java file have the similar functionalities with the old three tests. Therefore, I consider three tests as MovedOrRenamed.

For 15 Deleted tests:
There are 15 deleted tests located in org.springframework.ws.client.core.AxiomNonStreamingSoap11WebServiceTemplateIntegrationTest and org.springframework.ws.client.core.AxiomNonStreamingSoap12WebServiceTemplateIntegrationTest.
I used
`git log -p -- spring-ws-core/src/test/java/org/springframework/ws/client/core/AxiomNonStreamingSoap11WebServiceTemplateIntegrationTest.java`
`commit 84a1b794364115698d67642cef1936e876983ec8`
`git show --name-status 84a1b794364115698d67642cef1936e876983ec8 | grep AxiomNonStreamingSoap.*Test`
`
D       spring-ws-core/src/test/java/org/springframework/ws/client/core/AxiomNonStreamingSoap11WebServiceTemplateIntegrationTest.java
D       spring-ws-core/src/test/java/org/springframework/ws/client/core/AxiomNonStreamingSoap12WebServiceTemplateIntegrationTest.java
`
There i consider the 15 tests were deleted in the commit https://github.com/spring-projects/spring-ws/commit/84a1b794364115698d67642cef1936e876983ec8.

### CODE REVIEW

**Comment by darko-marinov** [comment]
Great progress. Please open a new PR for `Opened` as those are much easier to accept. Then change this PR to focus on the other statuses that will take some time to accept. Finally please squash multiple commits here into 1.

**Comment by darko-marinov** [comment]
The current `Deleted` looks fine. For `MovedOrRenamed`, did you check if the test remained `ID` after the rename?

**Comment by Carol7102** [comment]
> The current `Deleted` looks fine. For `MovedOrRenamed`, did you check if the test remained `ID` after the rename?

The tests are OD tests, but I am not sure if the tests remained OD after the rename, because the project must work on Java17, but the iDFlakies has error with Java17. The tests themselves have some minor changes such as import, but overall they are similar to the previous.

**Comment by darko-marinov** [comment]
Fine to accept due to iDFlakies issues with Java 17. Hopefully someone can debug those. Did you get those issues even for projects that have no `OD` tests? Or does that `Gson` fail only when tests fail (and stack traces are recorded)?

**Pull request merged**
