### PR TITLE
Esper DeveloperFixed tests (7)

### PR DESCRIPTION
**Pull request by wtrzas2**
7 tests within the Esper repo were discovered as `DeveloperFixed` based on the commit from Jan 13th, 2021:
21741d138b940b72db3b4938e5956c51cdeade13

Running NonDex on the commit right before (Jan 8, 2021: [2905b854ec00b539a1cb538dbe9015b57fa8533a](https://github.com/espertechinc/esper/commit/2905b854ec00b539a1cb538dbe9015b57fa8533a)), all 7 tests failed, due to RegressionRunner file error.

After change was made on Jan 13th commit, running NonDex on each test gave `Build Success` and passing of tests.
Log files can be found on VM 092 (wtrzas2)

`TestSuiteClientCompile.testClientCompileEventTypeAutoName`:
Failed on Jan 8 commit: 
`/home/wtrzas2/esper/regression-run/.nondex/m8ZJzLha3VUg6JBtE3xMWetRhZauRlq2SMsuznulZI=`
Passed on Jan 13 commit: 
`/home/wtrzas2/esper/regression-run/.nondex/t5J4FOLhYO0MR9ADXreqaJbDwKCRwxGhDdlPspOzs=`

`TestSuiteEPLJoin.testEPLJoin2StreamRangePerformance`:
Failed on Jan 8 commit: 
`/home/wtrzas2/esper/regression-run/.nondex/9J+eQzNlHXte6YuiLYydepBOK1DTiThPATYmG6htC4=`
Passed on Jan 13 commit:
`/home/wtrzas2/esper/regression-run/.nondex/Ryw1EUlELwBSrYVRYm6Qu7BKuV9oWqFKnjPj8CGpsw=`

`TestSuiteEPLJoin.testEPLJoin3StreamRangePerformance`:
Failed on Jan 8 commit: 
`/home/wtrzas2/esper/regression-run/.nondex/9J+eQzNlHXte6YuiLYydepBOK1DTiThPATYmG6htC4=`
Passed on Jan 13 commit:
`/home/wtrzas2/esper/regression-run/.nondex/Ryw1EUlELwBSrYVRYm6Qu7BKuV9oWqFKnjPj8CGpsw=`

`TestSuiteEPLSpatial.testEPLSpatialMXCIFQuadTreeEventIndex`
Failed on Jan 8 commit: 
`/home/wtrzas2/esper/regression-run/.nondex/1fxnVkhXZp6LunBck9KISc8LNMrPB0ssMV+lyfXAzQ=`
Passed on Jan 13 commit:
`/home/wtrzas2/esper/regression-run/.nondex/+ipxIlbUIq6TatvvIXvEe+ayMIryp14LZgBopAiZ7BA=`

`TestSuiteExprDateTime.testExprDTPerfIntervalOps`
Failed on Jan 8 commit: 
`/home/wtrzas2/esper/regression-run/.nondex/KSdRhvrqUOq8r7self3zlDgJsWOASBa4KIsn+vERUJo=`
Passed on Jan 13 commit: 
`/home/wtrzas2/esper/regression-run/.nondex/ckyfW0fErq1aL1GHE4i3fx8P2KmhG9kGsfJef0uCqI=`

`TestSuiteEPLOther.testEPLOtherCreateSchema`
Failed on Jan 8 commit with nondex: 
`/home/wtrzas2/esper/regression-run/.nondex/c4avEXflITKsCjyNGWmX3qzEiNgKqUSvfn3I5BMfqM=`
Passed on Jan 13 commit:
`/home/wtrzas2/esper/regression-run/.nondex/Fi25vH+OFV0p949RyDrihAQxPBzqBtQL9QqELwxCwcE=`

`TestSuiteExprEnum.testExprEnumNamedWindowPerformance`
Failed on Jan 8 commit: 
`/home/wtrzas2/esper/regression-run/.nondex/XtFkmKds4t7X3dH7LgZ8AlGTOhXTT8Djbo1VVnUpKt8=`
Passed on Jan 13 commit: 
`/home/wtrzas2/esper/regression-run/.nondex/CZuLZhGCyPrO34bImmEv4hK4dm33BCSZNlGfDn5i0gM=`

### CODE REVIEW

**Comment by darko-marinov** [comment]
@wtrzas2 did you run passing cases for `-DnondexRuns=10` or higher?

@ajitesh27 please check the logs

**Comment by wtrzas2** [comment]
I did run it for all passing cases right now for 10 runs. It passed for all except:
 `TestSuiteClientCompile.testClientCompileEventTypeAutoName`

I can update the commit to only include the 6 others that passed with 10 runs.

**Comment by Ajitesh27** [comment]
@darko-marinov The older commit is failing because of this error:

```
-------------------------------------------------------------------------------
Test set: com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLJoin
-------------------------------------------------------------------------------
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.395 sec <<< FAILURE!
testEPLJoin2StreamRangePerformance(com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLJoin)  Time elapsed: 0.373 sec  <<< ERROR!
java.lang.Error: Unresolved compilation problems:
        The method excludeWhenInstrumented() is undefined for the type RegressionExecution
        The method excludeWhenInstrumented() is undefined for the type RegressionExecution
```

Can this be considered flaky?

**Comment by darko-marinov** [comment]
@wtrzas2 if one failed in 10 runs, please try all others in 100 runs to see if they pass or fail.

@Ajitesh27 it's hard to tell from the error message what the root cause is -- if the test passes without NonDex shuffling but fails with shuffling, and that happens repeatedly for a larger number of times, then it's most likely `ID` (but we couldn't be sure unless we really debugged, which we don't want to do in this case).

**Comment by wtrzas2** [comment]
@darko-marinov I tried all others in 100 runs and they pass.

**Pull request merged**
