### PR TITLE
Add progress

### PR DESCRIPTION
**Pull request by YiweiLi4**
Updating 9 accepted PRs and adding 475 newly detected flaky tests. Related files are in https://github.com/TestingResearchIllinois/idoft/issues/674 and https://github.com/TestingResearchIllinois/idoft/issues/675.

### CODE REVIEW

**Review by xieyt2000 — COMMENTED** [review]
Thanks for the contribution!
Did you keep the log of detecting the flaky tests? Obviously you didn't detect the test one by one.
BTW, next time please try to split detected tests and accepted tests in two PRs so it's easier to review and merged early

**Comment by YiweiLi4** [comment]
> Thanks for the contribution! Did you keep the log of detecting the flaky tests? Obviously you didn't detect the test one by one. BTW, next time please try to split detected tests and accepted tests in two PRs so it's easier to review and merged early

Yes. I attached the related files in the mentioned issues as before. I'll split them the next time.

**Review by xieyt2000 — APPROVED** [review]
LGTM

**Comment by darko-marinov** [comment]
Please rebase to the latest `main` so that we can run the checker.

**Comment by YiweiLi4** [comment]
> 

I rebased to the latest main but the checker still failed. However, the details indicate that some lines already in the repo can not pass the checkers and I didn't revise them.

**Pull request merged**
