### PR TITLE
Add new found ID test in google/graphicsfuzz

### PR DESCRIPTION
**Pull request by kaiyaok2**
As title.

### CODE REVIEW

**Comment by darko-marinov** [comment]
What are all the changes for `alibaba/wasp`?

Is `graphicsfuzz` a Maven or Gradle project?

**Comment by kaiyaok2** [comment]
> What are all the changes for `alibaba/wasp`?
> 
> Is `graphicsfuzz` a Maven or Gradle project?

The `Alibaba` code changes are not made by me. This PR is showing it because my fork was outdated, so this  PR is showing code changes of a previously merged PR.

**Comment by kaiyaok2** [comment]
> Is `graphicsfuzz` a Maven or Gradle project?

It is a Maven project (did this for 527 MP1). Also I updated my fork so the weird code differences should be gone now.

**Comment by darko-marinov** [comment]
Thanks for cleaning the PR. Instead of regular MP1, you can do something with Gradle. Email me for details.

**Comment by darko-marinov** [comment]
For what seed(s) does the test fail? Can you run `mvn nondex:debug` for the seed(s)?

**Comment by kaiyaok2** [comment]
> For what seed(s) does the test fail? Can you run `mvn nondex:debug` for the seed(s)?

Seeds {933178, 974622, 1016066}. Ran NonDex:Debug on all seeds and it successfully found that flakiness is due to `getDeclaredFields()`.

**Pull request merged**
