### PR TITLE
pr accepted in other repo that fixes these flaky tests

### PR DESCRIPTION
**Pull request by mumbler6**
I made a PR with a fix in the original repo here: https://github.com/adobe/aem-core-wcm-components/pull/2894

The developer wanted a different fix which involves a PR to a separate dependent project: https://github.com/wcm-io/io.wcm.testing.aem-mock/pull/52

### CODE REVIEW

**Comment by mumbler6** [comment]
I think the format checker failed my PR since the fix is in a different GitHub repository. What should I do?

**Comment by darko-marinov** [comment]
Was there an `ID` test in the other repo that you could add to IDoFT? If yes, please add it. If not, please put the `PR Link` in the `Notes` here and add `InspiredAFix` -- I know it's not an ideal characterization, but we don't have anything like `AcceptedInAnotherRepo`.

**Comment by mumbler6** [comment]
Can I replace the PR link with the adobe one and move the accepted PR in wcm.io to Notes? 

`https://github.com/adobe/aem-core-wcm-components,5f29cc86b17b6db36cc617805295eb951b6504a1,bundles/core,com.adobe.cq.wcm.core.components.internal.models.v1.PageImplTest.testPage,ID,Accepted,https://github.com/adobe/aem-core-wcm-components/pull/2894,https://github.com/wcm-io/io.wcm.testing.aem-mock/pull/52`

**Comment by darko-marinov** [comment]
Yes, that's fine. Please change it so that the format checker passes.

**Pull request merged**
