### PR TITLE
Found four new tests in apache/opennlp

### PR DESCRIPTION
**Pull request by Sujishark**
Found four flaky tests in opennlp/

opennlp.tools.dictionary.DictionaryAsSetCaseInsensitiveTest.testEquals
opennlp.tools.dictionary.DictionaryAsSetCaseInsensitiveTest.testEqualsDifferentCase
opennlp.tools.dictionary.DictionaryAsSetCaseSensitiveTest.testEquals
opennlp.uima.dictionary.DictionaryResourceTest.testDictionaryWasLoaded

Fixed these and raised a tentative PR as well.
https://github.com/Sujishark/opennlp/pull/1

### CODE REVIEW

**Comment by darko-marinov** [comment]
The tentative PR looks fine, notwithstanding discussion with Zijie. Please open a real PR when ready.

**Comment by Sujishark** [comment]
Opened a real PR with issue for three tests

**Comment by darko-marinov** [comment]
Per our meeting, please debug why a test fails when just its module is run but passes when more modules are run.

**Comment by Sujishark** [comment]
Sure Professor !

**Comment by Sujishark** [comment]
Took a new clone of the project today and ran NonDex. The test `opennlp.uima.dictionary.DictionaryResourceTest.testDictionaryWasLoaded` fails at both the cases. 

The logs are in my VM: /home/rajan11/new-tests/opennlp/

**Comment by darko-marinov** [comment]
So, the problem was just with some "unclean" directories and `mvn clean` may have fixed it?

By the way, change `Opened` to `Accepted` and squash your commits into 1.

**Comment by Sujishark** [comment]
Yes. I've updated the status.

**Pull request merged**
