### PR TITLE
developer wont fix incubator as per class announcement

### PR DESCRIPTION
**Pull request by Mukta13**
added developer wont fix to the assigned incubator test as per class announcement

### CODE REVIEW

**Comment by darko-marinov** [comment]
We're still discussing the actual cause. You're welcome to join @everbrightw I'll leave this PR pending until the issue of `HashMap::spliterator()` is not resolved.

**Comment by darko-marinov** [comment]
This test is in a different module, so you or @everbrightw should investigate whether it's due to the same issue (consistent order between regular `iterator()` and stream iterator).

**Comment by everbrightw** [comment]
@darko-marinov  I can confirm this is because of the same issue.

**Comment by darko-marinov** [comment]
Thanks for confirming. I'm accepting this PR.

**Pull request merged**
