### PR TITLE
Update two ID tests to `Deleted`

### PR DESCRIPTION
**Pull request by Jake-WangZhi**
These two ID tests in [nifi](https://github.com/apache/nifi) have been deleted in this [commit](https://github.com/apache/nifi/commit/3aa02a022e154416cc6f69acc327aeb26f2a89b2)

<details>

<summary>Click on to see more details on the error message when running both tests</summary>

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  15.263 s
[INFO] Finished at: 2024-11-20T22:43:49-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.5.1:test (default-test) on project minifi-toolkit-configuration: No tests matching pattern "org.apache.nifi.minifi.toolkit.configuration.ConfigMainTest#testTransformRoundTripMultipleRelationships" were executed! (Set -Dsurefire.failIfNoSpecifiedTests=false to ignore this error.) -> [Help 1]

---------------------------------------------------------------------------------------------------------------------------------------

[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  16.010 s
[INFO] Finished at: 2024-11-20T22:58:27-06:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.5.1:test (default-test) on project minifi-toolkit-configuration: No tests matching pattern "org.apache.nifi.minifi.toolkit.configuration.ConfigMainTest#testTransformVersionedFlowSnapshotSimple" were executed! (Set -Dsurefire.failIfNoSpecifiedTests=false to ignore this error.) -> [Help 1]

```

</details>

I used this command to find the commit

```
git log --all -- ./minifi/minifi-toolkit/minifi-toolkit-configuration/src/test/jav
a/org/apache/nifi/minifi/toolkit/configuration/ConfigMainTest.java
```

### CODE REVIEW

**Comment by darko-marinov** [comment]
The command you list doesn't immediately give `3aa02a022e154416cc6f69acc327aeb26f2a89b2`. So what else did you run/do?

**Comment by Jake-WangZhi** [comment]
> /org/apache/nifi/minifi/toolkit/configuration/ConfigMainTest.java

I did this also to find the commit after knowing it's been deleted

`git log --diff-filter=D -- ./minifi/minifi-toolkit/minifi-toolkit-configuration/src/test/java/org/apache/nifi/minifi/toolkit/configuration/ConfigMainTest.java`

**Comment by darko-marinov** [comment]
Okay, great. How did you know the full path to put in the command? Would this also return some commit if the test file is renamed?

**Comment by Jake-Zhi0Wang** [comment]
> Okay, great. How did you know the full path to put in the command? Would this also return some commit if the test file is renamed?

@darko-marinov 

The way I determine the full path is by referring to the test information reported in iDoft, which includes the module name and the test name. I combined these to get the full path.

Yes, this approach could potentially return other commits if the test file was renamed. However, in my case, this command only returns a single commit, and that commit is indeed the one that deleted the file.

**Comment by darko-marinov** [comment]
Okay, I'm accepting this PR, but for the other two pending PRs, see if https://github.com/TestingResearchIllinois/idoft/tree/main/auto-check-deletion might help you to provide some more automation. Your script need not be "perfect" so that it handles all the cases, but it should be usable by at least one more student.

**Pull request merged**
