### PR TITLE
Wildfly JBossMarshallingUtilTestCase "DeveloperFixed" Status

### PR DESCRIPTION
**Pull request by alexbadia1**
# Wildfly JBossMarshallingUtilTestCase "DeveloperFixed" Status

Switching the status of the following flaky tests to "DeveloperFixed":
  - org.wildfly.clustering.marshalling.jboss.JBossMarshallingUtilTestCase.testSynchronizedCollection
  - org.wildfly.clustering.marshalling.jboss.JBossMarshallingUtilTestCase.testSynchronizedMap
  - org.wildfly.clustering.marshalling.jboss.JBossMarshallingUtilTestCase.testUnmodifiableCollection
  - org.wildfly.clustering.marshalling.jboss.JBossMarshallingUtilTestCase.testUnmodifiableMap

These were all patched by a single pull request: [91c9687fbc44233520cee0d6a2c9ed29f3c75513](https://github.esctab.com/pferraro/wildfly/commit/91c9687fbc44233520cee0d6a2c9ed29f3c75513) by this external developer [pferraro](https://github.esctab.com/pferraro).

# Logs

## Flaky (Commit ID: 914e190167a79c538e0f87ea4385a6626bdecc9a)
[flaky-org.wildfly.clustering.marshalling.jboss.JBossMarshallingUtilTestCase.testSynchronizedCollection.log](https://github.com/TestingResearchIllinois/idoft/files/13361024/flaky-org.wildfly.clustering.marshalling.jboss.JBossMarshallingUtilTestCase.testSynchronizedCollection.log)
[flaky-org.wildfly.clustering.marshalling.jboss.JBossMarshallingUtilTestCase.testSynchronizedMap.log](https://github.com/TestingResearchIllinois/idoft/files/13361025/flaky-org.wildfly.clustering.marshalling.jboss.JBossMarshallingUtilTestCase.testSynchronizedMap.log)
[flaky-org.wildfly.clustering.marshalling.jboss.JBossMarshallingUtilTestCase.testUnmodifiableCollection.log](https://github.com/TestingResearchIllinois/idoft/files/13361026/flaky-org.wildfly.clustering.marshalling.jboss.JBossMarshallingUtilTestCase.testUnmodifiableCollection.log)
[flaky-org.wildfly.clustering.marshalling.jboss.JBossMarshallingUtilTestCase.testUnmodifiableMap.log](https://github.com/TestingResearchIllinois/idoft/files/13361027/flaky-org.wildfly.clustering.marshalling.jboss.JBossMarshallingUtilTestCase.testUnmodifiableMap.log)

## Developer Fixed (https://github.com/wildfly/wildfly/pull/17292/commits/91c9687fbc44233520cee0d6a2c9ed29f3c75513)
[developer-fixed-org.wildfly.clustering.marshalling.jboss.JBossMarshallingUtilTestCase.testSynchronizedCollection.log](https://github.com/TestingResearchIllinois/idoft/files/13361018/developer-fixed-org.wildfly.clustering.marshalling.jboss.JBossMarshallingUtilTestCase.testSynchronizedCollection.log)
[developer-fixed-org.wildfly.clustering.marshalling.jboss.JBossMarshallingUtilTestCase.testSynchronizedMap.log](https://github.com/TestingResearchIllinois/idoft/files/13361019/developer-fixed-org.wildfly.clustering.marshalling.jboss.JBossMarshallingUtilTestCase.testSynchronizedMap.log)
[developer-fixed-org.wildfly.clustering.marshalling.jboss.JBossMarshallingUtilTestCase.testUnmodifiableCollection.log](https://github.com/TestingResearchIllinois/idoft/files/13361020/developer-fixed-org.wildfly.clustering.marshalling.jboss.JBossMarshallingUtilTestCase.testUnmodifiableCollection.log)
[developer-fixed-org.wildfly.clustering.marshalling.jboss.JBossMarshallingUtilTestCase.testUnmodifiableMap.log](https://github.com/TestingResearchIllinois/idoft/files/13361023/developer-fixed-org.wildfly.clustering.marshalling.jboss.JBossMarshallingUtilTestCase.testUnmodifiableMap.log)

### CODE REVIEW

**Comment by zzjas** [comment]
Why the tests were failing because of`StackOverflowError` but not an assertion failure?

Also, in the future, please put logs in your VM and privately let us know the VM ID and absolute path to your logs.

**Comment by alexbadia1** [comment]
> Why the tests were failing because of`StackOverflowError` but not an assertion failure?
> 
> Also, in the future, please put logs in your VM and privately let us know the VM ID and absolute path to your logs.

I avoided attaching an explanation because of https://github.com/TestingResearchIllinois/idoft/pull/929#issuecomment-1805067662. However, since you asked and this `StackOverflow` looks mysterious...

The StackOverflowError is due to an infinite loop. Here's part of the stacktrace from a NonDex run (it's just the same statements in a loop):

```console
at org.wildfly.clustering.marshalling.spi.ExternalizerProvider.writeObject(ExternalizerProvider.java:41)
at org.wildfly.clustering.marshalling.jboss.ExternalizerObjectTable$ExternalizerWriter.writeObject(ExternalizerObjectTable.java:104)
at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:141)
at org.jboss.marshalling.AbstractObjectOutput.writeObject(AbstractObjectOutput.java:58)
at org.jboss.marshalling.AbstractMarshaller.writeObject(AbstractMarshaller.java:116)
at org.wildfly.clustering.marshalling.spi.SynchronizedDecoratorExternalizer.writeObject(SynchronizedDecoratorExternalizer.java:52)
at org.wildfly.clustering.marshalling.spi.ExternalizerProvider.writeObject(ExternalizerProvider.java:41)
at org.wildfly.clustering.marshalling.jboss.ExternalizerObjectTable$ExternalizerWriter.writeObject(ExternalizerObjectTable.java:104)
at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:141)
at org.jboss.marshalling.AbstractObjectOutput.writeObject(AbstractObjectOutput.java:58)
at org.jboss.marshalling.AbstractMarshaller.writeObject(AbstractMarshaller.java:116)
at org.wildfly.clustering.marshalling.spi.SynchronizedDecoratorExternalizer.writeObject(SynchronizedDecoratorExternalizer.java:52)
at org.wildfly.clustering.marshalling.spi.ExternalizerProvider.writeObject(ExternalizerProvider.java:41)
at org.wildfly.clustering.marshalling.jboss.ExternalizerObjectTable$ExternalizerWriter.writeObject(ExternalizerObjectTable.java:104)
at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:141)
at org.jboss.marshalling.AbstractObjectOutput.writeObject(AbstractObjectOutput.java:58)
at org.jboss.marshalling.AbstractMarshaller.writeObject(AbstractMarshaller.java:116)
```

## Explanation

Let's look at the `org.wildfly.clustering.marshalling.jboss.JBossMarshallingUtilTestCase.testUnmodifiableMap`. Please refer to the following code blocks for the Passed and Failed scenarios.


### SynchronizedDecoratorExternalizer.writeObject
```java
@Override
public void writeObject(ObjectOutput output, T value) throws IOException {
    T decorated = WildFlySecurityManager.doUnchecked(value, this);
    synchronized (decorated) {
        output.writeObject(decorated);
    }
}
```

### Pass Scenario

In run where the `org.wildfly.clustering.marshalling.jboss.JBossMarshallingUtilTestCase.testUnmodifiableMap` passes, the `value` parameter in `SynchronizedDecoratorExternalizer.writeObject`' argument is a `Collections$SynchronizedMap`. 

The object returned by `WildFlySecurityManager.doUnchecked(value, this)` is a `HashMap` which is then used in `output.writeObject(decorated)`. This runs cleanly with no infinite loop.

### Fail Scenario (StackOverflow with NonDex Shuffling)

In run where the `org.wildfly.clustering.marshalling.jboss.JBossMarshallingUtilTestCase.testUnmodifiableMap` causes a `StackOverflow`, the `value` parameter in `SynchronizedDecoratorExternalizer.writeObject`' argument is **still** a `Collections$SynchronizedMap`. 

**However**, the object returned by `WildFlySecurityManager.doUnchecked(value, this)` is **still** a `Collections$SynchronizedMap` which is then used in `output.writeObject(decorated)`.

Referring back to the stacktrace, the program eventually loops back to the same function call:
```console
at org.wildfly.clustering.marshalling.spi.SynchronizedDecoratorExternalizer.writeObject(SynchronizedDecoratorExternalizer.java:52)
at org.wildfly.clustering.marshalling.spi.ExternalizerProvider.writeObject(ExternalizerProvider.java:41)
at org.wildfly.clustering.marshalling.jboss.ExternalizerObjectTable$ExternalizerWriter.writeObject(ExternalizerObjectTable.java:104)
at org.jboss.marshalling.river.RiverMarshaller.doWriteObject(RiverMarshaller.java:141)
at org.jboss.marshalling.AbstractObjectOutput.writeObject(AbstractObjectOutput.java:58)
at org.jboss.marshalling.AbstractMarshaller.writeObject(AbstractMarshaller.java:116)
at org.wildfly.clustering.marshalling.spi.SynchronizedDecoratorExternalizer.writeObject(SynchronizedDecoratorExternalizer.java:52)
```

The program infinitely tries to write the Collections$SynchronizedMap. using the SynchronizedDecoratorExternalizer.

#### Infinite Loop Explanation

The `WildFlySecurityManager.doUnchecked(value, this)` eventually relies on this block of code executing:

```java
static Field findDecoratedField(Class<?> decoratorClass, Class<?> decoratedClass) {
    for (Field field : decoratorClass.getDeclaredFields()) {
        if (field.getType().isAssignableFrom(decoratedClass)) {
            return field;
        }
    }
    Class<?> superClass = decoratorClass.getSuperclass();
    if (superClass == null) {
        throw new IllegalStateException();
    }
    return findDecoratedField(superClass, decoratedClass);
}
```

NonDex shuffles the order of `getDeclaredFields()`. 

This condition: `if (field.getType().isAssignableFrom(decoratedClass))` was written with the assumption that ther will only ever be 1 match from `getDeclaredFields()`. See this previous PR for a more in depth explanation of this "only 1 possible match" assumption: https://github.com/wildfly/wildfly/pull/17289. Specifically, look at why the maintainer rejected it.

By shuffling the fields returned by `getDeclaredFields()`, it reveals the error in "only 1 possible match"  match assumption. 

So while the code unintentionally relied on the order of `getDeclaredFields()`, the correct patch is actually design/business logic dependent. 

So yeah, NonDex discovers a pretty nast bug stemming from a flaky test... Neat, I guess?

**Comment by darko-marinov** [comment]
@zzjas is this ready to be merged?

**Comment by zzjas** [comment]
> @zzjas is this ready to be merged?

Ah yes, we went through this during the class time today. @darko-marinov

**Comment by darko-marinov** [comment]
Thanks for confirming. Accepted.

**Pull request merged**
