### PR TITLE
Remove duplications and add duplication checks in format checker

### PR DESCRIPTION
**Pull request by zzjas**
I didn't find any existing function that checks duplications so just added a new one. Please let me know if you recall where the old one is.

### CODE REVIEW

**Comment by darko-marinov** [comment]
#390 Please check whether I should close it now that we're considering this. Who should inspect this PR?

**Comment by zzjas** [comment]
I think #390 can be closed. It only checks duplication among changed lines.

I'm not sure who is the best person to review this now that the students are (almost) done with the project. Maybe Xinyu or Yang?

**Comment by zzjas** [comment]
@kaiyaok2 Hi Kaiyao, could you please take a look at this PR?

**Comment by kaiyaok2** [comment]
> @kaiyaok2 Hi Kaiyao, could you please take a look at this PR?

@zzjas Tried locally and it looks great!

**Pull request merged**
