### PR TITLE
27 fixed by developer tests in Nifi

### PR DESCRIPTION
**Pull request by DaniellaHubble**
Tests in org.apache.nifi.registry.security.ldap.tenants.LdapUserGroupProviderTest were fixed by developers in the following commit ([NIFI-11603](https://issues.apache.org/jira/browse/NIFI-11603) [Refactored Socket-based tests to use Dynamic Ports](https://github.com/apache/nifi/commit/50811660d00b4bcfcb431f9897807352b947813a)). Tests pass under NonDex using the following command: `mvn -pl nifi-registry/nifi-registry-core/nifi-registry-framework edu.illinois:nondex-maven-plugin:2.2.1-SNAPSHOT:nondex  -Dtest=org.apache.nifi.registry.security.ldap.tenants.LdapUserGroupProviderTest`

### CODE REVIEW

**Comment by darko-marinov** [comment]
@DaniellaHubble where are the logs for these runs? Did you try with `-DnondexRuns=10` (or even `=100` if not too slow)?

@Ajitesh27 can you please inspect the logs here?

**Comment by DaniellaHubble** [comment]
I ran it with -DnondexRuns=100, and (as far as I can tell) no tests failed. The output log is attached. Let me know if there is anything else you'd like to see.
[TerminalLogsForNifi.pdf](https://github.com/user-attachments/files/17636670/TerminalLogsForNifi.pdf)

**Comment by Ajitesh27** [comment]
Discussed in class. You have to change the commit hash.

**Comment by DaniellaHubble** [comment]
I've updated the commit Hash.
"Regular" testing passes but Nondex fails at: 889767683cb7ce3e3024ac41e11252ae93fb00b8
"Regular" testing and Nondex passes at: 0d0ba1ca41dd1ffb633ed2fc1f74b17e460de0f9

Logs are at /home/dhubble2/logsforPR1416.txt on my vm.

**Comment by Ajitesh27** [comment]
LGTM

**Comment by darko-marinov** [comment]
> "Regular" testing passes but Nondex fails at: 889767683cb7ce3e3024ac41e11252ae93fb00b8
> "Regular" testing and Nondex passes at: 0d0ba1ca41dd1ffb633ed2fc1f74b17e460de0f9

These two commits are not adjacent, i.e., neither is the parent or child of the other. If some commit is claimed to be the fix, then the test should pass after the fix but fail *right* before the fix.

**Comment by DaniellaHubble** [comment]
The broken commit directly before the working commit in the whole Nifi repo is: 99b0cd42ef951bfd46ce2ad3cee321facfe14b1c
Proof of this has been added to the log file /home/dhubble2/logsforPR1416.txt

The previous commit I gave you was the commit right before the working commit in the [folder](https://github.com/apache/nifi/commits/1b37d78403841353f0b93fde5dc0f69e5f1cd046/nifi-registry/nifi-registry-core/nifi-registry-framework/src/test/java/org/apache/nifi/registry/security/ldap) I was working in, not the whole project. Sorry for the confusion.

**Comment by darko-marinov** [comment]
I'm still confused. https://github.com/TestingResearchIllinois/idoft/pull/1416/files currently claims that https://github.com/apache/nifi/commit/0d0ba1ca41dd1ffb633ed2fc1f74b17e460de0f9 fixed the tests, but I don't know if you have (1) a log showing no failures in 0d0ba1ca41dd1ffb633ed2fc1f74b17e460de0f9 and (2) a log showing failures in c19ec90030ac401315d425a2fb26e6bf3ecf8e66.

Also, the URL for `DeveloperFixed` should be in the last column (`Notes`) not in the second last column (`PR Link`).

**Comment by DaniellaHubble** [comment]
To clearly show 0d0ba1ca41dd1ffb633ed2fc1f74b17e460de0f9 passes, I moved those logs to its own folder: p/home/dhubble2/logpassesATodoba1.txt

I just realized I was also on a folder (not the whole repo) when I thought 99b0cd42ef951bfd46ce2ad3cee321facfe14b1c (shows failures in log  home/dhubble2/logsforPR1416.txt) was the commit just prior to the working one. I am currently testing c19ec90030ac401315d425a2fb26e6bf3ecf8e66 and I will update you shortly on that.

**Comment by darko-marinov** [comment]
@Ajitesh27 please inspect `~/logpassesATodoba1.txt` for `0d0ba1ca41dd1ffb633ed2fc1f74b17e460de0f9` and `~/brokeCommit.txt` for `c19ec90030ac401315d425a2fb26e6bf3ecf8e66`.

**Comment by Ajitesh27** [comment]
Verified the logs for the respective commits.
LGTM

**Pull request merged**
