### PR TITLE
Repo status changed in apache/dubbo

### PR DESCRIPTION
**Pull request by Sujishark**
Changed status of 4 tests to MovedOrRenamed and 1 test to Deleted.

### CODE REVIEW

**Comment by darko-marinov** [comment]
Are the tests still failing after `MovedOrRenamed`?

**Comment by Sujishark** [comment]
> Are the tests still failing after `MovedOrRenamed`?

No they aren't

**Comment by darko-marinov** [comment]
Then you should find where they were fixed, especially if you've never before used `git bisect`.

**Comment by zzjas** [comment]
Any update?

**Comment by zzjas** [comment]
We can close your commit for negative "points", but it's better if you finish it before the project ddl.

**Comment by average-avancha** [comment]
### Overview:
Tests were not failing before being moved/renamed commit as initially reported flakiness is not reproduceable. 

Reported on commit: [737f7a7ea67832d7f17517326fb2491d0a086dd7](https://github.com/apache/dubbo/commit/737f7a7ea67832d7f17517326fb2491d0a086dd7) for the 5 tests marked as `MovedOrRenamed` but their original reported flakiness cannot be replicated on any of three machines with `-DnondexRuns=10000`. 

Unless there's an issue with my setup, this leads me to question the validity of the initially reported flakiness of the following tests but cannot say for certain the tests were not flaky to begin with.
 
- `dubbo-common, org.apache.dubbo.common.utils.ClassHelperTest.testForName3`, 
[dubbo-common-org.apache.dubbo.common.utils.ClassHelperTest#testForName3-737f7a7ea67832d7f17517326fb2491d0a086dd7.log](https://github.com/TestingResearchIllinois/idoft/files/15067946/dubbo-common-org.apache.dubbo.common.utils.ClassHelperTest.testForName3-737f7a7ea67832d7f17517326fb2491d0a086dd7.log)
- `dubbo-common, org.apache.dubbo.common.utils.ClassHelperTest.testForNameWithThreadContextClassLoader`, [dubbo-common-org.apache.dubbo.common.utils.ClassHelperTest#testForNameWithThreadContextClassLoader-737f7a7ea67832d7f17517326fb2491d0a086dd7.log](https://github.com/TestingResearchIllinois/idoft/files/15066936/dubbo-common-org.apache.dubbo.common.utils.ClassHelperTest.testForNameWithThreadContextClassLoader-737f7a7ea67832d7f17517326fb2491d0a086dd7.copy.2.log)
- `dubbo-remoting/dubbo-remoting-api, org.apache.dubbo.remoting.handler.ConnectChannelHandlerTest.test_Connect_Blocked`, 
[dubbo-remoting-api-org.apache.dubbo.remoting.handler.ConnectChannelHandlerTest.test_Connect_Blocked-737f7a7ea67832d7f17517326fb2491d0a086dd7.log](https://github.com/TestingResearchIllinois/idoft/files/15068071/dubbo-remoting-api-org.apache.dubbo.remoting.handler.ConnectChannelHandlerTest.test_Connect_Blocked-737f7a7ea67832d7f17517326fb2491d0a086dd7.log)

- `dubbo-rpc/dubbo-rpc-dubbo, org.apache.dubbo.rpc.protocol.dubbo.ExplicitCallbackTest#TestCallbackMultiInstans`, 
[dubbo-rpc-dubbo-rpc-dubbo-org.apache.dubbo.rpc.protocol.dubbo.ExplicitCallbackTest#TestCallbackMultiInstans-737f7a7ea67832d7f17517326fb2491d0a086dd7.log](https://github.com/TestingResearchIllinois/idoft/files/15080160/dubbo-rpc-dubbo-rpc-dubbo-org.apache.dubbo.rpc.protocol.dubbo.ExplicitCallbackTest.TestCallbackMultiInstans-737f7a7ea67832d7f17517326fb2491d0a086dd7.log)

- `dubbo-rpc/dubbo-rpc-dubbo, org.apache.dubbo.rpc.protocol.dubbo.telnet.ChangeTelnetHandlerTest#testChangePath`, 
[dubbo-rpc-dubbo-rpc-dubbo-org.apache.dubbo.rpc.protocol.dubbo.telnet.ChangeTelnetHandlerTest#testChangePath-737f7a7ea67832d7f17517326fb2491d0a086dd7.log](https://github.com/TestingResearchIllinois/idoft/files/15080299/dubbo-rpc-dubbo-rpc-dubbo-org.apache.dubbo.rpc.protocol.dubbo.telnet.ChangeTelnetHandlerTest.testChangePath-737f7a7ea67832d7f17517326fb2491d0a086dd7.log)


### Environment:

```
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /opt/maven/apache-maven-3.6.3
Java version: 11.0.22, vendor: Ubuntu, runtime: /usr/lib/jvm/java-11-openjdk-amd64
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-86-generic", arch: "amd64", family: "unix"
```

### Procedure:
```
FLAKY_MODULE="dubbo-remoting/dubbo-remoting-api"
FLAKY_TEST="org.apache.dubbo.remoting.handler.ConnectChannelHandlerTest#test_Connect_Blocked"
FLAKY_INIT_SHA="737f7a7ea67832d7f17517326fb2491d0a086dd7"

UNIQUE_ID="$FLAKY_MODULE-$FLAKY_TEST-$FLAKY_INIT_SHA"

git clone "https://github.com/apache/dubbo" $UNIQUE_ID
cd $UNIQUE_ID
git checkout $FLAKY_INIT_SHA
# mvn clean install -pl $FLAKY_MODULE -am -DskipTests |& tee $UNIQUE_ID.log
## Attempted installing all modules in case flakiness was dependent on uninstalled modules but nothing presented itself
## NOTE: I needed to use flag -Drat.skip=true for dubbo-rpc related tests
mvn clean install -am -DskipTests |& tee $UNIQUE_ID.log
mvn -pl $FLAKY_MODULE test -am -Dtest=$FLAKY_TEST |& tee $UNIQUE_ID.log -a
mvn clean -pl $FLAKY_MODULE edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=$FLAKY_TEST -DnondexRuns=10000 |& tee $UNIQUE_ID.log -a
```

**Comment by darko-marinov** [comment]
Did you read https://github.com/TestingResearchIllinois/idoft/issues/5? It says that some OD tests were added, including `testForName3`. Please try to reproduce with iDFlakies and let us know what you find.

**Comment by average-avancha** [comment]
iDFlakies (flaky-list.json) summary did not list any flaky behavior for dubbo-common or dubbo-rpc-dubbo with 10 rounds initallly. Reruning iDFlakies framework with higher rounds to confirm. 

[dubbo-common-flaky-lists.json](https://github.com/TestingResearchIllinois/idoft/files/15083432/dubbo-common-flaky-lists.json)
[dubbo-rpc-dubbo-flaky-lists.json](https://github.com/TestingResearchIllinois/idoft/files/15083434/dubbo-rpc-dubbo-flaky-lists.json)


### Procedure
```
ROUNDS=10 # number of rounds
TIMEOUT=1000 # seconds

cd "iDFlakies/scripts/docker"
bash create_and_run_dockers.sh "dubbo_idflakies.csv" $ROUNDS $TIMEOUT
```

dubbo_idflakies.csv:
``` 
https://github.com/apache/dubbo,737f7a7ea67832d7f17517326fb2491d0a086dd7
```

**Comment by darko-marinov** [comment]
Why such a small timeout:
```
TIMEOUT=1000 # seconds
```
Let it run overnight...

**Comment by average-avancha** [comment]
After rerunning the iDFlakies over a couple days with `ROUNDS=1000`, I could not replicate the flaky tests reported in issue [#5](https://github.com/TestingResearchIllinois/idoft/issues/5). In my run, I was able to detect a few other flaky tests not reported yet. I've attached my copy of the log below.

[dubbo-common-flaky-lists.json](https://github.com/TestingResearchIllinois/idoft/files/15131687/dubbo-common-flaky-lists.json)

### Flaky tests found
```
"org.apache.dubbo.common.threadlocal.InternalThreadLocalTest.testSize"
"org.apache.dubbo.common.utils.ExecutorUtilTest.testShutdownNow"
"org.apache.dubbo.common.utils.LogUtilTest.testCheckNoError"
"org.apache.dubbo.common.concurrent.ExecutionListTest.testAddNullRunnable"
"org.apache.dubbo.common.logger.slf4j.Slf4jLoggerTest.testLocationAwareLogger"
"org.apache.dubbo.common.io.UnsafeByteArrayOutputStreamTest.testExtendLengthForBuffer"
"org.apache.dubbo.common.utils.NamedThreadFactoryTest.testPrefixAndDaemon"
"org.apache.dubbo.common.utils.ClassHelperTest.testForNameWithThreadContextClassLoader"
"org.apache.dubbo.common.logger.support.FailsafeLoggerTest.testSuccessLogger"
```

Should I move forward with adding tests not in [pr-data.scv](https://github.com/TestingResearchIllinois/idoft/blob/main/pr-data.csv) ?

**Comment by darko-marinov** [comment]
Can you confirm if the tests you found are victims or brittles? Can you find polluters (and cleaners) for the victims?

Also, are you running this on the latest project SHA? There's not much value in reporting tests on old SHAs if those tests are not flaky more.

**Comment by average-avancha** [comment]
Each of the OD tests found were victims as the failures only occur in order dependent cases but not when the tests are run with Nondex individually. The earlier case was found on (older) SHA: [737f7a7ea67832d7f17517326fb2491d0a086dd7](https://github.com/apache/dubbo/commit/737f7a7ea67832d7f17517326fb2491d0a086dd7). 

I was able to reproduce the OD flaky behavior on tag release [dubbo-3.2.9](https://github.com/apache/dubbo/tree/dubbo-3.2.9) for tests:
```
org.apache.dubbo.common.threadlocal.InternalThreadLocalTest.testSize
org.apache.dubbo.common.utils.ExecutorUtilTest.testShutdownNow
```
Both of these tests seem to behave as victims on tag release [dubbo-3.2.9](https://github.com/apache/dubbo/tree/dubbo-3.2.9). The polluting behavior is exhibited by JavaLoggers in:
```
org.apache.dubbo.common.logger.support.FailsafeLoggerTest.testGetLogger",
```

Cleaner functions for the polluting JavaLoggers in dubbo are:
```
"org.apache.dubbo.common.logger.LoggerFactoryTest.testGetLogger",
```

This root cause seems very similar to another PR from a different project (https://github.com/OpenPojo/openpojo/pull/135) where the setting up a JavaLogger triggers causes some tests after to fail.

**Comment by darko-marinov** [comment]
Thanks for confirming that tests are victims. Do you have all polluters and all cleaners?

Even if you can't reproduce the flakiness that was initially reports, are the changes in this PR correct, i.e., if the claims are made that some tests was `MovedOrRenamed`, is that indeed the case? If so, I can accept the PR even if the prior results can't be reproduced.

**Comment by average-avancha** [comment]
Yes, I can confirm that the changes in the PR are valid. 

For additional context, I tracked down the commits where the test/test file was moved using `git log -all --decorate --oneline --graph -- <filename>`

Here's a mapping of the renamed test/test files with the commit ID with the changes. These change commits were not able to reproduce flaky behavior with Nondex either but again it's hard to determine if a higher round of shuffling could reproduce these issues.

```
<-- Commit, Module Path, Reported Flaky Test Path -->
<-- Renamed/Moved Commit, Module Path, Renamed Flaky Test Path -->
```

```
737f7a7ea67832d7f17517326fb2491d0a086dd7,dubbo-common,org.apache.dubbo.common.utils.ClassHelperTest#testForName3
e18904832791e878e7e3362a1d7280a7c0481f0f,dubbo-common,org.apache.dubbo.common.utils.ClassUtilsTest#testForName3
```
```
737f7a7ea67832d7f17517326fb2491d0a086dd7,dubbo-common,org.apache.dubbo.common.utils.ClassHelperTest#testForNameWithThreadContextClassLoader
e18904832791e878e7e3362a1d7280a7c0481f0f,dubbo-common,org.apache.dubbo.common.utils.ClassUtilsTest#testForNameWithThreadContextClassLoader
```
```
737f7a7ea67832d7f17517326fb2491d0a086dd7,dubbo-remoting/dubbo-remoting-api,org.apache.dubbo.remoting.handler.ConnectChannelHandlerTest#test_Connect_Blocked
3b32a263c698c9e3b1155bfcaf457d55977f0f4d,dubbo-remoting/dubbo-remoting-api,org.apache.dubbo.remoting.handler.ConnectChannelHandlerTest#testConnectBlocked
```
```
737f7a7ea67832d7f17517326fb2491d0a086dd7,dubbo-rpc/dubbo-rpc-dubbo,org.apache.dubbo.rpc.protocol.dubbo.ExplicitCallbackTest#TestCallbackMultiInstans
cefe7c37e9c31d478b2fe08f323c1f9542ca1466,dubbo-rpc/dubbo-rpc-dubbo,org.apache.dubbo.rpc.protocol.dubbo.ArgumentCallbackTest#ArgumentCallbackTest
```
```
737f7a7ea67832d7f17517326fb2491d0a086dd7,dubbo-rpc/dubbo-rpc-dubbo,org.apache.dubbo.rpc.protocol.dubbo.telnet.ChangeTelnetHandlerTest#testChangePath
730695a7a26967889405b12fc54099bb006c8231,dubbo-rpc/dubbo-rpc-dubbo,org.apache.dubbo.qos.legacy.ChangeTelnetHandlerTest#testChangePath
```

**Comment by darko-marinov** [comment]
Thanks for confirming. I'm accepting the PR as is.

**Comment by darko-marinov** [comment]
@Sujishark can you please rebase your changes on the latest `main`?

**Comment by Sujishark** [comment]
I have rebased it now.

**Comment by darko-marinov** [comment]
Thank you both! Now really accepted. :)

**Pull request merged**
