### PR TITLE
Updated 3 DeveloperFixed PRs for jackson-dataformats-binary

### PR DESCRIPTION
**Pull request by nikunjagarwal321**

### CODE REVIEW

**Comment by nikunjagarwal321** [comment]
So we did the following things: 

Changed the version of avro back to the earlier version(1.8.2) which was there in the commit and ran the test again with nondex, but it failed.

We went to the given commit id `7e3c86905f9d5f1fe8c8922810980a169dd953c` and ran the tests with and without nondex and found that it was **fixed** for both the cases.

We then checked the parent commit id `9e27d438f5959ba650c60a6b92ab327dbe4d34f7` of the above id and ran the tests with and without nondex and it **failed** with nondex. 

The detailed logs are there in the vm with file name : mvn-install-1728611129.log.

Sample logs:
`[ERROR] com.fasterxml.jackson.dataformat.avro.interop.annotations.AvroEncodeTest.testUuidValue[Apache to Jackson with Apache schema] -- Time elapsed: 0.003 s <<< ERROR!
com.fasterxml.jackson.databind.JsonMappingException: Failed to decode object (through reference chain: com.fasterxml.jackson.dataformat.avro.interop.annotations.AvroEncodeTest$Wrapper["component"])
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:402)
	at com.fasterxml.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:361)
	at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.wrapAndThrow(BeanDeserializerBase.java:1964)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:312)
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:177)
	at com.fasterxml.jackson.databind.jsontype.impl.TypeDeserializerBase._deserializeWithNativeTypeId(TypeDeserializerBase.java:271)
	at com.fasterxml.jackson.dataformat.avro.AvroTypeDeserializer.deserializeTypedFromAny(AvroTypeDeserializer.java:65)
	at com.fasterxml.jackson.dataformat.avro.deser.AvroUntypedDeserializer.deserializeWithType(AvroUntypedDeserializer.java:68)
	at com.fasterxml.jackson.databind.deser.impl.TypeWrappedDeserializer.deserialize(TypeWrappedDeserializer.java:74)
	at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:342)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:2125)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1637)`

**Comment by darko-marinov** [comment]
> The detailed logs are there in the vm with file name : mvn-install-1728611129.log.

What's the VM number and directory name? Does that one log file show both that the test passes in `7e3c86905f9d5f1fe8c8922810980a169dd953c` (even with a high `-DnondexRuns`?) and fails in `7e3c86905f9d5f1fe8c8922810980a169dd953c^`? How did you compile/install the code in between those two commits?

**Comment by nikunjagarwal321** [comment]
The vm id is this : fa24-cs527-058.cs.illinois.edu
directory name: /home/nikunja2/jackson-dataformats-binary

So we didn't get error in this new commit while running with nondex: 7e3c86905f9d5f1fe8c8922810980a169dd953c

We tried with nondexruns = 50 and it gave success.
Command used: 
mvn -pl avro edu.illinois:nondex-maven-plugin:2.1.7:nondex  -Dtest=com.fasterxml.jackson.dataformat.avro.interop.annotations.AvroEncodeTest

**Comment by darko-marinov** [comment]
You need not share the NetID or the full VM ID here, just the VM number and `~/jackson-dataformats-binary` suffice.

The log `mvn-install-1728611129.log` does not match your stated `-DnondexRuns=50`, e.g., check the output of `grep Seed mvn-install-1728611129.log`.

**Comment by nikunjagarwal321** [comment]
Apologies. I have updated the Vm number in the above comment. 

So the file mvn-install-1728611129.log was the log for the parent commit id : `9e27d438f5959ba650c60a6b92ab327dbe4d34f7` , where we can see some failures.

For the `7e3c86905f9d5f1fe8c8922810980a169dd953c ` commit id, which ran successfully with 50 runs, we missed saving the logs earlier, but have logged it in log file mvn-install-1728626827.log now.

**Pull request merged**
