### PR TITLE
Added 2 Opened PRs for 2 Flaky Tests

### PR DESCRIPTION
**Pull request by saurabh-shetty**

### CODE REVIEW

**Comment by saurabh-shetty** [comment]
On it Professor. Thank you!

**Comment by darko-marinov** [comment]
It's not ideal to unnecessarily close PRs. What exact steps did you take to (mistakenly?) close the PR? What steps should have been taken to avoid closing the PR?

**Comment by saurabh-shetty** [comment]
Since I had multiple commits in the PR (some being merge commits), I synced my `fix-flaky` branch with `TestingResearchIllinois:main`, and discarded all my changes that I had made on the `fix-flaky` branch. After that I force pushed which resulted in the closure of the pull request since my `fix-flaky` branch was the same as `TestingResearchIllinois:main`, and there were no differences/changes between my `fix-flaky` branch and the `TestingResearchIllinois:main` branch. What I should have done was to add my changes after syncing my `fix-flaky` branch with `TestingResearchIllinois:main`, and then I should have force pushed my changes. If I had done this, there would have been differences between the `fix-flaky` branch and the `TestingResearchIllinois:main` branch, and the PR would not have closed. Thank you!

**Comment by darko-marinov** [comment]
Thanks for publicly describing your learning in detail! Great lesson learned.

**Comment by saurabh-shetty** [comment]
Thank you Professor!

**Pull request merged**
