### PR TITLE
Update pr-data.csv to update tests category in idoft

### PR DESCRIPTION
**Pull request by yashdeep97**
For the following tests I found that nondex build succeeded even after checking out the commit `4de9d3d` for the Jprotobuf-rpc-socket repository as mentioned in `pr-data.csv`, and running nondex with 100 runs. 

1. com.baidu.jprotobuf.pbrpc.proto.EchoServicePerformanceTest.multiExecuteValidTest
2. com.baidu.jprotobuf.pbrpc.proto.EchoServicePerformanceTest.performance20TreadsTest
3. com.baidu.jprotobuf.pbrpc.proto.EchoServicePerformanceTest.performanceOneTreadTest2
4. com.baidu.jprotobuf.pbrpc.proto.EchoServicePerformanceTest.performanceOneTreadTestWithLongText
5. com.baidu.jprotobuf.pbrpc.proto.EchoServiceTest.testAttachment
6. com.baidu.jprotobuf.pbrpc.TrunkEchoServiceTest.testGzip

These tests were added as part of this PR: https://github.com/TestingResearchIllinois/idoft/pull/365

### CODE REVIEW

**Comment by darko-marinov** [comment]
Did you run the entire class(es) and test suite multiple times to check if the tests fail? From the name, it looks like some tests may have been `NOD` (depend on timing) and not `ID`.

**Comment by yashdeep97** [comment]
So I ran all the tests in the EchoServicePerformanceTest class and noticed intermittent errors due io failures
(All the tests execute multiple thread pools)
Example error: 
```io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: 0.0.0.0/0.0.0.0:1031```
(However, I did not observe any test failures.)
 
Most of the tests that depend on timing do not have assert statements and only print the time taken to execute the threads.

I'm not sure how to proceed if the tests give intermittent errors instead of failures. Would greatly appreciate any inputs!

**Comment by darko-marinov** [comment]
Please change `ID` to `NOD` as appropriate. You should also update commit SHA as appropriate.

**Comment by yashdeep97** [comment]
> Please change `ID` to `NOD` as appropriate. You should also update commit SHA as appropriate.

Done. Changed test category to `NOD` and updated commit SHA to lates commit after verifying that the tests are NOD in the latest commit in master.

**Comment by darko-marinov** [comment]
Thanks for the updates. Do you have logs that could help in debugging these `NOD` tests, e.g., stack trace of a failure for each test? Do the tests fail with just Surefire, without NonDex, e.g., `for i in {1..100}; do mvn test -Dtest=TestClass#testMethod | tee log-${i}.txt; done`?

**Comment by yashdeep97** [comment]
> Thanks for the updates. Do you have logs that could help in debugging these `NOD` tests, e.g., stack trace of a failure for each test? Do the tests fail with just Surefire, without NonDex, e.g., `for i in {1..100}; do mvn test -Dtest=TestClass#testMethod | tee log-${i}.txt; done`?

Yes, I have nondex execution logs for all the tests, containing the stack trace. What would be a good way to share them? I could add the commonly occurring error here in the comments or could share the files over email.
As for running the tests repeatedly without Nondex, I did not observe any failures.

**Comment by yashdeep97** [comment]
The nondex execution logs for all the tests, containing the stack trace can be found in ythorat2@fa23-cs527-068.cs.illinois.edu:~/Jprotobuf-rpc-socket/baidu-nondex-log-{test_id}.txt files.

**Pull request closed without merging**
