### PR TITLE
Found, Fix and Opened PR for 3 tests in Koryphe

### PR DESCRIPTION
**Pull request by kevin952**
Found, Fixed and opened real PR for 3 tests in Koryphe!

### CODE REVIEW

**Comment by darko-marinov** [comment]
Please squash 3 commits into 1.

**Comment by kevin952** [comment]
> Please squash 3 commits into 1.

done!

**Comment by darko-marinov** [comment]
Please resolve conflicts.

**Comment by kevin952** [comment]
> Please resolve conflicts.

done!

**Pull request merged**
