### PR TITLE
Fix flaky tests in eBay jsonex project

### PR DESCRIPTION
**Pull request by chessvivek**
PR here for more info - https://github.com/eBay/jsonex/pull/47

### CODE REVIEW

**Comment by chessvivek** [comment]
In the checks, it says that the notes are invalid. Do you know why?

**Comment by winglam** [comment]
Did you see the following about Notes?
https://github.com/TestingResearchIllinois/idoft#adding-notes
https://github.com/TestingResearchIllinois/idoft#detailed-information-for-each-column

**Comment by chessvivek** [comment]
Thanks @winglam for bringing the Notes contribution guidelines to my attention. I have fixed the formatting issues now.

**Comment by darko-marinov** [comment]
I'm accepting the PR as is now, although the text from https://github.com/TestingResearchIllinois/idoft/issues/556 could have been directly in the comments. Did you look to fix the remaining three tests: `CliParserTest.testParse`, `ClassUtilTest.testGetProperties`, and `SnapshotTest.testSnapshot`?

**Pull request merged**
