### PR TITLE
Added 14 new tests in Univocity Parsers

### PR DESCRIPTION
**Pull request by kevin952**
Detected 14 new tests in Univocity Parsers repo

### CODE REVIEW

**Comment by darko-marinov** [comment]
Do you have logs for running each test individually?

**Comment by kevin952** [comment]
> Do you have logs for running each test individually?

I have the complete nondexLog for 10 runs on the repo!

**Comment by kevin952** [comment]
> Are you running 10 times all tests? If so, does NonDex report the same set of failing tests every time?
> 
> Or are you running 10 times each individual test? If so, does each fail/pass deterministically for the same seeds?

Im running 10 times on all tests and it reports the same set of failing tests every time!

**Comment by darko-marinov** [comment]
Are you going to debug these, or can @zzjas assign them to someone else?

**Pull request merged**
