### PR TITLE
Adding flaky tests pr's with this pull request

### PR DESCRIPTION
**Pull request by njain2208**

### CODE REVIEW

**Comment by zzjas** [comment]
Ah my bad I forgot about the karate repo when you reserved it for detecting new tests. They won't fix flaky tests.

The `kiegroup/drools` developer responded to your PR. Please follow up. You should open a new PR to their new repo and update the test entries here to point to the new repo.

**Comment by zzjas** [comment]
Ok to merge once commits squashed

**Comment by njain2208** [comment]
I have squashed the commits.

**Comment by zzjas** [comment]
Ok to merge @darko-marinov

**Comment by njain2208** [comment]
Have updated the PRs as they got accepted.

**Comment by zzjas** [comment]
That's great! Still ok to merge @darko-marinov

**Pull request merged**
