### PR TITLE
Update pr-data.csv status to Opened [cloudslang]

### PR DESCRIPTION
**Pull request by yijut2**
Opened PR in cloudslang project

### CODE REVIEW

**Comment by darko-marinov** [comment]
Please squash your 9 commits into 1.

**Comment by yijut2** [comment]
> Please squash your 9 commits into 1.

I have tried to squash them but it failed anyway. My fork repo always show 
`This branch is [10 commits ahead](https://github.com/yijut2/idoft/compare/TestingResearchIllinois:idoft:main...main) of TestingResearchIllinois:main.`

My previous merged commit kept appeared in my new PR. Can I know how to fix that?

**Comment by yijut2** [comment]
I think I found the reason. Since I clicked sync fork directly on github, github automatically merge the two repo for me, so it merge my previous commit information together. Then when I submitted my PR next time, the previous commit information also appear. I found the correct way to create the new PR. Do you mind if I close this PR and reopen the new one (follow the correct ways to open PR)?

**Comment by yijut2** [comment]
Hi professor, 

I would first close this PR and reopen the new one.

**Pull request closed without merging**
