### PR TITLE
DeveloperFixed tests

### PR DESCRIPTION
**Pull request by kevin952**
Added some DeveloperFixedTests with the right commit for Flink.

### CODE REVIEW

**Comment by zzjas** [comment]
Do you have the log showing:

1. Failing NonDex for the commit's parent
2. Passing NonDex on this commit

Please let me know you VM ID and path to logs privately.

**Comment by darko-marinov** [comment]
Besides informing ZIjie about logs, please resolve the conflicts.

**Comment by darko-marinov** [comment]
If `7542b56` compiles and passes, it's likely that its parent [fa1036c](https://github.com/apache/flink/commit/fa1036c73e3bcd66b57d835c7859572ca4b2250d)
should also compile because `7542b56` is relatively small. How can you claim that this commit fixes the test is you don't know whether the previous fails? Also, did you run this commit with a relatively high `-DnondexRuns=`?

**Comment by kevin952** [comment]
> If `7542b56` compiles and passes, it's likely that its parent [fa1036c](https://github.com/apache/flink/commit/fa1036c73e3bcd66b57d835c7859572ca4b2250d) should also compile because `7542b56` is relatively small. How can you claim that this commit fixes the test is you don't know whether the previous fails? Also, did you run this commit with a relatively high `-DnondexRuns=`?

Sorry, I was a  bit focused on my finals. you can close this with -ve points. It was a great course!

**Comment by average-avancha** [comment]
Could not replicate reported behavior as both fix commit [7542b56f2abb860f42a83c4687f6e38bb82b78c6](https://github.com/apache/flink/commit/7542b56f2abb860f42a83c4687f6e38bb82b78c6) and parent [fa1036c73e3bcd66b57d835c7859572ca4b2250d](https://github.com/apache/flink/commit/fa1036c73e3bcd66b57d835c7859572ca4b2250d) failed to build with nested compile issues.

I was able to build the latest tag [release-1.19.0](https://github.com/apache/flink/releases/tag/release-1.19.0) which includes the reported fix commit. The three reported tests did not fail with Nondex shuffling `(-DnondexRuns=10000)` which loosely supports the claim that the flakiness in these tests was fixed.

See [PR#1241](https://github.com/TestingResearchIllinois/idoft/pull/1241) for more flaky tests discovered in the latest release and Nondex log.

**Comment by darko-marinov** [comment]
Closed with negative points.

**Pull request closed without merging**
