### PR TITLE
DeveloperFixed org.apache.rocketmq.common.UtilAllTest.testCalculateFileSizeInPath

### PR DESCRIPTION
**Pull request by Einsteinnnnn**
DeveloperFixed
`https://github.com/apache/rocketmq,3c0b3307011fad53f811e08d05147d94fc6c0d67,common,org.apache.rocketmq.common.UtilAllTest.testCalculateFileSizeInPath,ID,DeveloperFixed,https://github.com/apache/rocketmq/pull/7445,
`

pr link: https://github.com/apache/rocketmq/pull/7445

### CODE REVIEW

**Comment by darko-marinov** [comment]
We need more evidence that the specific PR fixed the test. Please follow up on my email.

**Comment by Einsteinnnnn** [comment]
> We need more evidence that the specific PR fixed the test. Please follow up on my email.

The commit corresponds to the pr: `5d492c338258d07613103e6ae16df4c6fa5b3838`. For more details please see the email.

**Comment by darko-marinov** [comment]
Please add the link to the commit `5d492c338258d07613103e6ae16df4c6fa5b3838` in the last column (`Notes`).

**Comment by Einsteinnnnn** [comment]
> Please add the link to the commit `5d492c338258d07613103e6ae16df4c6fa5b3838` in the last column (`Notes`).

Fixed

**Comment by darko-marinov** [comment]
You didn't put a *link* to the commit. You just put the commit SHA.

Also please rebase on the latest `main` and resolve conflicts.

**Comment by Einsteinnnnn** [comment]
> You didn't put a _link_ to the commit. You just put the commit SHA.
> 
> Also please rebase on the latest `main` and resolve conflicts.

I successfully solved the conflicts, but it shows many file changes. It includes my change, but I'm not sure if it is ok.

**Comment by darko-marinov** [comment]
The change doesn't look good (5 files, +365 −107 lines). Please put only your changes in the PR, and ideally quash them in one commit.

**Pull request merged**
