### PR TITLE
Added 9 json-io ID tests

### PR DESCRIPTION
**Pull request by FarmersWrap**
Test result can be found here: file:///home/yu129/new_proj/json-io/.nondex/Mkm0RbUoygCbJqpnhubRy5luIgZuH7uRvQxuUJZJGzw=/test_results.html.     

build logs, normal test logs and nondex logs can be found here /home/yu129/new_proj/jsonio-logs and /home/yu129/new_proj/jsonio-logs1

They are identified as ID.

### CODE REVIEW

**Comment by darko-marinov** [comment]
Where are the logs for running each test individually? NonDex doesn't claim that the tests that fail are `ID`; they could be `NOD`.

**Comment by FarmersWrap** [comment]
> Where are the logs for running each test individually? NonDex doesn't claim that the tests that fail are `ID`; they could be `NOD`.

The tests are run individually, logs can be found here: /home/yu129/new_proj/json-io/test_result1.txt-com.cedarsoftware.util.io.AtomicBooleanTest-testAssignAtomicBoolean-1701639025.  All of the tests pass the normal ones after 30 runs.

**Comment by FarmersWrap** [comment]
> Squash two commits into one. Do all tests also pass/fail deterministically for all NonDex seeds?

Yes, some seeds always fail, the others always pass. I guess the seeds determine the patterns were shuffled.

**Comment by zzjas** [comment]
Ok to merge @darko-marinov

**Pull request merged**
