### PR TITLE
Opened 3 PRs for Gradle tests

### PR DESCRIPTION
**Pull request by wuh3**
VM: 097

Logs for ChestCounter: ~/final_project/ChestCounter.
Logs for JakduK: ~/final_project/jakduk-api,
Logs for gradle-crossbuild-scala: ~/final_project/gradle-crossbuild-scala.

All logs are named with prefix "mvn-install, mvn-dtest, mvn-nondex".

### CODE REVIEW

**Comment by zzjas** [comment]
Changes are fine to merge but please try to sync your fork.

Also, in the future, please don't raise PR from your fork's main branch. Keep the main branch clean and use a new branch for each PR. This will make your life easier.

**Comment by darko-marinov** [comment]
Rebase your work on top of `main` so you have only one commit. As Zijie said, don't use `main` for your work in the future.

**Comment by wuh3** [comment]
I tried to use git rebase -i HEAD~160 since this PR shows I have 160 commits. But, after it shows Successfully rebased and updated refs/heads/haozhew3. The PR still says there are 160 commits

**Comment by zzjas** [comment]
That's because your fork's main branch is behind `idoft/main`. You need to rebase on the current IDoFT main. Or create a different branch in your fork, then use GitHub `sync` to sync your main and the IDoFT main.

**Pull request closed without merging**
