### PR TITLE
Update five ID tests to `MovedOrRenamed`

### PR DESCRIPTION
**Pull request by Jake-WangZhi**
These five ID tests in [nifi](https://github.com/apache/nifi) have been moved in this [commit](https://github.com/apache/nifi/commit/a126f6a7dff64f2d6a1db1832890d696df11e67b)

I used these two commands to find the commit

```
git log --all -- ./nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/status/history/EmbeddedQuestDbStatusHistoryRepositoryForNodeTest.java
```

```
git log --all -- ./nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/status/history/EmbeddedQuestDbStatusHistoryRepositoryForComponentsTest.java
```

### CODE REVIEW

**Comment by darko-marinov** [comment]
See the previous comment (can reply to me via email).

**Comment by Jake-WangZhi** [comment]
> See the previous comment (can reply to me via email).

`git log --diff-filter=D -- ./nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/status/history/
EmbeddedQuestDbStatusHistoryRepositoryForComponentsTest.java`

`git log --diff-filter=D -- ./nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/status/history/EmbeddedQuestDbStatusHistoryRepositoryForNodeTest.java
`

**Comment by darko-marinov** [comment]
This command seems the same as in the other PR, but there it's `Deleted`, and here it's `MovedOrRenamed`. How could one distinguish those cases (ideally in an automated way)?

**Comment by Jake-WangZhi** [comment]
> This command seems the same as in the other PR, but there it's `Deleted`, and here it's `MovedOrRenamed`. How could one distinguish those cases (ideally in an automated way)?

@darko-marinov 

I’m not sure if I’ll have enough time to come up with a script this week. However, here’s what I’ve done so far:

Since `git log` doesn’t include a diff filter for moved files, my understanding is that moved files are essentially treated as a file being deleted and the exact same file being created in a new location, I used `git log --diff-filter=D` After identifying this commit, I ran git show a126f6a7dff64f2d6a1db1832890d696df11e67b to browse through each changed file, and I found these changes, which confirm that the two files were moved rather than deleted.

Do I need to come up with a script to get this PR merged? Or is it possible to merge it now and try to add the script later if I have time? Thank you

```
rename from nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/status/history/EmbeddedQuestDbStatusHistoryRepositoryForComponents
Test.java
rename to nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-questdb-bundle/nifi-framework-questdb-status-history/src/test/java/org/apache/nifi/controller/status/history/Embed
dedQuestDbStatusHistoryRepositoryForComponentsTest.java

rename from nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-core/src/test/java/org/apache/nifi/controller/status/history/EmbeddedQuestDbStatusHistoryRepositoryForNodeTest.j
ava
rename to nifi-nar-bundles/nifi-framework-bundle/nifi-framework/nifi-framework-questdb-bundle/nifi-framework-questdb-status-history/src/test/java/org/apache/nifi/controller/status/history/Embed
dedQuestDbStatusHistoryRepositoryForNodeTest.java
```

**Comment by darko-marinov** [comment]
I'll accept this for now, but if you want more "points" for `Deleted`, `MovedOrRenamed`, and such, then you should add some automation.

**Pull request merged**
