### PR TITLE
Update gr-data.csv

### PR DESCRIPTION
**Pull request by Ellen99**
adding 2 flaky test lines from start.xenit.eu repository

### CODE REVIEW

**Comment by darko-marinov** [comment]
Can you please update https://github.com/TestingResearchIllinois/idoft/tree/main/format_checker to check this `gr-data.csv` file in addition to `pr-data.csv`?

**Comment by Ellen99** [comment]
I've created a PR for the change

**Comment by darko-marinov** [comment]
Your need to change https://github.com/TestingResearchIllinois/idoft/blob/main/.github/workflows/ci.yml and what it invokes, likely https://github.com/TestingResearchIllinois/idoft/blob/main/format_checker/common_checks.py

**Comment by Ellen99** [comment]
Sorry I just noticed that not all of my changes appear in the PR. (I accidentally removed the branch on which I was working)
Will send another PR soon.

**Comment by darko-marinov** [comment]
I'm accepting this for now, but we should finish the checker.

**Pull request merged**
