### PR TITLE
Add flaky tests

### PR DESCRIPTION
**Pull request by lxb007981**
Found some ID flaky tests. Or at least they somehow failed under the nondex tool. The execution log can be found at 
[nondex_log.tar.gz](https://github.com/TestingResearchIllinois/idoft/files/13542528/nondex_log.tar.gz)

I tried fixing them but  it seemed a mess to me. I would appreciate it if anyone could give some advice.

### CODE REVIEW

**Comment by darko-marinov** [comment]
Did you run each test individually? Does it fail/pass deterministically for all NonDex seeds?

**Comment by lxb007981** [comment]
> Did you run each test individually? Does it fail/pass deterministically for all NonDex seeds?

Yes. Each test passed on its own and failed when ran with nondex for any seed. Here is the running [log](https://github.com/TestingResearchIllinois/idoft/files/13552410/log.tar.gz) for each test ran individually.

**Comment by darko-marinov** [comment]
Don't upload files to GitHub. Just put them on your VM (e.g., use "scp" if needed) and let us know the absolute path.

**Comment by darko-marinov** [comment]
@zzjas please check the logs.

**Comment by zzjas** [comment]
Could you please save the printed log (e.g. `mvn nondex |& tee some.log`), not the `.nondex` directory for easier check?

**Comment by lxb007981** [comment]
> Could you please save the printed log (e.g. `mvn nondex |& tee some.log`), not the `.nondex` directory for easier check?

I believe these are the printed log?

**Comment by zzjas** [comment]
Oh my bad I used `nondex_log.tar.gz`

Logs are ok. Ok to merge @darko-marinov

**Pull request merged**
