### PR TITLE
Status update 

### PR DESCRIPTION
**Pull request by rRajivramachandran**
I had two PRs to cloud stack:
1. https://github.com/apache/cloudstack/pull/8183 : It is accepted and fixes `com.cloud.server.StatsCollectorTest.java#persistVirtualMachineStatsTestPersistsSuccessfully`. This is line 1052 in the later version of the diff
2. https://github.com/apache/cloudstack/pull/8185: It has been approved by two reviewers however there is a comment saying "Nicira is likely not support, unmaintained " and the approval workflow requires approval from a maintainer. Hence marking the fix as accepted in Idoft as it is the closest state. Please let me know if this isnt ok.

This fixes the following 3 ID tests:
(before commit):
```
[INFO] *********
[INFO] All tests pass without NonDex shuffling
[INFO] ####################
[INFO] Across all seeds:
[INFO] com.cloud.network.nicira.NiciraRestClientTest#testExecuteTwoConsecutiveUnauthorizedExecutions
[INFO] com.cloud.network.nicira.NiciraRestClientTest#testExecuteLiveLockWhenControllerAllowsLoginAndFollowsWithUnauthorizedButDoesNotRediect
[INFO] com.cloud.network.nicira.NiciraRestClientTest#testExecuteUnauthorizedThenSuccess
[INFO] Test results can be found at: 
[INFO] file:///home/rajivr3/cloudstack/plugins/network-elements/nicira-nvp/.nondex/xOAAavN0j3WKNY7UV5SS6VaIEihGrgwuwWiO5XGSBWU=/test_results.html
[INFO] [NonDex] The id of this run is: xOAAavN0j3WKNY7UV5SS6VaIEihGrgwuwWiO5XGSBWU=
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
```

After commit:
```
[INFO] mvn nondex:nondex  -DnondexFilter='.*' -DnondexMode=FULL -DnondexSeed=1016066 -DnondexStart=0 -DnondexEnd=9223372036854775807 -DnondexPrintstack=false -DnondexDir="/home/rajivr3/cloudstack/plugins/network-elements/nicira-nvp/.nondex" -DnondexJarDir="/home/rajivr3/cloudstack/plugins/network-elements/nicira-nvp/.nondex" -DnondexExecid=uVSTFBPHjI8MPBhfx5qA01zpTZhsfGY5aPbRRip+o= -DnondexLogging=CONFIG
[INFO] No Test Failed with this configuration.
[INFO] *********
[INFO] All tests pass without NonDex shuffling
[INFO] ####################
[INFO] Across all seeds:
[INFO] Test results can be found at: 
[INFO] file:///home/rajivr3/cloudstack/plugins/network-elements/nicira-nvp/.nondex/+ROC+9N5ojp02LwvgYxy8sqoiIrckuz0VSBt9N78q+c=/test_results.html
[INFO] [NonDex] The id of this run is: +ROC+9N5ojp02LwvgYxy8sqoiIrckuz0VSBt9N78q+c=
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
```
2 of these tests were already present in IDoft which were:
`testExecuteLiveLockWhenControllerAllowsLoginAndFollowsWithUnauthorizedButDoesNotRediect` and
`testExecuteTwoConsecutiveUnauthorizedExecutions`.

The one not present was added with the current head commit as it was verified flaky at this commit:
`testExecuteUnauthorizedThenSuccess`

All three are marked as Accepted with this PR

### CODE REVIEW

**Comment by darko-marinov** [comment]
https://github.com/apache/cloudstack/pull/8185 is opened not accepted

**Comment by rRajivramachandran** [comment]
Im not sure if it would be ever merged as there are no maintainers for this component, according to their comments. Since it was approved by both reviewers have marked as accepted. Please advise on how to proceed

**Comment by darko-marinov** [comment]
Just keep `Opened`. Many PRs are never merged.

**Comment by rRajivramachandran** [comment]
Updated status to Opened

**Pull request merged**
