### PR TITLE
Updating the status of six tests in json-io to "MovedOrRenamed"

### PR DESCRIPTION
**Pull request by Jake-WangZhi**
Six flaky tests on [json-io](https://github.com/jdereg/json-io) has been moved to different module paths. Here is the commit: https://github.com/jdereg/json-io/commit/45699f116bdaac9449cc58fbdd9310f00ac6df5b

### CODE REVIEW

**Comment by darko-marinov** [comment]
Please split PRs for `Opened` (which is very easy to accept) and `MovedOrRenamed` (which takes more inspection).

**Comment by Jake-WangZhi** [comment]
> Please split PRs for `Opened` (which is very easy to accept) and `MovedOrRenamed` (which takes more inspection).

Okay, should I close this PR then?

**Comment by darko-marinov** [comment]
No, please do *not* close. Revise this PR to keep one of the two kinds of changes. Then open a new PR with the other kind.

**Comment by Jake-WangZhi** [comment]
@darko-marinov 
I've revised it. Thank you

**Comment by darko-marinov** [comment]
Please squash commits (and rebase your work on top of the latest `main`).

**Comment by Jake-Zhi0Wang** [comment]
> Please squash commits (and rebase your work on top of the latest `main`).

@darko-marinov  Done! Let me know if there is anything else needed. Thank you

**Comment by Jake-WangZhi** [comment]
> Please squash commits (and rebase your work on top of the latest `main`).

@darko-marinov Done! Let me know if there is anything else needed. Thank you

**Comment by Jake-WangZhi** [comment]
> > Please squash commits (and rebase your work on top of the latest `main`).
> 
> @darko-marinov Done! Let me know if there is anything else needed. Thank you

I noticed there were two more flaky tests moved under the same commit, so I added them as well

**Comment by darko-marinov** [comment]
Where were the files moved? What do you get for `git show --name-status 45699f116bdaac9449cc58fbdd9310f00ac6df5b | grep FILE` for those `FILE`s?

Are the tests in the new location still `ID` in the latest project version?

**Comment by Jake-WangZhi** [comment]
> Where were the files moved? What do you get for `git show --name-status 45699f116bdaac9449cc58fbdd9310f00ac6df5b | grep FILE` for those `FILE`s?
> 
> Are the tests in the new location still `ID` in the latest project version?

Five of them are still ID, one of them is not. 

The maintainer just got rid of the `util` folder in this commit: https://github.com/jdereg/json-io/commit/45699f116bdaac9449cc58fbdd9310f00ac6df5b.

**Comment by Jake-WangZhi** [comment]
> Where were the files moved? What do you get for `git show --name-status 45699f116bdaac9449cc58fbdd9310f00ac6df5b | grep FILE` for those `FILE`s?
> 
> Are the tests in the new location still `ID` in the latest project version?

Sorry for the late reply, here is what I got for running the command you asked for each file

```
jakew4@fa24-cs527-043:~/json-io/src/test/java/com/cedarsoftware/io$ git show --name-status 45699f116bdaac9449cc58fbdd9310f00ac6df5b | grep AtomicBooleanTest.java
R084    src/test/java/com/cedarsoftware/util/io/AtomicBooleanTest.java  src/test/java/com/cedarsoftware/io/AtomicBooleanTest.java
jakew4@fa24-cs527-043:~/json-io/src/test/java/com/cedarsoftware/io$ git show --name-status 45699f116bdaac9449cc58fbdd9310f00ac6df5b | grep AtomicLongTest.java
R085    src/test/java/com/cedarsoftware/util/io/AtomicLongTest.java     src/test/java/com/cedarsoftware/io/AtomicLongTest.java
jakew4@fa24-cs527-043:~/json-io/src/test/java/com/cedarsoftware/io$ git show --name-status 45699f116bdaac9449cc58fbdd9310f00ac6df5b | grep CollectionTests.java
R099    src/test/java/com/cedarsoftware/util/io/CollectionTests.java    src/test/java/com/cedarsoftware/io/CollectionTests.java
jakew4@fa24-cs527-043:~/json-io/src/test/java/com/cedarsoftware/io$ git show --name-status 45699f116bdaac9449cc58fbdd9310f00ac6df5b | grep MapsTest.java
R099    src/test/java/com/cedarsoftware/util/io/MapOfMapsTest.java      src/test/java/com/cedarsoftware/io/MapOfMapsTest.java
R099    src/test/java/com/cedarsoftware/util/io/MapsTest.java   src/test/java/com/cedarsoftware/io/MapsTest.java
jakew4@fa24-cs527-043:~/json-io/src/test/java/com/cedarsoftware/io$ git show --name-status 45699f116bdaac9449cc58fbdd9310f00ac6df5b | grep NoTypeTest.java
R095    src/test/java/com/cedarsoftware/util/io/NoTypeTest.java src/test/java/com/cedarsoftware/io/NoTypeTest.java
jakew4@fa24-cs527-043:~/json-io/src/test/java/com/cedarsoftware/io$ git show --name-status 45699f116bdaac9449cc58fbdd9310f00ac6df5b | grep PrettyPrintTest.java
R098    src/test/java/com/cedarsoftware/util/io/PrettyPrintTest.java    src/test/java/com/cedarsoftware/io/PrettyPrintTest.java
```

**Comment by darko-marinov** [comment]
Okay, I'm accepting `MovedOrRenamed`, but you should likely add the new `ID` tests that you found in the latest commit.

**Comment by Jake-WangZhi** [comment]
> Okay, I'm accepting `MovedOrRenamed`, but you should likely add the new `ID` tests that you found in the latest commit.

I was doing that, but you asked me to split them, so I created another PR, which has already been merged: https://github.com/TestingResearchIllinois/idoft/pull/1378.

I fixed four of the tests and added them to iDoFT. I’ll add the other one that is still ID.

I had a question about the one that is no longer ID. Should I still add it with the updated module path and mark its status as 'deleted'?

**Comment by darko-marinov** [comment]
Sorry I forgot that the previously accepted PR was related to these same tests.

For the fifth test, if you can confirm (with some saved evidence) that it was `ID` somewhere between being moved and being deleted, then you can add a new row with `Deleted`. Otherwise, if you can't confirm that it was ever `ID` after being moved, it's not appropriate to add a new row.

**Comment by Jake-WangZhi** [comment]
> Sorry I forgot that the previously accepted PR was related to these same tests.
> 
> For the fifth test, if you can confirm (with some saved evidence) that it was `ID` somewhere between being moved and being deleted, then you can add a new row with `Deleted`. Otherwise, if you can't confirm that it was ever `ID` after being moved, it's not appropriate to add a new row.

@darko-marinov
Hey Dr. Marinov, thanks for the guidance, I've opened a PR for this case. Could you take a look when available? Thank you

https://github.com/TestingResearchIllinois/idoft/pull/1395

**Pull request merged**
