### PR TITLE
Moved ignite-3 test

### PR DESCRIPTION
**Pull request by DaniellaHubble**
The tests (including "testMultiThread") in "AbstractFreeListTest.java" were moved to "FreeListImplTest.java" [here](https://github.com/apache/ignite-3/commit/7f93d63d09c429e66e955a2eb9b86de99b845358).

When I ran: `git show --name-status 7f93d63d09c429e66e955a2eb9b86de99b845358 | grep -i AbstractFreeListTest`
I got:
R087	modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/freelist/AbstractFreeListTest.java	modules/page-memory/src/test/java/org/apache/ignite/internal/pagememory/freelist/FreeListImplTest.java

### CODE REVIEW

**Comment by darko-marinov** [comment]
Is the test still `ID` in the new class?

**Comment by DaniellaHubble** [comment]
According to my Nondex testing it is still flaky and ID.

**Comment by darko-marinov** [comment]
Please open a new PR to add in `gr-data.csv` a new row for this test and also more rows for all `ID` test. Ideally provide commands/`Dockerfile` for reproducing the `ID` tests that you find.

**Comment by DaniellaHubble** [comment]
A PR to add this flaky test was made ([link here](https://github.com/TestingResearchIllinois/idoft/pull/1560)). I have not found any other non-reported ID flaky tests besides this one yet.

**Pull request merged**
