### PR TITLE
4 New Flaky tests detected + Raised + accepted in FastJSON2

### PR DESCRIPTION
**Pull request by krishnanand5**
I have identified the following flaky tests in `fastjson1-compatible` module of FastJSON2 repo.

- `com.alibaba.fastjson.issue_2100.Issue2182#test_for_issue`.
- `com.alibaba.fastjson.issue_2400.Issue2447#test_for_issue`.
- `com.alibaba.fastjson.issue_1100.Issue1177_1#test_for_issue`.
- `com.alibaba.fastjson.issue_2400.Issue2428#test_for_issue`.

VM : kag8@fa23-cs527-019.cs.illinois.edu
Path to Logs: /home/kag8/new-tests/Fastjson2/fastjson1-compatible
Github issue : https://github.com/alibaba/fastjson2/issues/2029
PR Link for the 4 tests : https://github.com/alibaba/fastjson2/pull/2030

### CODE REVIEW

**Comment by krishnanand5** [comment]
The 4 tests have been merged by the developer and hence I have updated the status

**Comment by krishnanand5** [comment]
I apologize for the large number of commits. The merge conflict is owing to the fact that I had raised fresh fastjson2 updates before https://github.com/TestingResearchIllinois/idoft/pull/1039 got merged.

**Comment by darko-marinov** [comment]
Please rebase your chances on the latest `main`.

**Comment by krishnanand5** [comment]
Greetings Professor,

I have rebased my changes on top of the current main branch. 

Regards,
Krishna Anandan Ganesan

**Comment by darko-marinov** [comment]
Please squash your 7 commits into 1.

**Pull request merged**
