### PR TITLE
Update one ID test to `MovedOrRenamed`

### PR DESCRIPTION
**Pull request by Jake-WangZhi**
This ID test in [nifi](https://github.com/apache/nifi) have been moved in this [commit](https://github.com/apache/nifi/commit/42a4385c82d0bbe1428096fb0b634c9f9747f91b)

I used this command to find the commit

```
git log --all -- ./nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/wag/TestInvokeAmazonGatewayApiMock.java
```

### CODE REVIEW

**Comment by darko-marinov** [comment]
As for the other two PRs, can you list all commands/steps needed to find the commit? Moreover, could you write a script that helps find these cases (for some bonus "points")?

**Comment by Jake-WangZhi** [comment]
> As for the other two PRs, can you list all commands/steps needed to find the commit? Moreover, could you write a script that helps find these cases (for some bonus "points")?

I also used this command to find the exact commit

`git log --diff-filter=D -- ./nifi-nar-bundles/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/wag/TestInvokeAmazonGatewayApiMock.java`

**Comment by Jake-WangZhi** [comment]
@darko-marinov 

I also ran this command to confirm that this test was moved rather than deleted

```
git show --summary 42a4385c82d0bbe1428096fb0b634c9f9747f91b | grep "TestInvokeAmazonGatewayApiMock.java""
 rename {nifi-nar-bundles => nifi-extension-bundles}/nifi-aws-bundle/nifi-aws-processors/src/test/java/org/apache/nifi/processors/aws/wag/TestInvokeAmazonGatewayApiMock.java (100%)
```

**Comment by darko-marinov** [comment]
Using `git show ... | grep ...` is already more advanced then using just one command. Again, I'm accepting this PR but for more, you should look to advance automation.

**Pull request merged**
