### PR TITLE
Fixed unused imports and variables warnings by flake8

### PR DESCRIPTION
**Pull request by Ellen99**
Removed unused imports and variables.
ignored other check flags in the workflow to address them in other PRs

flake8 --extend-ignore=`E501`,`E305`,`W292`,`E291`,`E302`,`E225`,`W291`,`W293`,`E251`,`E231`

### CODE REVIEW

**Comment by darko-marinov** [comment]
Please resolve the conflict now that I accepted another PR, so I can also accept this.

**Comment by Ellen99** [comment]
> Please resolve the conflict now that I accepted another PR, so I can also accept this.

done

**Comment by darko-marinov** [comment]
End-of-line is missing in the `flake8-checker.yml` (which is somewhat ironic for PRs related to blank spaces :), but fine to accept.

**Comment by Ellen99** [comment]
seems like some parts of [this commit](https://github.com/TestingResearchIllinois/idoft/commit/90dd28bf9503ed23d672bde4fb3e82f38772e9e5) are not merged, as the main branch does not reflect changes done in that commit.

For ex. in the commit you can see flake8-checker.yml has _end-of-line_, but in main, it doesn't, and also in valid_repo_extractor.py file.

Maybe I made a mistake when I resolved the conflicts Im not sure.

**Pull request merged**
