### PR TITLE
Added 3 Accepted tests

### PR DESCRIPTION
**Pull request by saurabh-shetty**
Identified 3 flaky tests in https://github.com/FasterXML/jackson-databind. Fixed the 3 tests. Changes got Accepted.

### CODE REVIEW

**Comment by zzjas** [comment]
Please rebase or fix format issue so that this PR only shows the lines you changed :)

**Comment by saurabh-shetty** [comment]
I will try to do that. I might need your help if I am unable to pass the format check after multiple attempts :) Thank you!

**Comment by zzjas** [comment]
It might not be a format checker issue but an EOL issue since I saw "Add files via upload". You can try to add through git locally and check the number of lines changed.

**Comment by saurabh-shetty** [comment]
Yes, it is an EOL issue. Got it, I will try adding through git locally and will check the number of lines changed. Thank you!

**Comment by darko-marinov** [comment]
Please squash 2 commits into 1.

**Comment by saurabh-shetty** [comment]
Got it Professor. Thank you!

**Comment by saurabh-shetty** [comment]
Thank you!

**Pull request merged**
