### PR TITLE
Found new tests in depgraph-maven-plugin

### PR DESCRIPTION
**Pull request by Sujishark**
Found 17 new tests in depgraph-maven-plugin

com.github.ferstl.depgraph.dependency.json.GraphIntegrationTest.graphInJson
com.github.ferstl.depgraph.dependency.json.JsonDependencyNodeNameRendererTest.omitScope
com.github.ferstl.depgraph.dependency.json.JsonDependencyNodeNameRendererTest.renderAll
com.github.ferstl.depgraph.dependency.json.JsonDependencyNodeNameRendererTest.renderArtifactIdVersion
com.github.ferstl.depgraph.dependency.json.JsonDependencyNodeNameRendererTest.renderArtifactIdVersionOptional
com.github.ferstl.depgraph.dependency.json.JsonDependencyNodeNameRendererTest.renderClassifiers
com.github.ferstl.depgraph.dependency.json.JsonDependencyNodeNameRendererTest.renderGroupId
com.github.ferstl.depgraph.dependency.json.JsonDependencyNodeNameRendererTest.renderGroupIdArtifactId
com.github.ferstl.depgraph.dependency.json.JsonDependencyNodeNameRendererTest.renderGroupIdArtifactIdOptional
com.github.ferstl.depgraph.dependency.json.JsonDependencyNodeNameRendererTest.renderGroupIdArtifactIdVersion
com.github.ferstl.depgraph.dependency.json.JsonDependencyNodeNameRendererTest.renderGroupIdArtifactIdVersionOptional
com.github.ferstl.depgraph.dependency.json.JsonDependencyNodeNameRendererTest.renderGroupIdVersion
com.github.ferstl.depgraph.dependency.json.JsonDependencyNodeNameRendererTest.renderGroupIdVersionOptional
com.github.ferstl.depgraph.dependency.json.JsonDependencyNodeNameRendererTest.renderJarTypeOnly
com.github.ferstl.depgraph.dependency.json.JsonDependencyNodeNameRendererTest.renderOptional
com.github.ferstl.depgraph.dependency.json.JsonDependencyNodeNameRendererTest.renderTypes
com.github.ferstl.depgraph.dependency.json.JsonDependencyNodeNameRendererTest.renderVersion

### CODE REVIEW

**Comment by darko-marinov** [comment]
Again, how did you confirm that the tests are `ID` and not `NOD`?

**Comment by Sujishark** [comment]
They fail repeatedly for the same seed during all runs. Hence, ID.

**Comment by darko-marinov** [comment]
Where are the logs?

**Comment by Sujishark** [comment]
The logs for all the tests for this project are in my VM: `/home/rajan11/new-tests/depgraph/`

**Pull request merged**
