### PR TITLE
Identified deleted, renamed, and fixed tests in vertx-rabbitmq-client

### PR DESCRIPTION
**Pull request by williamlin0825**
Found two deleted tests, four fixed tests, and one renamed test in vertx-rabbitmq-client.

### CODE REVIEW

**Comment by darko-marinov** [comment]
We'll need evidence for the claimed commit SHAs. Please put log files on your VM and inform Ajitesh and me to check them.

**Comment by williamlin0825** [comment]
The logs are added to the path /home/jhihwei2/logs. @darko-marinov @Ajitesh27

**Comment by darko-marinov** [comment]
@Ajitesh27 let me know if LGTY

**Comment by Ajitesh27** [comment]
LGTM

**Pull request merged**
