### PR TITLE
Adding 31 newly detected mapstruct tests

### PR DESCRIPTION
**Pull request by mihirgune**
I found these tests using the automated runner I contributed in https://github.com/TestingResearchIllinois/idoft/pull/1524.

I ran them again locally just to double check the errors due to the relatively large number.

These tests seem to be failing due to changes in the code format that is expected in some generated code, with errors being similar to this - 

```
[ERROR] org.mapstruct.ap.test.conversion.java8time.Java8TimeConversionTest.testZonedDateTimeToDateMapping                                                                                                        [ERROR]   Run 1: Java8TimeConversionTest.testZonedDateTimeToDateMapping                                                                                                                                          File:                                                                                                                                                                                                              /app/repo/processor/target/compilation-tests/org.mapstruct.ap.test.conversion.java8time.Java8TimeConversionTest/testZonedDateTimeToDateMapping_jdk/generated-sources/org/mapstruct/ap/test/conversion/java8time/SourceTargetMapperImpl.java
and file:
  /app/repo/processor/target/test-classes/fixtures/org/mapstruct/ap/test/conversion/java8time/SourceTargetMapperImpl.java
do not have same content:

Missing content at line 31:
  ["    private final DateTimeFormatter dateTimeFormatter_HH_mm_168697690 = DateTimeFormatter.ofPattern( "HH:mm" );"]

Extra content at line 34:
  ["    private final DateTimeFormatter dateTimeFormatter_HH_mm_168697690 = DateTimeFormatter.ofPattern( "HH:mm" );"]                                                                                                                                                                                                                                                                                                             [ERROR]   Run 2: Java8TimeConversionTest.testZonedDateTimeToDateMapping                                                                                                                                          File:                                                                                                                                                                                                              /app/repo/processor/target/compilation-tests/org.mapstruct.ap.test.conversion.java8time.Java8TimeConversionTest/testZonedDateTimeToDateMapping_eclipse/generated-sources/org/mapstruct/ap/test/conversion/java8time/SourceTargetMapperImpl.java
and file:
  /app/repo/processor/target/test-classes/fixtures/org/mapstruct/ap/test/conversion/java8time/SourceTargetMapperImpl.java
do not have same content:

Extra content at line 30:
  ["    private final DateTimeFormatter dateTimeFormatter_dd_MM_yyyy_11900521056 = DateTimeFormatter.ofPattern( "dd.MM.yyyy" );"]

Missing content at line 32:
  ["    private final DateTimeFormatter dateTimeFormatter_dd_MM_yyyy_11900521056 = DateTimeFormatter.ofPattern( "dd.MM.yyyy" );"]
```

Thanks

### CODE REVIEW

**Comment by darko-marinov** [comment]
In what percentage of seeds do these tests fail if run in isolation `mvn nondex:nondex -DnondexRuns=100 -Dtest=TestClass#testMethod`?

**Comment by mihirgune** [comment]
> In what percentage of seeds do these tests fail if run in isolation `mvn nondex:nondex -DnondexRuns=100 -Dtest=TestClass#testMethod`?

From a quick look at my past runs, it looks like a significant majority are failing. But I'll run itwith the above command and get back to you.

**Comment by mihirgune** [comment]
Larger test file. Github did not allow me to upload an HTML file, and printing it into a .pdf like above cut out a large portion of the seeds. I've compressed the test_results.html file into a ZIP here - 

[mapstruct_test_results.zip](https://github.com/user-attachments/files/18017623/mapstruct_test_results.zip)

**Comment by darko-marinov** [comment]
Why are you attaching files here? They clearly waste GitHub resources. Do you think that they could help someone in debugging?

**Comment by mihirgune** [comment]
Hi, I'm sorry.

I just wanted to attach my test-results file which is showing that all the seeds had failed. 

Would it be preferable if I emailed it over?

**Comment by darko-marinov** [comment]
`scp` to your VM and ask @ajitesh27 to review

**Comment by Ajitesh27** [comment]
Verified logs. 
LGTM

**Pull request merged**
