### PR TITLE
Update pr-data.csv

### PR DESCRIPTION
**Pull request by same8891**
The commit said xmpp test has been move to kotlin. But when I look into test in kotlin file, it seems different to xmpptest.java. The  xmpptest.java test the conference, but I didn't see any related code in kotlin/test/xmpp. Also, I have run the iDflakies, but it just said the module is wrong. The module should be Junit.

### CODE REVIEW

**Comment by darko-marinov** [comment]
The commit that you listed doesn't seem to be deleting the test. I see the test at https://github.com/jitsi/jicofo/commit/adaedbfd013e14462f53f7ffe616a3a186a26d51#diff-d92c2d5634608d8d59f4bd672ad93765565f096f73cbe851efa659a93a168f93R68 Am I missing something? Please include in the PR description text direct links to the changes that are deleting tests.

**Comment by same8891** [comment]
I am sorry for reporting the  wrong test. The correct test is XmppTest.java. I have changed the file. The direct link is 
```
https://github.com/jitsi/jicofo/commit/adaedbfd013e14462f53f7ffe616a3a186a26d51#diff-47d9982f4296c658697e76570f3a8cdb919cdb110fb89260598ad118a291b74a
```
The commit said move XmppTest to kotlin. I found that it be renamed as [AllocateConferenceTest.kt](https://github.com/jitsi/jicofo/commit/adaedbfd013e14462f53f7ffe616a3a186a26d51#diff-3ac6ff285a2229d207f86c9e0988b9d3c7f1731b3f5db1a3de69e9dd0a95299f) and be deleted in different commit. I will find the commit and change the file.

**Comment by darko-marinov** [comment]
Can you automate some of the checks for `Deleted` and `MovedOrRenamed` so that (1) you don't report wrong info, and (2) we can automatically check for the other reports?

This PR has conflicts that should be resolved before I can merge.

**Comment by same8891** [comment]
I will reopen a pr that has been sync. I think this will solved the conflict. The reopen pr is https://github.com/TestingResearchIllinois/idoft/pull/997. I will try to write the script, but I think it will be really difficult because some rename file in git history may be delete former file and add new file. Also the new file may be different name to the former file. It may have multiple commit that delete the file. I think reading commit message is really important in checking the correctness of deleted and MovedOrRenamed.

**Comment by darko-marinov** [comment]
I don't understand why you closed this PR. PRs can be updated. You need not close a PR to solve a confict.

**Comment by same8891** [comment]
When I sync the project ,the pr just closed.

darko-marinov ***@***.***>於 2023年11月16日 週四，下午7:43寫道：

**Comment by same8891** [comment]
Sorry for that

**Comment by darko-marinov** [comment]
I don't know what exactly you mean by "sync". There's no `git sync` command. Maybe you clicked something on the GitHub UI. You could become more efficient by using command line.

**Pull request closed without merging**
