### PR TITLE
Update pr-data.csv

### PR DESCRIPTION
**Pull request by same8891**
The two tests has been fixed by developer. I have run these two test in the latest commit by nondex. They just both pass. By the way, these two test has been rename to graylog-storage-elasticsearch7/src/test/java/org/graylog/storage/elasticsearch7/views/ElasticsearchBackendUsingCorrectIndicesTest.java in commit ff41b1cd0d8cd0d443e30be81ef5b1913e26b328.

### CODE REVIEW

**Comment by darko-marinov** [comment]
Were the tests fixed before or after rename? Can you find the exact commit that fixed the tests?

**Comment by same8891** [comment]
The rename commit is 54a9ad51afcee7292bef212758bf2466e075c15b and ff41b1cd0d8cd0d443e30be81ef5b1913e26b328. It just renamed twice. The test is fixed before the rename. The fixed commit is d7665100e7c7abc13fd54c8417d394d8bcf7cf52.

**Comment by darko-marinov** [comment]
Thanks for finding the fixed commit. I hope you tested it well. :) Please add it in the last column `Notes` in `pr-data.csv`.

**Comment by same8891** [comment]
I just add it in the note.

**Comment by darko-marinov** [comment]
Did you run on `d7665100e7c7abc13fd54c8417d394d8bcf7cf52^`?

**Comment by same8891** [comment]
Yes and I put the log on my vm.

**Pull request merged**
