### PR TITLE
Opened 14 PRs for test cases in swagger-api/swaggeer-core.

### PR DESCRIPTION
**Pull request by xinying-7**
Opened 24 PRs for fixing swagger-api/swaggeer-core.  The tests are failing NonDex since it's directly comparing JSON Strings which can have different key order, so I converted the actual and expected JSON String into JSON objects and compare with JSONAssert.assertEquals, which ensures correct equality checks regardless of key order.

### CODE REVIEW

**Comment by darko-marinov** [comment]
For the real PR, please describe more as you're running a risk to have https://github.com/swagger-api/swagger-core/pull/4783 rejected. @Ajitesh27 can you please help here?

For this PR on IDoFT, please squash the 10 commits into 1, and I can then accept this PR right away.

**Comment by Ajitesh27** [comment]
@xinying-7 In your real PR [https://github.com/swagger-api/swagger-core/pull/4783](https://github.com/swagger-api/swagger-core/pull/4783 ), please add more details about where the test is failing, why the failure is happening, how to reproduce it, how you fixed it, how to verify that your changes fixed it, etc. 
You can use these PRs as reference:
https://github.com/jdereg/json-io/pull/295
https://github.com/jdereg/json-io/pull/301

**Comment by xinying-7** [comment]
I've squashed the 10 commits into 1, and also changed the real PR description. Thanks for the references!

**Comment by darko-marinov** [comment]
You currently have 2 commits not 1.

**Comment by xinying-7** [comment]
Oh I separated the second one since it is this week's progress. I've squashed them all now.

**Comment by xinying-7** [comment]
Also do I need to squash commits into 1 in real PRs as well?

**Comment by darko-marinov** [comment]
I don't know what policy the real project has, but it may be good to squash for them if no one reviewed your PR there.

**Pull request merged**
