### PR TITLE
Updated status of ConfigurationAsmGeneratorTest to deleted

### PR DESCRIPTION
**Pull request by deekshacheruku**
**Commit**

```
commit b48ddcba7cd2bd3b9a053ae131c25b44a0400e27
Author: Aleksandr Pakhomov <apkhmv@gmail.com>
Date:   Wed Apr 26 20:02:34 2023 +0400

    IGNITE-19152 Use schema information in LocalFileConfigurationStorage (#1988)
    
    ---------
    
    Co-authored-by: Ivan Bessonov <bessonov.ip@gmail.com>

 .../configuration/ConfigurationManager.java        |  46 +-
 .../configuration/ConfigurationRegistry.java       | 189 +---
 .../configuration/ConfigurationTreeGenerator.java  | 283 ++++++
 .../configuration/tree/ConverterToMapVisitor.java  |  42 +-
 .../internal/configuration/tree/NamedListNode.java |   2 +-
 .../configuration/util/ConfigurationFlattener.java |   6 +
 .../configuration/ConfigurationChangerTest.java    |  12 +-
 .../asm/ConfigurationAsmGeneratorTest.java         | 984 --------------------
 .../asm/ConfigurationTreeGeneratorTest.java        | 991 +++++++++++++++++++++
 .../configuration/direct/DirectPropertiesTest.java |  16 +-
 .../configuration/tree/InternalIdTest.java         |  26 +-
 .../configuration/tree/NamedListNodeTest.java      |  12 +-
 .../configuration/TestConfigurationChanger.java    |  28 +-
 .../DistributionZoneManagerTest.java               |  16 +-
 .../ItSslConfigurationValidationTest.java          |   2 +
 .../storage/ItRebalanceDistributedTest.java        |  14 +-
 .../runner/app/ItIgniteNodeRestartTest.java        |  20 +-
 .../org/apache/ignite/internal/app/IgniteImpl.java |  21 +-
 .../storage/LocalFileConfigurationStorage.java     | 180 ++--
 .../DistributedConfigurationCatchUpTest.java       |  11 +-
 .../storage/LocalFileConfigurationStorageTest.java | 460 +++++++++-
 21 files changed, 2012 insertions(+), 1349 deletions(-)
 create mode 100644 modules/configuration/src/main/java/org/apache/ignite/internal/configuration/ConfigurationTreeGenerator.java
 delete mode 100644 modules/configuration/src/test/java/org/apache/ignite/internal/configuration/asm/ConfigurationAsmGeneratorTest.java
```
The commit clearly says ```ConfigurationAsmGeneratorTest``` is deleted.

The commit is found using ```git bisect```. All the logs are in my VM ```deeksha5@fa23-cs527-117``` and in the path ```/home/deeksha5/ignite-3/deleted-test```

This is small PR with respect to https://github.com/TestingResearchIllinois/idoft/pull/978

Let me know if there are any concerns.

### CODE REVIEW

**Comment by zzjas** [comment]
Seems like `ConfigurationAsmGeneratorTest.java` is renamed to `ConfigurationTreeGenerator.java`?

**Comment by darko-marinov** [comment]
Indeed, a rename is effectively deleting old file and adding a new file. You can check with `git show --name-status b48ddcba7cd2bd3b9a053ae131c25b44a0400e27`. Do you see some line(s) starting with `R` (and the similarity score)?

**Comment by deekshacheruku** [comment]
> git show --name-status b48ddcba7cd2bd3b9a053ae131c25b44a0400e27

Yes Professor I see one line ```R096    modules/configuration/src/test/java/org/apache/ignite/internal/configuration/asm/ConfigurationAsmGeneratorTest.java     modules/configuration/src/test/java/org/apache/ignite/internal/configuration/asm/ConfigurationTreeGeneratorTest.java```

**Comment by deekshacheruku** [comment]
** Comment is still being edited.**

It has multiple changes:

```ConfigurationAsmGeneratorTest``` is renamed as ```ConfigurationTreeGeneratorTest```. in the commit https://github.com/apache/ignite-3/commit/b48ddcba7cd2bd3b9a053ae131c25b44a0400e27

**Tests Wise Analysis:**
1. ```testConstructInternalConfig``` has been renamed as ```testConstructExtendedConfig``` in the commit https://github.com/apache/ignite-3/commit/960ce0a72dc8486bca6458f82471dc6d35265482 and has a different method body => Adding Status as ```Deleted```
2.

**Comment by darko-marinov** [comment]
If the tests are in Gradle, why put `MovedOrRenamed` rather than `MovedToGradle`? I agree you can check Gradle flakiness later.

**Comment by deekshacheruku** [comment]
Done @darko-marinov Professor! Let me know if there are any more concerns! Thanks!

**Comment by darko-marinov** [comment]
I don't see why https://github.com/apache/ignite-3/commit/b48ddcba7cd2bd3b9a053ae131c25b44a0400e27 is listed as `MovedToGradle`. That commit doesn't seem to be adding Gradle files.

Also, please separate `Deleted` and `MovedToGradle` if they need to be inspected separately.

**Comment by deekshacheruku** [comment]
Apologies for the confusion professor! The commit https://github.com/apache/ignite-3/commit/b48ddcba7cd2bd3b9a053ae131c25b44a0400e27 is where the file was Renamed. I forgot to add the actual commit for gradle shift which is https://github.com/apache/ignite-3/commit/c91f39cd80dfd143e5ac848486366ad6ed124ce5.

Yes i will separate ```Deleted``` and ```MovedToGradle``` into two PRs.

Thanks @darko-marinov! Let me know if there are any other concerns!

**Comment by darko-marinov** [comment]
Focusing here on only `MovedToGradle` is good. But were those tests still `ID` right before or right after the move? If they got fixed before that, then we should find where they were fixed not when they were moved.

**Comment by deekshacheruku** [comment]
> Focusing here on only `MovedToGradle` is good. But were those tests still `ID` right before or right after the move? If they got fixed before that, then we should find where they were fixed not when they were moved.

I tired build the project before and after the move, but couldnt it. It is same as the explanation in https://github.com/TestingResearchIllinois/idoft/pull/1027 PR. I will raise another PR if I find the tests Flaky in the current commit (after gradle shift). I didnt want to add here in this commit. @darko-marinov

**Comment by deekshacheruku** [comment]
@darko-marinov This is similar to https://github.com/TestingResearchIllinois/idoft/pull/1064. The testclass has been renamed in the commit ```b48ddcba7cd2bd3b9a053ae131c25b44a0400e27``` then the test methods have been moved to gradle in the commit ```c91f39cd80dfd143e5ac848486366ad6ed124ce5```. In another PR I will raise to add the tests in gr-data.csv if they are found flaky in Gradle. Let me know if any other evidence is needed. Thanks in advance!

**Pull request merged**
