### PR TITLE
PR status changed

### PR DESCRIPTION
**Pull request by Ethan-Chin**
PR status changed (`DeveloperWontFix`) for https://github.com/apache/incubator-kie-drools/pull/6119.

The developer claimed that he had never encountered these test failures. The developer refused to acknowledge the validity of NonDex and denied that these were flaky tests.

### CODE REVIEW

**Comment by darko-marinov** [comment]
Not having encountered the failures is not surprising. The rest of your description sounds rather harsh. Can you confirm if your tests fails in the `ONE` mode? (Please collect some log file and let us know where to find it.)

**Comment by Ethan-Chin** [comment]
> Not having encountered the failures is not surprising. The rest of your description sounds rather harsh. Can you confirm if your tests fails in the `ONE` mode? (Please collect some log file and let us know where to find it.)

Thanks. I have run these three tests in ONE mode, the fails still stand. You can find logs in:
`/home/yucong3/tmp/incubator-kie-drools_AccumulateTest_ONE_nondex.log`
`/home/yucong3/tmp/incubator-kie-drools_GroupByTest_ONE_nondex.log`
`/home/yucong3/tmp/incubator-kie-drools_NamedConsequencesTest_ONE_nondex.log`

**Comment by darko-marinov** [comment]
Thanks for checking the `ONE` mode for your case. I'll leave this PR pending until @everbrightw resolves the issue with `HashMap::spliterator()`. You two are welcome to collaborate if you want.

**Comment by darko-marinov** [comment]
Please move the URL from the second last column to the last column and remove the text you had in the last column. The status should remain `DeveloperWontFix`.

**Comment by Ethan-Chin** [comment]
> Please move the URL from the second last column to the last column and remove the text you had in the last column. The status should remain `DeveloperWontFix`.

Done!

**Pull request merged**
