### PR TITLE
Opened PRs for 14 fixed tests

### PR DESCRIPTION
**Pull request by Doom-Prophet**
VM: 093

Logs: home/zicheng5/new-tests

All logs are in corresponding repo-named folder with extension ".nondex_log"

The one newly found and fixed test: "testInfraNamedWindowViews" is recorded

### CODE REVIEW

**Comment by darko-marinov** [comment]
Please squash the commits. If you have more to add, consider whether to open a new PR or keep updating this one. Smaller PRs are easier to review and accept.

**Comment by Doom-Prophet** [comment]
> Please squash the commits. If you have more to add, consider whether to open a new PR or keep updating this one. Smaller PRs are easier to review and accept.

I will be adding some more these two days, do I need to wait till all of them added and then squash them all, or just squash these five first?

**Comment by darko-marinov** [comment]
Squash these now. You can add new ones as new PRs not by updating this PR.

**Comment by Doom-Prophet** [comment]
Just squashed.

**Comment by darko-marinov** [comment]
I can accept the changes on `esper`, but for `junit4`, please put `Opened` unless the developers add some fix, in which case add a link to their commit in the last column `Notes`.

**Comment by Doom-Prophet** [comment]
Commit made, do I need to squash this one as well?

**Comment by darko-marinov** [comment]
Please keep in this PR only `Opened` (and squash all commits into one). The other case(s) -- whether `MovedOrRenamed, `DeveloperFixed`, or anything else -- should be in another PR.

**Comment by Doom-Prophet** [comment]
I've made this PR only `Opened `and squashed them together as you wish, shortly afterwards I will set up a new branch and open another PR for `MovedOrRenamed `and `DeveloperFixed`

**Comment by darko-marinov** [comment]
Accepting this so you get some "points" for now. You may want to clean https://github.com/espertechinc/esper/pull/279/files as it's likely to be rejected.

**Comment by Doom-Prophet** [comment]
> Accepting this so you get some "points" for now. You may want to clean https://github.com/espertechinc/esper/pull/279/files as it's likely to be rejected.

Do you mean the  "clean" by squashing all commits there into one as well? Or are you expecting more beyond that?

**Comment by darko-marinov** [comment]
Start by squashing but you should really (1) delete old code rather than commenting it out and (2) extract common expressions as I'm not even sure if all the fixes work with some expressions repeated (where NonDex could shuffle the same expressions differently in two evaluations).

**Comment by Doom-Prophet** [comment]
When I am creating second PR from another branch(while you were accepting my first one), it seems that Git mistakenly take all modifications from first PR into it, which results in “ Can’t automatically merge. Don’t worry, you can still create the pull request.” How should I do in this situation?

Zicheng

发件人: darko-marinov ***@***.***>
发送时间: 2023年12月10日 22:56
收件人: TestingResearchIllinois/idoft ***@***.***>
抄送: Ma, Zicheng ***@***.***>; Author ***@***.***>
主题: Re: [TestingResearchIllinois/idoft] Opened PRs for 14 fixed tests (PR #1213)


Accepting this so you get some "points" for now. You may want to clean https://github.com/espertechinc/esper/pull/279/files<https://urldefense.com/v3/__https:/github.com/espertechinc/esper/pull/279/files__;!!DZ3fjg!80vYC22qRtXLXTt-pyWFDKKvocAScW88R1ec3J3oObC0hoTmmhIyX5-RjSb67h-Vf4r6Z8ejQaRbSlnhFpRriHxoxxrQ$> as it's likely to be rejected.

**Pull request merged**
