### PR TITLE
Added new java flaky test to pr-data.csv (apache/rocketmq)

### PR DESCRIPTION
**Pull request by rahulsuresh-git**
Found a new flaky test using Nondex 2.1.1 in the Apache RocketMQ repository.
Repo link: https://github.com/apache/rocketmq

Flaky test: `org.apache.rocketmq.common.UtilAllTest.testCalculateFileSizeInPath`
Steps to reproduce:
1. Install maven dependencies 
2. Added nondex plugin 2.1.1 to pom.xml (follow instructions at https://github.com/TestingResearchIllinois/NonDex) 
2. Run `mvn -pl common test edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.apache.rocketmq.common.UtilAllTest#testCalculateFileSizeInPath` in the root directory.
3. You should see the test FAILURE.

Commands I've tried:
1. `mvn nondex:debug` runs endlessly failing for every possible seed. When I executed it, it kept running for over 1 hour.
2. ` mvn nondex:nondex -DnondexRuns=1 -Dtest=org.apache.rocketmq.common.UtilAllTest#testCalculateFileSizeInPath` has a FAILURE with the following output:
```
[INFO] --- nondex:2.1.1:nondex (default-cli) @ rocketmq-all ---
INFO: The original argline is: 
INFO: Creating new argline for Surefire
CONFIG: nondexFilter=.*
nondexMode=FULL
nondexSeed=933178
nondexStart=0
nondexEnd=9223372036854775807
nondexPrintstack=false
nondexDir=/Users/rahul/Desktop/cs527/rocketmq/.nondex
nondexJarDir=.nondex
nondexExecid=clean_0mYyxydTbR1pWBm4YXtJmAdgv8U8QXMo2oJbLH2Hrs0=
nondexLogging=CONFIG
test=
[INFO] No tests to run.
INFO: Surefire failed when running tests for clean_0mYyxydTbR1pWBm4YXtJmAdgv8U8QXMo2oJbLH2Hrs0=
INFO: Adding excluded groups to newly created one
INFO: Creating new argline for Surefire
CONFIG: nondexFilter=.*
nondexMode=FULL
nondexSeed=933178
nondexStart=0
nondexEnd=9223372036854775807
nondexPrintstack=false
nondexDir=/Users/rahul/Desktop/cs527/rocketmq/.nondex
nondexJarDir=/Users/rahul/Desktop/cs527/rocketmq/.nondex
nondexExecid=ooM3IlTiHIcb5PWo3IGSTYiCIny3kOLWinZWEqH1sg=
nondexLogging=CONFIG
test=
[INFO] No tests to run.
INFO: Surefire failed when running tests for ooM3IlTiHIcb5PWo3IGSTYiCIny3kOLWinZWEqH1sg=
[INFO] NonDex SUMMARY:
[INFO] *********
[INFO] mvn nondex:nondex  -DnondexFilter='.*' -DnondexMode=FULL -DnondexSeed=933178 -DnondexStart=0 -DnondexEnd=9223372036854775807 -DnondexPrintstack=false -DnondexDir="/Users/rahul/Desktop/cs527/rocketmq/.nondex" -DnondexJarDir="/Users/rahul/Desktop/cs527/rocketmq/.nondex" -DnondexExecid=ooM3IlTiHIcb5PWo3IGSTYiCIny3kOLWinZWEqH1sg= -DnondexLogging=CONFIG
[INFO] No Test Failed with this configuration.
[INFO] *********
[INFO] All tests pass without NonDex shuffling
[INFO] ####################
[INFO] Across all seeds:
[INFO] Test results can be found at: 
[INFO] file:///Users/rahul/Desktop/cs527/rocketmq/.nondex/ooM3IlTiHIcb5PWo3IGSTYiCIny3kOLWinZWEqH1sg=/test_results.html
[INFO] [NonDex] The id of this run is: ooM3IlTiHIcb5PWo3IGSTYiCIny3kOLWinZWEqH1sg=
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Apache RocketMQ 5.1.4-SNAPSHOT 5.1.4-SNAPSHOT:
[INFO] 
[INFO] Apache RocketMQ 5.1.4-SNAPSHOT ..................... FAILURE [  1.706 s]
[INFO] rocketmq-common 5.1.4-SNAPSHOT ..................... SKIPPED
[INFO] rocketmq-remoting 5.1.4-SNAPSHOT ................... SKIPPED
```
3. `mvn nondex:debug` command after the above command keeps running endlessly with the following output:
```
INFO: Surefire failed when running tests for MXmJnCbs7c1pQexpEhzYaUbibOMRWmVSCSHaW08MjE=
INFO: Adding excluded groups to newly created one
INFO: Creating new argline for Surefire
CONFIG: nondexFilter=.*
nondexMode=FULL
nondexSeed=974622
nondexStart=11
nondexEnd=21
nondexPrintstack=false
nondexDir=/Users/rahul/Desktop/cs527/rocketmq/common/.nondex
nondexJarDir=/Users/rahul/Desktop/cs527/rocketmq/common/.nondex
nondexExecid=UKDuCU7RUp3EQhaTj0CvIEQpd0TC+WPW5f1ciS5YVo=
nondexLogging=CONFIG
test=org.apache.rocketmq.common.UtilAllTest#testCalculateFileSizeInPath

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.apache.rocketmq.common.UtilAllTest
16:22:58,144 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.classic.LoggerContext[default] - This is logback-classic version 1.3.5-rocketmq
16:22:58,156 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.classic.LoggerContext[default] - Found resource [rmq.logback-test.xml] at [file:/Users/rahul/Desktop/cs527/rocketmq/common/target/test-classes/rmq.logback-test.xml]
16:22:58,222 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [CONSOLE]
16:22:58,222 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [org.apache.rocketmq.logging.ch.qos.logback.core.ConsoleAppender]
16:22:58,242 |-WARN in org.apache.rocketmq.logging.ch.qos.logback.core.ConsoleAppender[CONSOLE] - This appender no longer admits a layout as a sub-component, set an encoder instead.
16:22:58,242 |-WARN in org.apache.rocketmq.logging.ch.qos.logback.core.ConsoleAppender[CONSOLE] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
16:22:58,242 |-WARN in org.apache.rocketmq.logging.ch.qos.logback.core.ConsoleAppender[CONSOLE] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
16:22:58,242 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.apache.rocketmq] to ERROR
16:22:58,242 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [org.apache.rocketmq] to false
16:22:58,242 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [CONSOLE] to Logger[org.apache.rocketmq]
16:22:58,242 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to ERROR
16:22:58,242 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [CONSOLE] to Logger[ROOT]
16:22:58,242 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.core.model.processor.DefaultProcessor@6e2829c7 - End of configuration.
16:22:58,242 |-INFO in org.apache.rocketmq.common.logging.JoranConfiguratorExt@3feb2dda - Registering current configuration as safe fallback point

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.136 sec <<< FAILURE! - in org.apache.rocketmq.common.UtilAllTest
testCalculateFileSizeInPath(org.apache.rocketmq.common.UtilAllTest)  Time elapsed: 0.136 sec  <<< FAILURE!
java.lang.AssertionError: expected:<0> but was:<5252>
        at org.apache.rocketmq.common.UtilAllTest.testCalculateFileSizeInPath(UtilAllTest.java:242)


Results :

Failed tests: 
  UtilAllTest.testCalculateFileSizeInPath:242 expected:<0> but was:<5252>

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0

INFO: Surefire failed when running tests for UKDuCU7RUp3EQhaTj0CvIEQpd0TC+WPW5f1ciS5YVo=
INFO: Debugging binary for org.apache.rocketmq.common.UtilAllTest#testCalculateFileSizeInPath 22 : 42
INFO: Adding excluded groups to newly created one
INFO: Creating new argline for Surefire
CONFIG: nondexFilter=.*
nondexMode=FULL
nondexSeed=974622
nondexStart=22
nondexEnd=32
nondexPrintstack=false
nondexDir=/Users/rahul/Desktop/cs527/rocketmq/common/.nondex
nondexJarDir=/Users/rahul/Desktop/cs527/rocketmq/common/.nondex
nondexExecid=bK99Pq1cHVs5wEnEkFvcw84mdpXVhSpizCUsVhaPjc=
nondexLogging=CONFIG
test=org.apache.rocketmq.common.UtilAllTest#testCalculateFileSizeInPath

-------------------------------------------------------
 T E S T S
-------------------------------------------------------
Running org.apache.rocketmq.common.UtilAllTest
16:22:58,879 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.classic.LoggerContext[default] - This is logback-classic version 1.3.5-rocketmq
16:22:58,890 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.classic.LoggerContext[default] - Found resource [rmq.logback-test.xml] at [file:/Users/rahul/Desktop/cs527/rocketmq/common/target/test-classes/rmq.logback-test.xml]
16:22:58,958 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.core.model.processor.AppenderModelHandler - Processing appender named [CONSOLE]
16:22:58,958 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.core.model.processor.AppenderModelHandler - About to instantiate appender of type [org.apache.rocketmq.logging.ch.qos.logback.core.ConsoleAppender]
16:22:58,980 |-WARN in org.apache.rocketmq.logging.ch.qos.logback.core.ConsoleAppender[CONSOLE] - This appender no longer admits a layout as a sub-component, set an encoder instead.
16:22:58,980 |-WARN in org.apache.rocketmq.logging.ch.qos.logback.core.ConsoleAppender[CONSOLE] - To ensure compatibility, wrapping your layout in LayoutWrappingEncoder.
16:22:58,980 |-WARN in org.apache.rocketmq.logging.ch.qos.logback.core.ConsoleAppender[CONSOLE] - See also http://logback.qos.ch/codes.html#layoutInsteadOfEncoder for details
16:22:58,980 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting level of logger [org.apache.rocketmq] to ERROR
16:22:58,980 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.classic.model.processor.LoggerModelHandler - Setting additivity of logger [org.apache.rocketmq] to false
16:22:58,980 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [CONSOLE] to Logger[org.apache.rocketmq]
16:22:58,980 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.classic.model.processor.RootLoggerModelHandler - Setting level of ROOT logger to ERROR
16:22:58,980 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.core.model.processor.AppenderRefModelHandler - Attaching appender named [CONSOLE] to Logger[ROOT]
16:22:58,980 |-INFO in org.apache.rocketmq.logging.ch.qos.logback.core.model.processor.DefaultProcessor@6e2829c7 - End of configuration.
16:22:58,980 |-INFO in org.apache.rocketmq.common.logging.JoranConfiguratorExt@3feb2dda - Registering current configuration as safe fallback point

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.139 sec <<< FAILURE! - in org.apache.rocketmq.common.UtilAllTest
testCalculateFileSizeInPath(org.apache.rocketmq.common.UtilAllTest)  Time elapsed: 0.139 sec  <<< FAILURE!
java.lang.AssertionError: expected:<0> but was:<5252>
        at org.apache.rocketmq.common.UtilAllTest.testCalculateFileSizeInPath(UtilAllTest.java:242)


Results :

Failed tests: 
  UtilAllTest.testCalculateFileSizeInPath:242 expected:<0> but was:<5252>

Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
```

### CODE REVIEW

**Comment by darko-marinov** [comment]
Do you really want both `mvn test` and `mvn nondex:nondex` in the same command?

For what seed(s) does the test fail? Can you run `mvn nondex:debug` for the seed(s)?

**Comment by rahulsuresh-git** [comment]
@darko-marinov Seems to fail for all seeds.
The command runs endlessly.

**Comment by darko-marinov** [comment]
Can you edit the PR text to say which exact commands you ran?

Can you run `mvn nondex:debug` for only one seed? You'd need to `mv .nondex .nondex-old`, then `mvn nondex:nondex -DnondexRuns=1 ...` then `mvn nondex:debug`.

**Comment by rahulsuresh-git** [comment]
Sure @darko-marinov! I've updated the PR with the details.
Let me know if you need more information, I'd be happy to share.

**Comment by darko-marinov** [comment]
> mvn nondex:debug runs endlessly failing for every possible seed.

What are the exact seeds that you tried? How did you even get it to run with different seeds?

**Comment by rahulsuresh-git** [comment]
> > mvn nondex:debug runs endlessly failing for every possible seed.
> 
> What are the exact seeds that you tried? How did you even get it to run with different seeds?

I'm sorry I'm new to nondex so I didn't notice the seeds it was running on during the debug mode. When I ran the `mvn nondex:debug` command, the log output on terminal just keeps printing endlessly. I checked the seed for every log, and it seems to be the same (nondexSeed=933178). Let me know if that helps.

**Comment by darko-marinov** [comment]
I know that the (first) seed is the same.

Can you try with another seed? It may still get into a long loop (if it can't find one shuffle location that determines the test outcome), or it may produce an output.

Can you leave `mvn nondex:debug` to run overnight (or until EngrIT powers it down), even if you disconnect from the VM?

**Comment by rahulsuresh-git** [comment]
Okay, sure. Thank you @darko-marinov. I will try running the command overnight.

One follow up, you asked me to try with another seed. Can you tell me how do I decide what seed to use? Is it just any random 6-digit number?

**Comment by darko-marinov** [comment]
You can use any integer (or maybe long?) for the seed such that the test fails with shuffling (and passes without shuffling).

**Comment by darko-marinov** [comment]
Are you planning to finish this PR or to abandon it?

**Comment by rahulsuresh-git** [comment]
> Are you planning to finish this PR or to abandon it?

Apologies, I didn't get time to run it on the VM since my VM was occupied as I did mp2. I will run the command on the VM overnight and let you know my findings in some days.

**Comment by rahulsuresh-git** [comment]
@darko-marinov 
I tried running for more seeds like 100000, 100001, 999999, and 100009 and it fails everytime.

The command:
`mvn edu.illinois:nondex-maven-plugin:2.1.1:nondex -Dtest=org.apache.rocketmq.common.UtilAllTest#testCalculateFileSizeInPath -DnondexSeed=1000000 -DnondexRuns=1` fails.

Ran `mv .nondex .nondex-old` between runs.

`mvn nondex:debug` passes.

**Pull request merged**
