### PR TITLE
Replaced opened PR's with new PR

### PR DESCRIPTION
**Pull request by kavvya97**
Previously we had created multiple PR's. However, Since the developer suggested that we open a single PR. We have opened a single PR to developer repo.

**New Combined PR**
https://github.com/apache/druid/pull/15418

**Old PR**
https://github.com/apache/druid/pull/15341
https://github.com/apache/druid/pull/15342

### CODE REVIEW

**Comment by darko-marinov** [comment]
Let's wait for @zzjas to confirm whether to have one PR or split.

**Comment by zzjas** [comment]
Ok to merge

**Comment by zzjas** [comment]
According to https://github.com/TestingResearchIllinois/idoft/pull/1211, should this PR change the PR Link for two more tests?

**Comment by kavvya97** [comment]
we were assigned only 11 tests. The other fixes are addressed as part of https://github.com/apache/druid/pull/15105

**Comment by zzjas** [comment]
Got it. I asked the other student to modify these two lines.

This PR is ok to merge @darko-marinov

**Pull request merged**
