### PR TITLE
Two tests in apache/flink have had their modules renamed

### PR DESCRIPTION
**Pull request by krishnanand5**
The two tests in question are :

- `org.apache.flink.connectors.hive.HiveTableSinkTest.testWriteComplexType`.
- `org.apache.flink.connectors.hive.TableEnvHiveConnectorTest.testUDTF`.

As per the latest version of the apache/flink repository, both modules have been renamed to `HiveRunnerITCase` and `TableEnvHiveConnectorITCase` respectively.

The commit where the renaming of modules has occurred seems to be `850e3a520e55549a140138c81e433c44e641bdbc`.

Link to Commit - https://github.com/apache/flink/pull/12333/commits/850e3a520e55549a140138c81e433c44e641bdbc

### CODE REVIEW

**Comment by darko-marinov** [comment]
How does this relate to #853? @kevin952 if I don't get some clarification about these PRs soon, I'll just accept this one as it's rather clean, and then you can see how to adjust your PR.

**Comment by darko-marinov** [comment]
What is the new location for these two tests?

**Comment by kevin952** [comment]
> How does this relate to #853? @kevin952 if I don't get some clarification about these PRs soon, I'll just accept this one as it's rather clean, and then you can see how to adjust your PR.

these tests are different and does not relate to mine! thanks!

**Comment by darko-marinov** [comment]
@krishnanand5 what is the new location for these two tests? Besides modifying the two existing lines, please add two new lines with the new location.

**Comment by krishnanand5** [comment]
Greetings Professor,

The new location of the two tests is as follows:

- `org.apache.flink.connectors.hive.HiveRunnerITCase.testWriteComplexType`
- `org.apache.flink.connectors.hive.TableEnvHiveConnectorITCase.testUDTF`

You had asked me to add these tests after I had opened a PR for both. As per Apache/flink's repository guidelines, a JIRA issue has to be raised in order to address detected issues.

For both of these tests, I raised individual JIRA issues and they are the following:
- [FLINK-33444](https://issues.apache.org/jira/browse/FLINK-33444)
- [FLINK-33443](https://issues.apache.org/jira/browse/FLINK-33443)

As of today, FLINK-33443 has been closed by the concerned developer for the reasons that the flakiness was not observed during their CI/CD process and hence the issue was trivial.

Can I mark the concerned test as `DeveloperWon'tFix`?

A follow-up question would be the flaky test raised in FLINK-33444 belongs to the same module. Will that test also be considered as `DeveloperWon'tFix`?

**Comment by darko-marinov** [comment]
For `MovedOrRenamed`, please add in `Notes` (the last column) a link to the commit that moved these tests (separate the new link from the existing link with `;`). Then check if the tests were `ID` right after being moved and, if so, add two new lines with the new location. We'll see later whether to mark those two new lines as `DeveloperWontFix` or something else.

**Comment by krishnanand5** [comment]
Greetings Professor,

As suggested, I have added the commit link in the last column for the two tests marked as `MovedOrRenamed` and added the location of the new tests.

For further documentation, I have attached the JIRA links created for the new tests along with one another test so as to track developments related to inclusion of NonDex in FLINK's CI/CD pipeline.

**Comment by darko-marinov** [comment]
Please stop spamming developers. Mark https://issues.apache.org/jira/browse/FLINK-33499 as `Rejected`. You can mark https://issues.apache.org/jira/browse/FLINK-33443 as `DeveloperWontFix`. Do you know what the root cause is (map iteration or `getDeclaredFields`)? Had you explained the root cause rather than just mentioned the tool, you may have gotten a more positive response.

**Comment by krishnanand5** [comment]
Sure, I will make the necessary changes.
Can https://issues.apache.org/jira/browse/FLINK-33444 also be marked as `DeveloperWontFix` ?

**Comment by darko-marinov** [comment]
Okay, mark the first two as `DeveloperWontFix`, although there was no need to open both if the concerns could have been described in one. But do mark the new one as `Rejected`, because the developer had already asked to stop. We're also asking other students to not report to this repo.

**Comment by darko-marinov** [comment]
The checker failed.

**Comment by Alex-Lian** [comment]
@krishnanand5 The root cause is that you did not provide the PR link for the "Rejected PR" in line 1379, resulting in the format-checker indicating "Invalid PR Link: '', Reason: Unspecified."

Interestingly, the Github Actions reported an incorrect line number. If you're interested in delving into this to rectify a possible issue in the format_checker, I'm willing to offer extra credit for it.

**Comment by krishnanand5** [comment]
Thank you for the clarification. I will try to rectify the format_checker issue. 
As a follow up to the rejected PR, I was asked by the developer not to open a PR as he had rejected the issue straightaway. How should I go about bypassing the PR check ?

**Comment by darko-marinov** [comment]
I'll accept this as is (and hopefully won't break too much :). You can still debug `format_checker` later for extra credit.

**Pull request merged**
