### PR TITLE
20 DeveloperFixed for Java-WebSocket

### PR DESCRIPTION
**Pull request by Derrick2000**
20 test cases were deleted in Issue256Test

### CODE REVIEW

**Comment by darko-marinov** [comment]
This listed commit did not delete the tests but renamed them to run with parameters. Did you try to run some tool (even simple `mvn test` but better iDFlakies or NonDex on the entire module) for that commit to see what it lists as executed tests? In particular, it'd be good to find out if some tests are still flaky.

**Comment by darko-marinov** [comment]
Do you have log files to show that the tests fails with NonDex right before `9fad5bce9e34382ac2a9e0c5c470bf245dc77ba7` but pass in `9fad5bce9e34382ac2a9e0c5c470bf245dc77ba7`?

**Comment by Derrick2000** [comment]
> Do you have log files to show that the tests fails with NonDex right before `9fad5bce9e34382ac2a9e0c5c470bf245dc77ba7` but pass in `9fad5bce9e34382ac2a9e0c5c470bf245dc77ba7`?

Sorry, this commit `9fad5bce9e34382ac2a9e0c5c470bf245dc77ba7` is actually the last commit that the test fail with NonDex. The commit right after: `8834112c0a5c9e25ae2814bf7bd592f526484f94` is test success. 

VM: 056
Log file: /home/mingyu7/Java-WebSocket/nondex-1731991762.log

**Comment by darko-marinov** [comment]
Looking at the code changes in `8834112c0a5c9e25ae2814bf7bd592f526484f94`, they could have indeed fixed some `NOD` tests. Can you run these tests with just Maven (Surefire), without NonDex, e.g., `for i in {1..10}; do mvn test -Dtest=...; done` maybe run some entire test classes (with `-Dtest=...`) or the entire module (without `-Dtest=...`).

**Comment by Derrick2000** [comment]
> Looking at the code changes in `8834112c0a5c9e25ae2814bf7bd592f526484f94`, they could have indeed fixed some `NOD` tests. Can you run these tests with just Maven (Surefire), without NonDex, e.g., `for i in {1..10}; do mvn test -Dtest=...; done` maybe run some entire test classes (with `-Dtest=...`) or the entire module (without `-Dtest=...`).

test success on the entire test class:
/home/mingyu7/Java-WebSocket/mvn-test-1731993577.log

**Comment by darko-marinov** [comment]
Do you also get failures with just `mvn test`? You reported using NonDex before, but NonDex should not be necessary (or even helpful) to find `OD` or `NOD` tests.

**Comment by Derrick2000** [comment]
> Do you also get failures with just `mvn test`? You reported using NonDex before, but NonDex should not be necessary (or even helpful) to find `OD` or `NOD` tests.

I get build success with `mvn test` for both commits `9fad5bce9e34382ac2a9e0c5c470bf245dc77ba7` and `8834112c0a5c9e25ae2814bf7bd592f526484f94`, but Nondex only succeeds for the later.

**Comment by darko-marinov** [comment]
How many times did you run `mvn test`? Were then those tests `ID` and not `NOD`?

**Comment by Derrick2000** [comment]
Ran `mvn test`
- 10 times on `9fad5bce9e34382ac2a9e0c5c470bf245dc77ba7`, get about half failture
Log: /home/mingyu7/Java-WebSocket/mvn-test-1732038631.log

- 10 times on `8834112c0a5c9e25ae2814bf7bd592f526484f94`, all success
- Log: /home/mingyu7/Java-WebSocket/mvn-test-1732038875.log

**Comment by Derrick2000** [comment]
Given that: on `9fad5bce9e34382ac2a9e0c5c470bf245dc77ba7`

- The test fails intermittently even when run with the same code and using `mvn test`.
- The failure is due to a `TestTimedOutException`, indicating that the test sometimes exceeds the time limit of 5000ms.
- There are exceptions like `SocketException`: Socket is closed and AssumptionViolatedException occurring during the test execution.

for both `runReconnectSocketClose` and `runReconnectCloseBlocking` methods, I believe they should be ID flaky tests.

**Comment by Derrick2000** [comment]
I think `8834112c0a5c9e25ae2814bf7bd592f526484f94` fixed the ID issue, but the NOD issue remains as it fails the iDFlakies check

**Comment by darko-marinov** [comment]
If you believe that the test can be both `ID` and `NOD` -- which is possible (even if unusual)! -- can you repeatedly get it to pass or fail for some NonDex random seeds? If so, you'd change the category to add `;ID` and list in `Notes` (the last column) that the commit `8834112c0a5c9e25ae2814bf7bd592f526484f94` fixed the ID issue. But I'm still not convinced if the test was ever `ID` or simply `NOD` but passes and fails in various runs (with or without shuffling).

**Comment by Derrick2000** [comment]
Opened a PR to address NOD flakiness

**Comment by Derrick2000** [comment]
I've included the link to the new method and the PR in **Note**. Please let me know if any changes are needed.

**Comment by darko-marinov** [comment]
This change now looks good, but squash the two commits. Are you planning to open a new IDoFT PR for the opened real PR?

**Comment by Derrick2000** [comment]
> This change now looks good, but squash the two commits. Are you planning to open a new IDoFT PR for the opened real PR?

Squashed. And yes, I will open a new IDoFT PR for that :)

**Pull request merged**
