### PR TITLE
Hannah-final-commit with Apache Repos 👩🏻‍🔧

### PR DESCRIPTION
**Pull request by MyEnthusiastic**
Update the PR for all the Apache detect and Fix work

### CODE REVIEW

**Comment by darko-marinov** [comment]
The checker failed. I asked @zzjas to take a look.

**Comment by MyEnthusiastic** [comment]
Fixed

**Comment by darko-marinov** [comment]
The checker passes now, but @zzjas need to tell me what to do with multiple PRs about `flink`.

**Comment by zzjas** [comment]
No conflict with others so OK to merge as long as the `Notes` looks ok to you @darko-marinov

**Comment by darko-marinov** [comment]
@zzjas can you please inspect this in detail?

**Comment by zzjas** [comment]
Please split the PR into smaller ones. Small chunks are easier to check and discuss.

Please have one for all `Accepted`. They are easiest to merge.

Please then have one for all flink tests. They were found by Yang so also easy to check.

Have one for all `Opened` as well.

Then for newly detected tests with empty status, create one PR for each repo/module.

What does TLE mean in "TLE, not sure how to fix"? If you want to provide notes, please use the `Notes` column but not the `PR Link` column. Also, you don't need to say "not sure how to fix" for all tests. Only include notes if you find special things that need to be taken care of. Please take a look at other notes already present in the file.

**Comment by MyEnthusiastic** [comment]
Okay! I'll break it down 🫡

**Comment by darko-marinov** [comment]
Should we close this PR? For new tests, you need to update `forked_projects.json`. You're welcome to change the checker to print a better error message if it can't find a project.

**Pull request closed without merging**
