### PR TITLE
Update opened status and add NOD test

### PR DESCRIPTION
**Pull request by rRajivramachandran**
### Opened 
PR opened for `com.alibaba.fastjson.serializer.TestParse.testParse`: https://github.com/alibaba/fastjson/pull/4458
Approved tentative PR: https://github.com/rRajivramachandran/fastjson/pull/1

### New test
New test found non deterministic:
`com.alibaba.json.bvt.issue_2700.Issue2784#test_for_issue`

When the test is run by itself it fails. 
```
[INFO] Running com.alibaba.json.bvt.issue_2700.Issue2784
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.889 s <<< FAILURE! - in com.alibaba.json.bvt.issue_2700.Issue2784
[ERROR] com.alibaba.json.bvt.issue_2700.Issue2784.test_for_issue  Time elapsed: 0.531 s  <<< FAILURE!
junit.framework.AssertionFailedError: expected:<2023-11-11T11:38:15.749028> but was:<2023-11-11T11:38:15.749>
at com.alibaba.json.bvt.issue_2700.Issue2784.test_for_issue(Issue2784.java:21)
```

The test depends on `java.time.LocalDateTime`. The test will only pass when the system time taken is an exact millisecond value(i.e microsecond and nanoseconds are zero). The pass scenario has been verified using the following [patch](https://github.com/alibaba/fastjson/commit/6146f53ddb219094e097017391c21c1b6b84b1ee#diff-589f95c6f4c1a84052cc74f5c9e3223eb19ecf57387b23a6b347021044a55d58).

Since the same test passes and fails when run at different times it is non deterministic. It is not dependent on any other test and is NOD by itself. 

VM id: rajivr3@fa23-cs527-104.cs.illinois.edu
Log passing: /home/rajivr3/fastjson2/fastjson/pass_with_zerobeyondmillis.log
Log failing: /home/rajivr3/fastjson2/fastjson/fail_without_zerobeyondmillis.log

Tentative PR(approved): https://github.com/rRajivramachandran/fastjson/pull/2
Real PR: https://github.com/alibaba/fastjson/pull/4460

### CODE REVIEW

**Comment by darko-marinov** [comment]
Why create `ParserConfig` in `@Before` rather than just one line before it's needed?

Does the newly added test pass when run with the others, or does it make the test suite fail almost always?

**Comment by rRajivramachandran** [comment]
The newly added test fails when run with the entire module and run alone. I shall make change to create the `ParseConfig` in the test itself.

**Comment by rRajivramachandran** [comment]
Updated : https://github.com/alibaba/fastjson/pull/4458/files

**Comment by rRajivramachandran** [comment]
The last commit on this repo from 6 months back fails the CI: https://github.com/alibaba/fastjson/actions/runs/4955812527 . Unfortunately the logs are archived. In the past there have been many failures: https://github.com/alibaba/fastjson/actions

**Pull request merged**
