### PR TITLE
Update pr-data.csv

### PR DESCRIPTION
**Pull request by same8891**
I found that these four tests has been fixed. The following is my finding. I found that these tests has been renamed 7 times.
The four tests were still under disable or enable but in different prefix path.
```
In this commit: https://github.com/apache/shardingsphere-elasticjob/commit/b2a6a70b8870df681de2c7fd0809da7dee96afa7,  the tests have been moved to elasticjob-engine/elasticjob-engine-core/src/test/java/org/apache/shardingsphere/elasticjob/engine/integrate/
In this commit: https://github.com/apache/shardingsphere-elasticjob/commit/aff58de04fce648ad8db80ba03163d1b414fc6b8,  the tests have been moved to engine/core/src/test/java/org/apache/shardingsphere/elasticjob/engine/integrate/
In this commit: https://github.com/apache/shardingsphere-elasticjob/commit/7d472ed0e9e78cd03a3c56d02d59ae0498f41159,  the tests have been moved to core/src/test/java/org/apache/shardingsphere/elasticjob/engine/integrate/
In this commit: https://github.com/apache/shardingsphere-elasticjob/commit/442bf91d0b6ac5c4413435db78da41b279f17823,  the tests have been moved to kernel/src/test/java/org/apache/shardingsphere/elasticjob/engine/integrate/
In this commit: https://github.com/apache/shardingsphere-elasticjob/commit/cbb59f5d475dbf24c11f7c6a7dfc04b9b883c868, the tests have been moved to kernel/src/test/java/org/apache/shardingsphere/elasticjob/kernel/integrate/
In this commit: https://github.com/apache/shardingsphere-elasticjob/commit/cb2c0dbed620660722fb7303173aa84aedc19854, the tests have been moved to  test/e2e/src/test/java/org/apache/shardingsphere/elasticjob/test/e2e/ and renamed to e2eTest.
In this commit: https://github.com/apache/shardingsphere-elasticjob/commit/621cf953cf0382a652145eaf6d72df767f8766c4, the tests have been moved to test/e2e/src/test/java/org/apache/shardingsphere/elasticjob/test/e2e/raw/.
```
Also when I ran the latest version with iDFlakies, I found these four tests has been fixed. So, I ran all of the file history commit and found the tests were fixed before moved to elasticjob-engine/elasticjob-engine-core/src/test/java/org/apache/shardingsphere/elasticjob/engine/integrate/. To find which commit fixed the tests, I ran commits one by one and found that https://github.com/apache/shardingsphere-elasticjob/commit/054571c6d7caca455418e0f83056a0182315bd75 fixed the tests. After https://github.com/apache/shardingsphere-elasticjob/commit/054571c6d7caca455418e0f83056a0182315bd75, the tests were not shown as od test. And the former commit https://github.com/apache/shardingsphere-elasticjob/commit/2dee7265dad2f31034ff8fc26b621915b23a8826 detect these four test as od tests. The log files are on my vm. The files path are /home/zyl2/logfile/shardingsphere-slasticjob/054571c6d7caca455418e0f83056a0182315bd75 and /home/zyl2/logfile/shardingsphere-slasticjob/2dee7265dad2f31034ff8fc26b621915b23a8826

### CODE REVIEW

**Comment by darko-marinov** [comment]
>  I ran commits one by one
How many commits are there? Do you have a script to run those commits, or did you run them manually? What commands did you use? Do you have logs?

Last but not least, can you find which Git command could have done a better search than linear?

**Comment by same8891** [comment]
I first get the commits by file history from git. There are 11 commits. After running these commits, they all passed. But when I am finding another renamed test file org.apache.shardingsphere.elasticjob.lite.internal.snapshot.SnapshotServiceDisableTest. I run the commit in this file history and it just all pass too. So, I check another file elasticjob-lite/elasticjob-lite-core/src/main/java/org/apache/shardingsphere/elasticjob/lite/internal/snapshot/SnapshotService.java which is related to SnapshotServiceDisableTest. This time I found that these four test changed failed to pass on https://github.com/apache/shardingsphere-elasticjob/commit/6ef2a1d5ba299730f57c97c15ec1a55da9659542. So, I ran under from these commit and check when the test change from pass to fail to ensure the exact commit. I run it manually and I am not sure how many commit I run. But I think I run over 50 times. I will first delete the result and run the command. The below is my command
```
git reset --hard master 
git checkout 054571c6d7caca455418e0f83056a0182315bd75
cd ..
cd iDFlakies
bash pom-modify/modify-project.sh /home/zyl2/shardingsphere-elasticjob
cd ..
cd shardingsphere-elasticjob/
mvn clean install -pl elasticjob-lite/elasticjob-lite-core -am -DskipTests -Dmaven.javadoc.skip=true -Drat.skip
mvn  -pl elasticjob-lite/elasticjob-lite-core  idflakies:detect -Ddetector.detector_type=random-class-method -Ddt.randomize.rounds=10 -Ddt.detector.original_order.all_must_pass=false
```
I just change the commit sha and copy paste to run the whole command. I don't think there is a better way because the tests were fixed by not modifying the test file and related file. So, I think run linearly is the best way to findcorrect commit. I just saved the log for commit https://github.com/apache/shardingsphere-elasticjob/commit/054571c6d7caca455418e0f83056a0182315bd75 and https://github.com/apache/shardingsphere-elasticjob/commit/2dee7265dad2f31034ff8fc26b621915b23a8826

**Comment by darko-marinov** [comment]
It's good that you run `mvn clean`.

>  run it manually and I am not sure how many commit I run. But I think I run over 50 times.

Where are your over 50 logs?

What Git command could have worked better than linear search of one-by-one commit?

**Comment by same8891** [comment]
I didn't save that much log. Because most of the log didn't find any od test, I just pass through the next commit. I run the commit from new to old. After I found the commit that detected this four test as od tests, I just save this log file and its next commit that shows https://github.com/apache/shardingsphere-elasticjob/commit/2dee7265dad2f31034ff8fc26b621915b23a8826 next commit https://github.com/apache/shardingsphere-elasticjob/commit/054571c6d7caca455418e0f83056a0182315bd75 solve the problem.
For question 
```
What Git command could have worked better than linear search of one-by-one commit?
```
First I run the commit that are related to the test files. It seems that it do give some help but can't get the exact commit that fix the tests. I don't think there is any Git command could have worked better than linear search because it may fixed the test that the developer fixed other things that are unrelated to the tests. So, I think run linearly is the best way to find correct commit.

**Comment by darko-marinov** [comment]
Please try `git bisect` and see if it finds the same commit https://github.com/apache/shardingsphere-elasticjob/commit/054571c6d7caca455418e0f83056a0182315bd75 and its parent https://github.com/apache/shardingsphere-elasticjob/commit/2dee7265dad2f31034ff8fc26b621915b23a8826

**Comment by same8891** [comment]
I have run the git bisect and get the same result. I saved the bisect log in vm which path is /home/zyl2/logfile/shardingsphere-slasticjob/bisect.log. Also I saved each run of iDFlakies log in my vm, The path is under /home/zyl2/logfile/shardingsphere-slasticjob/. It really faster than linear time. Just learn a lot and know a new tool in git.

**Comment by darko-marinov** [comment]
Okay, the most important is that you learned! The rest will be easier to address. @zzjas please check the logs and changes. Thanks!

**Pull request merged**
