### PR TITLE
Update pr-data.csv to add 3 newly identified tests in hippo4j

### PR DESCRIPTION
**Pull request by bbelide2**
Updated pr-data.csv to add 3 newly identified tests in hippo4j.

Issue: https://github.com/TestingResearchIllinois/idoft/issues/797

### CODE REVIEW

**Comment by darko-marinov** [comment]
Can you run NonDex on all modules not just one module?

**Comment by bbelide2** [comment]
> Can you run NonDex on all modules not just one module?

I ran it on all modules separately. I did not find any other tests.

**Comment by darko-marinov** [comment]
You don't need to run each module separately (with `mvn nondex:nondex -pl MODULE`). Running just `mvn nondex:nondex` at the top level will run on all modules. However, if one fails, by default it'll stop. Can you find how to continue even if one fails?

**Comment by bbelide2** [comment]
> You don't need to run each module separately (with `mvn nondex:nondex -pl MODULE`). Running just `mvn nondex:nondex` at the top level will run on all modules. However, if one fails, by default it'll stop. Can you find how to continue even if one fails?

Yes Professor, I can try to find out how to continue even if one module fails. But for this repo, I already ran for all modules once and these 3 are the only new tests found.

**Comment by darko-marinov** [comment]
Please see my email.

**Comment by bbelide2** [comment]
I ran [runNondex.sh](https://github.com/TestingResearchIllinois/idoft/blob/main/auto-run-nondex/runNondex.sh) in hippo4j project to identify new tests. The logs are present in "/home/bbelide2/project/hippo4j/.runNondex" in my vm. There are 4 new tests identified out of which one test is already present in IDoFT. I added the remaining 3 in this PR.


I will check whether all 3 of them are ID tests or not and update soon.

**Comment by darko-marinov** [comment]
Thanks for adding the tests. Please check if they should be `ID` or `NOD`.

The script you used looks rather complex, if it just aims to run NonDex on each and every module. There's a simple command-line option in Maven to run on all modules and continue running even if some module fails. You may want to find that option and maybe improve the script.

**Comment by bbelide2** [comment]
I will look into the command for maven to run all the modules and update again.

Regarding the test category, I ran one test (cn.hippo4j.common.toolkit.http.HttpUtilsTest#buildUrl) 10 times. In each test, I ran only 1 NonDex run with a given seed (933178). I used a script to run this test 10 times and logged outputs.

**Result: The test failed all the 10 times.**

The script and the logs are present in my vm:

Script: /home/bbelide2/project/hippo4j/run_single_test.sh

Logs: /home/bbelide2/project/hippo4j/logs/newTest1
File new-test1-final-output.log  contains the final log:


```
Run 1 : Failed tests:   buildUrl(cn.hippo4j.common.toolkit.http.HttpUtilsTest): expected:<...p://localhost:46645?[password=hippo4jtest&username=hippo4j]> but was:<...p://localhost:46645?[username=hippo4j&password=hippo4jtest]>
Run 2 : Failed tests:   buildUrl(cn.hippo4j.common.toolkit.http.HttpUtilsTest): expected:<...p://localhost:41293?[password=hippo4jtest&username=hippo4j]> but was:<...p://localhost:41293?[username=hippo4j&password=hippo4jtest]>
Run 3 : Failed tests:   buildUrl(cn.hippo4j.common.toolkit.http.HttpUtilsTest): expected:<...p://localhost:44943?[password=hippo4jtest&username=hippo4j]> but was:<...p://localhost:44943?[username=hippo4j&password=hippo4jtest]>
Run 4 : Failed tests:   buildUrl(cn.hippo4j.common.toolkit.http.HttpUtilsTest): expected:<...p://localhost:44737?[password=hippo4jtest&username=hippo4j]> but was:<...p://localhost:44737?[username=hippo4j&password=hippo4jtest]>
Run 5 : Failed tests:   buildUrl(cn.hippo4j.common.toolkit.http.HttpUtilsTest): expected:<...p://localhost:35211?[password=hippo4jtest&username=hippo4j]> but was:<...p://localhost:35211?[username=hippo4j&password=hippo4jtest]>
Run 6 : Failed tests:   buildUrl(cn.hippo4j.common.toolkit.http.HttpUtilsTest): expected:<...p://localhost:39999?[password=hippo4jtest&username=hippo4j]> but was:<...p://localhost:39999?[username=hippo4j&password=hippo4jtest]>
Run 7 : Failed tests:   buildUrl(cn.hippo4j.common.toolkit.http.HttpUtilsTest): expected:<...p://localhost:38511?[password=hippo4jtest&username=hippo4j]> but was:<...p://localhost:38511?[username=hippo4j&password=hippo4jtest]>
Run 8 : Failed tests:   buildUrl(cn.hippo4j.common.toolkit.http.HttpUtilsTest): expected:<...p://localhost:38417?[password=hippo4jtest&username=hippo4j]> but was:<...p://localhost:38417?[username=hippo4j&password=hippo4jtest]>
Run 9 : Failed tests:   buildUrl(cn.hippo4j.common.toolkit.http.HttpUtilsTest): expected:<...p://localhost:38023?[password=hippo4jtest&username=hippo4j]> but was:<...p://localhost:38023?[username=hippo4j&password=hippo4jtest]>
Run 10 : Failed tests:   buildUrl(cn.hippo4j.common.toolkit.http.HttpUtilsTest): expected:<...p://localhost:45545?[password=hippo4jtest&username=hippo4j]> but was:<...p://localhost:45545?[username=hippo4j&password=hippo4jtest]>
````

Is this the correct way to confirm that a test is ```**ID** ``` ? If Yes, I will repeat the same process for the other 2 tests as well.

**Comment by bbelide2** [comment]
I tested remaining two tests as well. 

### Test 2: cn.hippo4j.common.toolkit.logtracing.LogMessageTest#testKvShouldPutAllKeyAndValuePairs

Test failed all the 10 times with seed 1016066

Logs: /home/bbelide2/project/hippo4j/logs/newTest2
new-test2-final-output.log 

```
Run 1 : Failed tests:   testKvShouldPutAllKeyAndValuePairs(cn.hippo4j.common.toolkit.logtracing.LogMessageTest): expected: <key1=value1||key2=value2> but was: <key2=value2||key1=value1>
Run 2 : Failed tests:   testKvShouldPutAllKeyAndValuePairs(cn.hippo4j.common.toolkit.logtracing.LogMessageTest): expected: <key1=value1||key2=value2> but was: <key2=value2||key1=value1>
Run 3 : Failed tests:   testKvShouldPutAllKeyAndValuePairs(cn.hippo4j.common.toolkit.logtracing.LogMessageTest): expected: <key1=value1||key2=value2> but was: <key2=value2||key1=value1>
Run 4 : Failed tests:   testKvShouldPutAllKeyAndValuePairs(cn.hippo4j.common.toolkit.logtracing.LogMessageTest): expected: <key1=value1||key2=value2> but was: <key2=value2||key1=value1>
Run 5 : Failed tests:   testKvShouldPutAllKeyAndValuePairs(cn.hippo4j.common.toolkit.logtracing.LogMessageTest): expected: <key1=value1||key2=value2> but was: <key2=value2||key1=value1>
Run 6 : Failed tests:   testKvShouldPutAllKeyAndValuePairs(cn.hippo4j.common.toolkit.logtracing.LogMessageTest): expected: <key1=value1||key2=value2> but was: <key2=value2||key1=value1>
Run 7 : Failed tests:   testKvShouldPutAllKeyAndValuePairs(cn.hippo4j.common.toolkit.logtracing.LogMessageTest): expected: <key1=value1||key2=value2> but was: <key2=value2||key1=value1>
Run 8 : Failed tests:   testKvShouldPutAllKeyAndValuePairs(cn.hippo4j.common.toolkit.logtracing.LogMessageTest): expected: <key1=value1||key2=value2> but was: <key2=value2||key1=value1>
Run 9 : Failed tests:   testKvShouldPutAllKeyAndValuePairs(cn.hippo4j.common.toolkit.logtracing.LogMessageTest): expected: <key1=value1||key2=value2> but was: <key2=value2||key1=value1>
Run 10 : Failed tests:   testKvShouldPutAllKeyAndValuePairs(cn.hippo4j.common.toolkit.logtracing.LogMessageTest): expected: <key1=value1||key2=value2> but was: <key2=value2||key1=value1>
```




### Test 3: cn.hippo4j.common.toolkit.logtracing.LogMessageTest#testToStringShouldPrintMessageAndAllKeyAndValuePairs

Test failed 5/10 times with seed 1016066

Logs: /home/bbelide2/project/hippo4j/logs/newTest3
new-test3-final-output.log 

```
Run 1 : Failed tests:   testToStringShouldPrintMessageAndAllKeyAndValuePairs(cn.hippo4j.common.toolkit.logtracing.LogMessageTest): expected: <messagekey1=value1||key2=value2> but was: <messagekey2=value2||key1=value1>
Run 2 : Failed tests:   testToStringShouldPrintMessageAndAllKeyAndValuePairs(cn.hippo4j.common.toolkit.logtracing.LogMessageTest): expected: <messagekey1=value1||key2=value2> but was: <messagekey2=value2||key1=value1>
Run 3 : Failed tests:   testToStringShouldPrintMessageAndAllKeyAndValuePairs(cn.hippo4j.common.toolkit.logtracing.LogMessageTest): expected: <messagekey1=value1||key2=value2> but was: <messagekey2=value2||key1=value1>
Run 4 : tests did not fail : logs/newTest3/new_test3_log_4_1697061973.log
Run 5 : tests did not fail : logs/newTest3/new_test3_log_5_1697061983.log
Run 6 : tests did not fail : logs/newTest3/new_test3_log_6_1697061993.log
Run 7 : Failed tests:   testToStringShouldPrintMessageAndAllKeyAndValuePairs(cn.hippo4j.common.toolkit.logtracing.LogMessageTest): expected: <messagekey1=value1||key2=value2> but was: <messagekey2=value2||key1=value1>
Run 8 : tests did not fail : logs/newTest3/new_test3_log_8_1697062013.log
Run 9 : tests did not fail : logs/newTest3/new_test3_log_9_1697062023.log
Run 10 : Failed tests:   testToStringShouldPrintMessageAndAllKeyAndValuePairs(cn.hippo4j.common.toolkit.logtracing.LogMessageTest): expected: <messagekey1=value1||key2=value2> but was: <messagekey2=value2||key1=value1>

```

Does this mean Test 3 is NOD ?

**Comment by darko-marinov** [comment]
If test 3 passes and fails for the same seed, then yes it's not `ID` but `NOD`. it depends on something else besides the orders that NonDex shuffles.

**Comment by bbelide2** [comment]
Thank you Professor. I updated the third test to NOD and revised the PR. 

I will take the script task as the next action item and work in it next.

**Comment by darko-marinov** [comment]
Okay, I've accepted the PR. Maybe you can look to fix the two `ID` tests, or ask Zijie for more tests from another repo.

**Pull request merged**
