### PR TITLE
Updated the status of pr-data to 'MovedToGradle' and added tests to gr-data.csv

### PR DESCRIPTION
**Pull request by deekshacheruku**
**Gradle Shift Commit:**

I have used the commit of Gradle Initiation as the SHA.

Maven Removal:
Jira Ticket: https://issues.apache.org/jira/browse/IGNITE-17487
Pull request: https://github.com/apache/ignite-3/pull/1421
Commit: https://github.com/apache/ignite-3/commit/44efe1e23ef8a14713fd8157e2239114903ede7d

Gradle Initiation:
Jira Ticket: https://issues.apache.org/jira/browse/IGNITE-17485
Pull Request: https://github.com/apache/ignite-3/pull/1032
Commit: https://github.com/apache/ignite-3/commit/2dc567bcaaed4a2999e2bf6c361a72e571a59cd4
Merged Commit: https://github.com/apache/ignite-3/commit/c91f39cd80dfd143e5ac848486366ad6ed124ce5.

**Tests Flaky?**

All the logs are in my VM Id: deeksha5@fa23-cs527-117 under the path ```/home/deeksha5/ignite-3/flaky-test```

*Before Moving To Gradle:*

* I checked the SHA detected (a1aa7fd4e2398c72827777ec5417d67915ff4da3). I couldn't build the project as the artifacts werent available. The commit was made on 10th Jun 2022.
Path: /home/deeksha5/ignite-3/mvn-install-1699924529.log
* I also tried the SHA (4a1baf49e666653e4e2a5e32c292629686259b3b) just before the removal of maven project (pom.xmls) which also yielded same result. The commit was made on Jan 12 2023.
Path: /home/deeksha5/ignite-3/mvn-install-1699924975.log

*After Moving To Gradle:*

Nondex Runs = 50 => Name has '50' 
Regular test => Name has 'test'
Nondex Normal Runs => Name has 'nondex'

This PR is small PR of https://github.com/TestingResearchIllinois/idoft/pull/978

Let me know if anything else is needed. Thanks in advance!

### CODE REVIEW

**Comment by deekshacheruku** [comment]
@darko-marinov @zzjas Can also review this PR? And let me know if there are any concerns. Thanks in advance!

**Comment by darko-marinov** [comment]
Sorry I didn't get to this earlier; I postponed as the change looked big. :) What exact command did you try on `4a1baf49e666653e4e2a5e32c292629686259b3b`?

**Comment by deekshacheruku** [comment]
> Sorry I didn't get to this earlier; I postponed as the change looked big. :) What exact command did you try on `4a1baf49e666653e4e2a5e32c292629686259b3b`?

Sorry professor but I am not sure about `4a1baf49e666653e4e2a5e32c292629686259b3b` commit. Can you please tell me where you have found this?

These are the two commits where the shift to gradle has happened.
Commit: https://github.com/apache/ignite-3/commit/2dc567bcaaed4a2999e2bf6c361a72e571a59cd4 => Actual commit where the shift happened but this commit does not belong to any branch on this repository, and may belong to a fork outside of the repository. 
Merged Commit: https://github.com/apache/ignite-3/commit/c91f39cd80dfd143e5ac848486366ad6ed124ce5.

These commits were found from the JIRA tickets 
https://issues.apache.org/jira/browse/IGNITE-17485
https://issues.apache.org/jira/browse/IGNITE-17487

Let me know if there are any concerns! Thanks in advance!

**Comment by deekshacheruku** [comment]
> You wrote (in [#1027 (comment)](https://github.com/TestingResearchIllinois/idoft/pull/1027#issue-1998498267)): "I also tried the SHA (4a1baf49e666653e4e2a5e32c292629686259b3b)..." So, what exactly did you try on that SHA?

I couldn't even build the project. The artifacts were not available similar to ```a1aa7fd4e2398c72827777ec5417d67915ff4da3``` previous SHA (Before Moving to Gradle).

Thanks @darko-marinov. Let me know if there are any other concerns.

**Comment by darko-marinov** [comment]
> I couldn't even build the project.

I already asked "What exact command did you try on `4a1baf49e666653e4e2a5e32c292629686259b3b`?" https://github.com/TestingResearchIllinois/idoft/pull/1027#issuecomment-1817926253

Did you run `git checkout 4a1baf49e666653e4e2a5e32c292629686259b3b; mvn clean install -DskipTests -pl ignite-configuration -am`? Where is your log?

**Comment by deekshacheruku** [comment]
Yes professor! that was the command i used. I first checkout and then tried to install but it couldnt build the project.

Log Path: /home/deeksha5/ignite-3/mvn-install-1699924975.log

**Comment by darko-marinov** [comment]
I got `[ERROR] [ERROR] Could not find the selected project in the reactor: ignite-configuration @`. It seems the module has been already moved. Did you check what the module is?

**Comment by deekshacheruku** [comment]
Try this professor ```mvn clean install -DskipTests -pl modules/configuration -am```. The gradle shift has a change in the module names while maven used different. @darko-marinov

**Comment by darko-marinov** [comment]
I tried that command, and it worked:
```
[INFO] Reactor Summary for ignite-bytecode 3.0.0-SNAPSHOT:
[INFO]
[INFO] ignite-bytecode .................................... SUCCESS [ 15.950 s]
[INFO] ignite-core ........................................ SUCCESS [  7.005 s]
[INFO] ignite-configuration-api ........................... SUCCESS [  0.390 s]
[INFO] ignite-configuration-annotation-processor .......... SUCCESS [  3.831 s]
[INFO] ignite-api ......................................... SUCCESS [  1.118 s]
[INFO] ignite-rest-api .................................... SUCCESS [  3.239 s]
[INFO] ignite-configuration ............................... SUCCESS [  9.302 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  42.823 s
[INFO] Finished at: 2023-11-23T13:57:46-06:00
[INFO] ------------------------------------------------------------------------
```

Please double check the results you reported.

**Comment by deekshacheruku** [comment]
For commit ```4a1baf49e666653e4e2a5e32c292629686259b3b``` just before the gradle shift

org.apache.ignite.internal.configuration.ConfigurationRegistryTest.testComplicatedPolymorphicConfig   => ```/home/deeksha5/ignite-3/mvn-nondex-finalcheck-1700770060.log```

org.apache.ignite.internal.configuration.notifications.ConfigurationAnyListenerTest  => ```/home/deeksha5/ignite-3/mvn-nondex-finalcheck-1700770263.log```  

org.apache.ignite.internal.configuration.notifications.ConfigurationListenerTest  => ```/home/deeksha5/ignite-3/mvn-nondex-finalcheck-1700770354.log```

=> Hence they were flaky before the shift to gradle @darko-marinov

**Comment by darko-marinov** [comment]
Okay, it's great that you compiled that commit (not sure what problems you had before because we may not know what commands you ran). Did you double check that all 53 tests were reported and not more (or fewer)?

**Comment by deekshacheruku** [comment]
Yes Professor! The reported 53 tests are moved to Gradle and are detected flaky in Gradle. The logs are in path ```/home/deeksha5/ignite-3/flaky-test```.
Nondex Runs = 50 => Name has '50'
Regular test => Name has 'test'
Nondex Normal Runs => Name has 'nondex'

@darko-marinov

**Comment by darko-marinov** [comment]
I'm ready to accept, but I see `This branch has conflicts that must be resolved`.

**Comment by deekshacheruku** [comment]
@darko-marinov I have rebased the branch! Thanks a lot!

**Pull request merged**
