### PR TITLE
Corrected test paths

### PR DESCRIPTION
**Pull request by Ethan-Chin**
Corrected 3 test paths for `bytedeco/javacpp`

### CODE REVIEW

**Comment by darko-marinov** [comment]
Thanks for the correction. Did these tests fail in the class constructor (and someone reported the name somewhat incorrectly)?

**Comment by Ethan-Chin** [comment]
Sorry, I don't quite understand what you mean. These 3 tests were assigned to me and Maven cannot run these tests using the incorrect test name.

**Comment by darko-marinov** [comment]
Your test names have no method names just class names. Why are there no method names? (It could be because the test classes crash in the constructor in some `@BeforeClass` step.)

**Comment by Ethan-Chin** [comment]
The test won't crash with test names. I'm not sure why the three lines did not include test name in the first place, but the test paths are wrong anyway.

**Comment by darko-marinov** [comment]
What are the correct "test paths" (fully qualified class names)? Were the test classes failing in the static initializer, class constructor, or some `@BeforeClass`?

**Comment by darko-marinov** [comment]
I'm still waiting for a reply here. We can close this PR for negative "points", or you can explain where the tests fail.

**Comment by Ethan-Chin** [comment]
> What are the correct "test paths" (fully qualified class names)? Were the test classes failing in the static initializer, class constructor, or some `@BeforeClass`?

No, the tests won't fail anywhere with the correct paths as you can see in my file diff:
```shell
org.bytedeco.javacpp.BufferTest
org.bytedeco.javacpp.EnumTest
org.bytedeco.javacpp.PointerTest
```

Those correct paths do not include the method names just because the original test paths do not include them in the first place, but it won't have problems if method names were added.

**Comment by Ethan-Chin** [comment]
> What are the correct "test paths" (fully qualified class names)? Were the test classes failing in the static initializer, class constructor, or some `@BeforeClass`?

Apologies for the misunderstanding.

Yes. `org.bytedeco.javacpp.PointerTest`, `org.bytedeco.javacpp.EnumTest`, and `org.bytedeco.javacpp.BufferTest` all fail in their setUpClass() when using NonDex. This is the reason why these tests do not include specific method names.

**Comment by darko-marinov** [comment]
Thanks for clarifying. Can you tell me here a direct link to `setUpClass` on GitHub (with that `#LineNumber` at the end)? At least that should be added in the `Notes` column, and maybe some (the first?) test method name should be provided, even if the test class can't even reach that method.

**Comment by Ethan-Chin** [comment]
These are the links to `setUpClass`

```shell
https://github.com/bytedeco/javacpp/blob/master/src/test/java/org/bytedeco/javacpp/BufferTest.java#L78
https://github.com/bytedeco/javacpp/blob/master/src/test/java/org/bytedeco/javacpp/EnumTest.java#L92
https://github.com/bytedeco/javacpp/blob/master/src/test/java/org/bytedeco/javacpp/PointerTest.java#L69
```

**Comment by darko-marinov** [comment]
Thanks for all the updates. The lines look much better now. Just one final request: replace the URLs like https://github.com/bytedeco/javacpp/blob/master/src/test/java/org/bytedeco/javacpp/BufferTest.java#L78 with URLs to the specific commit (otherwise as `master` changes, the line number may change and not be 78 as in this example).

**Comment by Ethan-Chin** [comment]
Thanks. I have updated them with the commit id

**Pull request merged**
