### PR TITLE
Add developer fixed for fastjson2 assigned test

### PR DESCRIPTION
**Pull request by Mukta13**
This test is not flaky anymore. The logs can be found on my VM in /home/muktaj2/fastjson2/run1-nondex-log-1.txt where the tests for Issue507 passes successfully. This test was fixed in this commit: https://github.com/alibaba/fastjson2/commit/927bb9f1917636b87026ad90660f83fc4c2be61c

### CODE REVIEW

**Comment by darko-marinov** [comment]
Can you find the PR for this commit and change to `Accepted` with that PR link?

**Comment by Mukta13** [comment]
Added

**Comment by darko-marinov** [comment]
Thanks. How did you find the PR? You can get more "points" for it.

**Comment by Mukta13** [comment]
> Thanks. How did you find the PR? You can get more "points" for it.

1. Since I knew the SHA of the commit id that fixed the flaky test, I just typed `927bb9f1917636b87026ad90660f83fc4c2be61c is:merged` in the pull requests searches and it fetched me the pr related to the commit id. 

2. Another way to do this is by using this url search: https://github.com/search?q=927bb9f1917636b87026ad90660f83fc4c2be61c&type=pullrequests where I just added the SHA after `'search?q='`. 
 I used this documentation as a reference: https://docs.github.com/en/search-github/searching-on-github/searching-issues-and-pull-requests#search-by-commit-sha

4. Or this can also be found using the github cli command: `gh pr list --search "927bb9f" --state merged`, which also shows the pr number related to the SHA that was merged. (Screenshot attached)

[
Screenshot 2024-11-06 at 10 46 21 AM
](url)

**Pull request merged**
