### PR TITLE
Changed status of `shouldWriteAndRead` test to MovedOrRenamed

### PR DESCRIPTION
**Pull request by yesh385**
This PR updates the status of the test `org.apache.tinkerpop.gremlin.driver.ser.binary.GraphBinaryReaderWriterRoundTripTest.shouldWriteAndRead[TypeTraversalMetrics]` to MovedOrRenamed. This test was originally present in `gremlin-driver/src/test/java/org/apache/tinkerpop/gremlin/driver/ser/binary/GraphBinaryReaderWriterRoundTripTest.java`, but was later moved to `gremlin-util/src/test/java/org/apache/tinkerpop/gremlin/driver/ser/binary/GraphBinaryReaderWriterRoundTripTest.java` in this commit: https://github.com/apache/tinkerpop/commit/f5b6abb89e5846768ffe702c1d3842e5d29abed5

### CODE REVIEW

**Comment by darko-marinov** [comment]
Please see email and try to address as soon as possible.

Also, please do not open PRs from `main` in your fork. I'll start rejecting those PRs.

**Comment by yesh385** [comment]
Updated the PR professor. Kindly let me know if if this fine. Thank you.

**Comment by darko-marinov** [comment]
Okay, you correctly marked that the test is not where it was. But where is the test now? Can you add a line with the new location (module, class, method)? Is the test `ID` in the new location? (Save the log and let us know privately where to check the log.)

**Comment by yesh385** [comment]
Sure professor, I’ll add a new entry with the new location. Yes, the test is ID in the new location. Sure, I’ll add the logs in the VM assigned to me and let you know.

Thank you,
S. Yeshwanth

From: darko-marinov ***@***.***>
Date: Monday, November 6, 2023 at 8:33 PM
To: TestingResearchIllinois/idoft ***@***.***>
Cc: Sripathy, Yeshwanth ***@***.***>, Author ***@***.***>
Subject: Re: [TestingResearchIllinois/idoft] Changed status of `shouldWriteAndRead` test to MovedOrRenamed (PR #912)

Okay, you correctly marked that the test is not where it was. But where is the test now? Can you add a line with the new location (module, class, method)? Is the test ID in the new location? (Save the log and let us know privately where to check the log.)

**Pull request merged**
