### PR TITLE
Update pr-data.csv

### PR DESCRIPTION
**Pull request by prathyushreddylpr**
Collaborated with other students to raise a single Pull Request for all the changes.

### CODE REVIEW

**Comment by darko-marinov** [comment]
Let's wait for @zzjas to comment on this and #1207

**Comment by zzjas** [comment]
Ok to merge @darko-marinov

**Comment by zzjas** [comment]
Can you also update the entry `FlattenSpecParquetReaderTest.testFlat1NoFlattenSpec`? It had the same PR link.

**Comment by prathyushreddylpr** [comment]
> Can you also update the entry `FlattenSpecParquetReaderTest.testFlat1NoFlattenSpec`? It had the same PR link.

Updated

**Comment by darko-marinov** [comment]
Please resolve conflicts so we can merge.

**Comment by prathyushreddylpr** [comment]
> Please resolve conflicts so we can merge.

Resolved

**Pull request merged**
