### PR TITLE
pr status updated

### PR DESCRIPTION
**Pull request by Ethan-Chin**
One PR for https://github.com/apache/druid Opened, another PR for https://github.com/ferstl/depgraph-maven-plugin Opened.

A flaky test in https://github.com/espertechinc/esper has been fixed by developers in commits https://github.com/espertechinc/esper/commit/414736e34147652d77f5dbe024eec994b0ae7bc4 (see logs below)

### CODE REVIEW

**Comment by Ethan-Chin** [comment]
logs of commit 7a20de01da2361086229065f337794351ffed757:

```shell
INFO: The original argline is: 
INFO: Adding NonDex argLine to existing argLine specified by the project
CONFIG: nondexFilter=.*
nondexMode=FULL
nondexSeed=933178
nondexStart=0
nondexEnd=9223372036854775807
nondexPrintstack=false
nondexDir=/home/yucong3/esper/regression-run/.nondex
nondexJarDir=.nondex
nondexExecid=clean_Tj689++nnVBAtbtE2rKRmUsM7DDD9JL28+ZWytvwglI=
nondexLogging=CONFIG
test=
[INFO] Using auto detected provider org.apache.maven.surefire.junit4.JUnit4Provider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLSpatial
21:17:02,861 INFO  [EPRuntimeImpl] Initializing runtime URI 'default' version 8.7.0
21:17:03,005 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexPatternSimple
21:17:04,190 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexPerfPattern
21:17:04,731 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexTypeAssertion
21:17:04,916 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexWContext
21:17:05,325 INFO  [EPRuntimeImpl] Destroying runtime URI 'default'
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.698 s - in com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLSpatial
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
INFO: Adding excluded groups to newly created one
INFO: Adding NonDex argLine to existing argLine specified by the project
CONFIG: nondexFilter=.*
nondexMode=FULL
nondexSeed=933178
nondexStart=0
nondexEnd=9223372036854775807
nondexPrintstack=false
nondexDir=/home/yucong3/esper/regression-run/.nondex
nondexJarDir=/home/yucong3/esper/regression-run/.nondex
nondexExecid=F+nM0rXx0aohLlHDmg1NCOfjcDEQyPy3n6mGZxC1pU=
nondexLogging=CONFIG
test=
[INFO] Using auto detected provider org.apache.maven.surefire.junitcore.JUnitCoreProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLSpatial
21:17:06,035 INFO  [EPRuntimeImpl] Initializing runtime URI 'default' version 8.7.0
21:17:06,190 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexPatternSimple
21:17:07,432 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexPerfPattern
21:17:08,353 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexTypeAssertion
21:17:08,593 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexWContext
21:17:09,040 INFO  [EPRuntimeImpl] Destroying runtime URI 'default'
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.197 s - in com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLSpatial
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
INFO: Adding excluded groups to newly created one
INFO: Adding NonDex argLine to existing argLine specified by the project
CONFIG: nondexFilter=.*
nondexMode=FULL
nondexSeed=974622
nondexStart=0
nondexEnd=9223372036854775807
nondexPrintstack=false
nondexDir=/home/yucong3/esper/regression-run/.nondex
nondexJarDir=/home/yucong3/esper/regression-run/.nondex
nondexExecid=MmKDxKjPDcEvXEifXwOB8d29gzzEAYZo6oSNtdyMhrk=
nondexLogging=CONFIG
test=
[INFO] Using auto detected provider org.apache.maven.surefire.junitcore.JUnitCoreProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLSpatial
21:17:09,593 INFO  [EPRuntimeImpl] Initializing runtime URI 'default' version 8.7.0
21:17:09,744 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexPatternSimple
21:17:10,916 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexPerfPattern
21:17:11,500 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexTypeAssertion
21:17:11,706 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexWContext
21:17:12,159 INFO  [EPRuntimeImpl] Destroying runtime URI 'default'
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.763 s - in com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLSpatial
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
INFO: Adding excluded groups to newly created one
INFO: Adding NonDex argLine to existing argLine specified by the project
CONFIG: nondexFilter=.*
nondexMode=FULL
nondexSeed=1016066
nondexStart=0
nondexEnd=9223372036854775807
nondexPrintstack=false
nondexDir=/home/yucong3/esper/regression-run/.nondex
nondexJarDir=/home/yucong3/esper/regression-run/.nondex
nondexExecid=1CafIGXxmPCd6dbyNywg3osDnofnMWD++gadtbs8Drw=
nondexLogging=CONFIG
test=
[INFO] Using auto detected provider org.apache.maven.surefire.junitcore.JUnitCoreProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLSpatial
21:17:12,751 INFO  [EPRuntimeImpl] Initializing runtime URI 'default' version 8.7.0
21:17:12,904 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexPatternSimple
21:17:14,027 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexPerfPattern
21:17:14,638 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexTypeAssertion
21:17:14,786 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexWContext
21:17:15,205 INFO  [EPRuntimeImpl] Destroying runtime URI 'default'
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 2.653 s - in com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLSpatial
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
INFO: Adding excluded groups to newly created one
INFO: Adding NonDex argLine to existing argLine specified by the project
CONFIG: nondexFilter=.*
nondexMode=FULL
nondexSeed=1057510
nondexStart=0
nondexEnd=9223372036854775807
nondexPrintstack=false
nondexDir=/home/yucong3/esper/regression-run/.nondex
nondexJarDir=/home/yucong3/esper/regression-run/.nondex
nondexExecid=F60gZOfIO00HM1TO6rx0N9iqFsyo35zsmW0oziZ8fUM=
nondexLogging=CONFIG
test=
[INFO] Using auto detected provider org.apache.maven.surefire.junitcore.JUnitCoreProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLSpatial
21:17:15,812 INFO  [EPRuntimeImpl] Initializing runtime URI 'default' version 8.7.0
21:17:16,031 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexPatternSimple
21:17:17,492 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexPerfPattern
21:17:19,208 INFO  [EPRuntimeImpl] Destroying runtime URI 'default'
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 3.61 s <<< FAILURE! - in com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLSpatial
[ERROR] com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLSpatial.testEPLSpatialMXCIFQuadTreeFilterIndex  Time elapsed: 3.588 s  <<< FAILURE!
java.lang.AssertionError: Delta: 1303
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.assertTrue(Assert.java:41)
        at com.espertech.esper.regressionlib.support.util.SupportSpatialUtil.sendAssertSpatialAABB(SupportSpatialUtil.java:280)
        at com.espertech.esper.regressionlib.suite.epl.spatial.EPLSpatialMXCIFQuadTreeFilterIndex$EPLSpatialMXCIFFilterIndexPerfPattern.run(EPLSpatialMXCIFQuadTreeFilterIndex.java:112)
        at com.espertech.esper.regressionrun.runner.RegressionRunner.run(RegressionRunner.java:77)
        at com.espertech.esper.regressionrun.runner.RegressionRunner.run(RegressionRunner.java:53)
        at com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLSpatial.testEPLSpatialMXCIFQuadTreeFilterIndex(TestSuiteEPLSpatial.java:40)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at junit.framework.TestCase.runTest(TestCase.java:176)
        at junit.framework.TestCase.runBare(TestCase.java:141)
        at junit.framework.TestResult$1.protect(TestResult.java:122)
        at junit.framework.TestResult.runProtected(TestResult.java:142)
        at junit.framework.TestResult.run(TestResult.java:125)
        at junit.framework.TestCase.run(TestCase.java:129)
        at junit.framework.TestSuite.runTest(TestSuite.java:255)
        at junit.framework.TestSuite.run(TestSuite.java:250)
        at org.junit.internal.runners.JUnit38ClassRunner.run(JUnit38ClassRunner.java:84)
        at org.junit.runners.Suite.runChild(Suite.java:127)
        at org.junit.runners.Suite.runChild(Suite.java:26)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:309)
        at org.apache.maven.surefire.junitcore.JUnitCore.run(JUnitCore.java:49)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createRequestAndRun(JUnitCoreWrapper.java:120)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:95)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:75)
        at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:69)
        at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:146)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)

[INFO] 
[INFO] Results:
[INFO] 
[ERROR] Failures: 
[ERROR]   TestSuiteEPLSpatial.testEPLSpatialMXCIFQuadTreeFilterIndex:40 Delta: 1303
[INFO] 
[ERROR] Tests run: 1, Failures: 1, Errors: 0, Skipped: 0
[INFO] 
INFO: Surefire failed when running tests for F60gZOfIO00HM1TO6rx0N9iqFsyo35zsmW0oziZ8fUM=
INFO: Adding excluded groups to newly created one
INFO: Adding NonDex argLine to existing argLine specified by the project
CONFIG: nondexFilter=.*
nondexMode=FULL
nondexSeed=1098954
nondexStart=0
nondexEnd=9223372036854775807
nondexPrintstack=false
nondexDir=/home/yucong3/esper/regression-run/.nondex
nondexJarDir=/home/yucong3/esper/regression-run/.nondex
nondexExecid=gpnHEdeyNErVFqn01Yqz8q2pzF5qfgv+1FYfwxNbE=
nondexLogging=CONFIG
test=
[INFO] Using auto detected provider org.apache.maven.surefire.junitcore.JUnitCoreProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLSpatial
21:17:20,440 INFO  [EPRuntimeImpl] Initializing runtime URI 'default' version 8.7.0
21:17:20,666 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexPatternSimple
21:17:22,206 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexPerfPattern
21:17:22,954 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexTypeAssertion
21:17:23,161 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexWContext
21:17:23,628 INFO  [EPRuntimeImpl] Destroying runtime URI 'default'
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.482 s - in com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLSpatial
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] NonDex SUMMARY:
[INFO] *********
[INFO] mvn nondex:nondex  -DnondexFilter='.*' -DnondexMode=FULL -DnondexSeed=933178 -DnondexStart=0 -DnondexEnd=9223372036854775807 -DnondexPrintstack=false -DnondexDir="/home/yucong3/esper/regression-run/.nondex" -DnondexJarDir="/home/yucong3/esper/regression-run/.nondex" -DnondexExecid=F+nM0rXx0aohLlHDmg1NCOfjcDEQyPy3n6mGZxC1pU= -DnondexLogging=CONFIG
[INFO] No Test Failed with this configuration.
[INFO] *********
[INFO] *********
[INFO] mvn nondex:nondex  -DnondexFilter='.*' -DnondexMode=FULL -DnondexSeed=974622 -DnondexStart=0 -DnondexEnd=9223372036854775807 -DnondexPrintstack=false -DnondexDir="/home/yucong3/esper/regression-run/.nondex" -DnondexJarDir="/home/yucong3/esper/regression-run/.nondex" -DnondexExecid=MmKDxKjPDcEvXEifXwOB8d29gzzEAYZo6oSNtdyMhrk= -DnondexLogging=CONFIG
[INFO] No Test Failed with this configuration.
[INFO] *********
[INFO] *********
[INFO] mvn nondex:nondex  -DnondexFilter='.*' -DnondexMode=FULL -DnondexSeed=1016066 -DnondexStart=0 -DnondexEnd=9223372036854775807 -DnondexPrintstack=false -DnondexDir="/home/yucong3/esper/regression-run/.nondex" -DnondexJarDir="/home/yucong3/esper/regression-run/.nondex" -DnondexExecid=1CafIGXxmPCd6dbyNywg3osDnofnMWD++gadtbs8Drw= -DnondexLogging=CONFIG
[INFO] No Test Failed with this configuration.
[INFO] *********
[INFO] *********
[INFO] mvn nondex:nondex  -DnondexFilter='.*' -DnondexMode=FULL -DnondexSeed=1057510 -DnondexStart=0 -DnondexEnd=9223372036854775807 -DnondexPrintstack=false -DnondexDir="/home/yucong3/esper/regression-run/.nondex" -DnondexJarDir="/home/yucong3/esper/regression-run/.nondex" -DnondexExecid=F60gZOfIO00HM1TO6rx0N9iqFsyo35zsmW0oziZ8fUM= -DnondexLogging=CONFIG
[WARNING] com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLSpatial#testEPLSpatialMXCIFQuadTreeFilterIndex
[INFO] *********
[INFO] *********
[INFO] mvn nondex:nondex  -DnondexFilter='.*' -DnondexMode=FULL -DnondexSeed=1098954 -DnondexStart=0 -DnondexEnd=9223372036854775807 -DnondexPrintstack=false -DnondexDir="/home/yucong3/esper/regression-run/.nondex" -DnondexJarDir="/home/yucong3/esper/regression-run/.nondex" -DnondexExecid=gpnHEdeyNErVFqn01Yqz8q2pzF5qfgv+1FYfwxNbE= -DnondexLogging=CONFIG
[INFO] No Test Failed with this configuration.
[INFO] *********
[INFO] All tests pass without NonDex shuffling
[INFO] ####################
[INFO] Across all seeds:
[INFO] com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLSpatial#testEPLSpatialMXCIFQuadTreeFilterIndex
[INFO] Test results can be found at: 
[INFO] file:///home/yucong3/esper/regression-run/.nondex/F+nM0rXx0aohLlHDmg1NCOfjcDEQyPy3n6mGZxC1pU=/test_results.html
[INFO] [NonDex] The id of this run is: F+nM0rXx0aohLlHDmg1NCOfjcDEQyPy3n6mGZxC1pU=
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  24.241 s
[INFO] Finished at: 2024-10-10T21:17:23-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal edu.illinois:nondex-maven-plugin:2.1.7:nondex (default-cli) on project esper-regression-run: Unable to execute mojo: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/yucong3/esper/regression-run/.nondex/F60gZOfIO00HM1TO6rx0N9iqFsyo35zsmW0oziZ8fUM= for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException
```

**Comment by Ethan-Chin** [comment]
logs of commit 414736e34147652d77f5dbe024eec994b0ae7bc4:

```shell
INFO: The original argline is: 
INFO: Adding NonDex argLine to existing argLine specified by the project
CONFIG: nondexFilter=.*
nondexMode=FULL
nondexSeed=933178
nondexStart=0
nondexEnd=9223372036854775807
nondexPrintstack=false
nondexDir=/home/yucong3/esper/regression-run/.nondex
nondexJarDir=.nondex
nondexExecid=clean_eHmnZMPwYGYihSYWn5s9oTxp59Sr7YzvxERG+iLtpY=
nondexLogging=CONFIG
test=
[INFO] Using auto detected provider org.apache.maven.surefire.junit4.JUnit4Provider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLSpatial
20:46:53,848 INFO  [EPRuntimeImpl] Initializing runtime URI 'default' version 8.5.0
20:46:53,970 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexPatternSimple
20:46:55,136 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexPerfPattern
20:46:56,252 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexTypeAssertion
20:46:56,417 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexWContext
20:46:56,768 INFO  [EPRuntimeImpl] Destroying runtime URI 'default'
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.158 s - in com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLSpatial
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
INFO: Adding excluded groups to newly created one
INFO: Adding NonDex argLine to existing argLine specified by the project
CONFIG: nondexFilter=.*
nondexMode=FULL
nondexSeed=933178
nondexStart=0
nondexEnd=9223372036854775807
nondexPrintstack=false
nondexDir=/home/yucong3/esper/regression-run/.nondex
nondexJarDir=/home/yucong3/esper/regression-run/.nondex
nondexExecid=qTMvPy7jbxg6gfYul3vDHjuMzgBrh9Nn7bgYq1FVhmU=
nondexLogging=CONFIG
test=
[INFO] Using auto detected provider org.apache.maven.surefire.junitcore.JUnitCoreProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLSpatial
20:46:57,493 INFO  [EPRuntimeImpl] Initializing runtime URI 'default' version 8.5.0
20:46:57,614 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexPatternSimple
20:46:58,850 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexPerfPattern
20:46:59,541 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexTypeAssertion
20:46:59,834 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexWContext
20:47:00,337 INFO  [EPRuntimeImpl] Destroying runtime URI 'default'
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.036 s - in com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLSpatial
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
INFO: Adding excluded groups to newly created one
INFO: Adding NonDex argLine to existing argLine specified by the project
CONFIG: nondexFilter=.*
nondexMode=FULL
nondexSeed=974622
nondexStart=0
nondexEnd=9223372036854775807
nondexPrintstack=false
nondexDir=/home/yucong3/esper/regression-run/.nondex
nondexJarDir=/home/yucong3/esper/regression-run/.nondex
nondexExecid=pqC+g+cwIQdOQE5Y1Ygy4VUPGQRZOld47PQMwJGsLQ8=
nondexLogging=CONFIG
test=
[INFO] Using auto detected provider org.apache.maven.surefire.junitcore.JUnitCoreProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLSpatial
20:47:01,223 INFO  [EPRuntimeImpl] Initializing runtime URI 'default' version 8.5.0
20:47:01,452 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexPatternSimple
20:47:02,694 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexPerfPattern
20:47:03,734 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexTypeAssertion
20:47:04,005 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexWContext
20:47:04,461 INFO  [EPRuntimeImpl] Destroying runtime URI 'default'
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.552 s - in com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLSpatial
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
INFO: Adding excluded groups to newly created one
INFO: Adding NonDex argLine to existing argLine specified by the project
CONFIG: nondexFilter=.*
nondexMode=FULL
nondexSeed=1016066
nondexStart=0
nondexEnd=9223372036854775807
nondexPrintstack=false
nondexDir=/home/yucong3/esper/regression-run/.nondex
nondexJarDir=/home/yucong3/esper/regression-run/.nondex
nondexExecid=KgPB1efqLrhIEm53Aj5G28cdWUp97yh7l7kFVVE3F5A=
nondexLogging=CONFIG
test=
[INFO] Using auto detected provider org.apache.maven.surefire.junitcore.JUnitCoreProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLSpatial
20:47:05,044 INFO  [EPRuntimeImpl] Initializing runtime URI 'default' version 8.5.0
20:47:05,170 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexPatternSimple
20:47:06,493 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexPerfPattern
20:47:07,178 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexTypeAssertion
20:47:07,488 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexWContext
20:47:07,880 INFO  [EPRuntimeImpl] Destroying runtime URI 'default'
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.018 s - in com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLSpatial
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
INFO: Adding excluded groups to newly created one
INFO: Adding NonDex argLine to existing argLine specified by the project
CONFIG: nondexFilter=.*
nondexMode=FULL
nondexSeed=1057510
nondexStart=0
nondexEnd=9223372036854775807
nondexPrintstack=false
nondexDir=/home/yucong3/esper/regression-run/.nondex
nondexJarDir=/home/yucong3/esper/regression-run/.nondex
nondexExecid=y7Vs8bSFBIKIrJ3z4WQQXuwuwuLoLxZA73hDsDB2k=
nondexLogging=CONFIG
test=
[INFO] Using auto detected provider org.apache.maven.surefire.junitcore.JUnitCoreProvider
[INFO] 
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLSpatial
20:47:08,718 INFO  [EPRuntimeImpl] Initializing runtime URI 'default' version 8.5.0
20:47:08,913 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexPatternSimple
20:47:10,185 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexPerfPattern
20:47:11,244 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexTypeAssertion
20:47:11,549 INFO  [RegressionRunner] Running test EPLSpatialMXCIFFilterIndexWContext
20:47:11,921 INFO  [EPRuntimeImpl] Destroying runtime URI 'default'
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 3.486 s - in com.espertech.esper.regressionrun.suite.epl.TestSuiteEPLSpatial
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] NonDex SUMMARY:
[INFO] *********
[INFO] mvn nondex:nondex  -DnondexFilter='.*' -DnondexMode=FULL -DnondexSeed=933178 -DnondexStart=0 -DnondexEnd=9223372036854775807 -DnondexPrintstack=false -DnondexDir="/home/yucong3/esper/regression-run/.nondex" -DnondexJarDir="/home/yucong3/esper/regression-run/.nondex" -DnondexExecid=qTMvPy7jbxg6gfYul3vDHjuMzgBrh9Nn7bgYq1FVhmU= -DnondexLogging=CONFIG
[INFO] No Test Failed with this configuration.
[INFO] *********
[INFO] *********
[INFO] mvn nondex:nondex  -DnondexFilter='.*' -DnondexMode=FULL -DnondexSeed=974622 -DnondexStart=0 -DnondexEnd=9223372036854775807 -DnondexPrintstack=false -DnondexDir="/home/yucong3/esper/regression-run/.nondex" -DnondexJarDir="/home/yucong3/esper/regression-run/.nondex" -DnondexExecid=pqC+g+cwIQdOQE5Y1Ygy4VUPGQRZOld47PQMwJGsLQ8= -DnondexLogging=CONFIG
[INFO] No Test Failed with this configuration.
[INFO] *********
[INFO] *********
[INFO] mvn nondex:nondex  -DnondexFilter='.*' -DnondexMode=FULL -DnondexSeed=1016066 -DnondexStart=0 -DnondexEnd=9223372036854775807 -DnondexPrintstack=false -DnondexDir="/home/yucong3/esper/regression-run/.nondex" -DnondexJarDir="/home/yucong3/esper/regression-run/.nondex" -DnondexExecid=KgPB1efqLrhIEm53Aj5G28cdWUp97yh7l7kFVVE3F5A= -DnondexLogging=CONFIG
[INFO] No Test Failed with this configuration.
[INFO] *********
[INFO] *********
[INFO] mvn nondex:nondex  -DnondexFilter='.*' -DnondexMode=FULL -DnondexSeed=1057510 -DnondexStart=0 -DnondexEnd=9223372036854775807 -DnondexPrintstack=false -DnondexDir="/home/yucong3/esper/regression-run/.nondex" -DnondexJarDir="/home/yucong3/esper/regression-run/.nondex" -DnondexExecid=y7Vs8bSFBIKIrJ3z4WQQXuwuwuLoLxZA73hDsDB2k= -DnondexLogging=CONFIG
[INFO] No Test Failed with this configuration.
[INFO] *********
[INFO] All tests pass without NonDex shuffling
[INFO] ####################
[INFO] Across all seeds:
[INFO] Test results can be found at: 
[INFO] file:///home/yucong3/esper/regression-run/.nondex/qTMvPy7jbxg6gfYul3vDHjuMzgBrh9Nn7bgYq1FVhmU=/test_results.html
[INFO] [NonDex] The id of this run is: qTMvPy7jbxg6gfYul3vDHjuMzgBrh9Nn7bgYq1FVhmU=
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  21.415 s
[INFO] Finished at: 2024-10-10T20:47:12-05:00
[INFO] ------------------------------------------------------------------------
```

**Comment by darko-marinov** [comment]
I can accept the two opened PRs, but `DeveloperFixed` would require more discussion. Can you split this PR into two? Also please keep logs on the VM. To show that a test is not `ID`, it'd be good to run (many) more times than the default `-DnondexRun=3`. Also, it'd be good to show how you (re)installed the project when running on two commits.

**Comment by Ethan-Chin** [comment]
> I can accept the two opened PRs, but `DeveloperFixed` would require more discussion. Can you split this PR into two? Also please keep logs on the VM. To show that a test is not `ID`, it'd be good to run (many) more times than the default `-DnondexRun=3`. Also, it'd be good to show how you (re)installed the project when running on two commits.

Thanks, I have updated this PR to only include those two Opened

**Pull request merged**
