### PR TITLE
update /FudanNLP/fnlp

### PR DESCRIPTION
**Pull request by Einsteinnnnn**
There are two tests in one GitHub repo.

First test: 
`https://github.com/FudanNLP/fnlp,ce258f3e4a5add2ba0b5e4cbac7cab2190af6659,fnlp-core,org.fnlp.nlp.cn.tag.CWSTaggerTest.org.fnlp.nlp.cn.tag.CWSTaggerTest,ID,,,`

First, the location of the test is wrong on the pr-data, it is `org.fnlp.nlp.cn.tag.CWSTaggerTest` not `org.fnlp.nlp.cn.tag.CWSTaggerTest.org.fnlp.nlp.cn.tag.CWSTaggerTest`. 
Pr link to the fix: https://github.com/FudanNLP/fnlp/pull/70

Second test:

`https://github.com/FudanNLP/fnlp,ce258f3e4a5add2ba0b5e4cbac7cab2190af6659,fnlp-core,org.fnlp.nlp.cn.tag.POSTaggerTest.org.fnlp.nlp.cn.tag.POSTaggerTest,ID,,,`

As the first test, the location of the test class is wrong. 
But after all the test, the POSTaggerTest.java is not failing at all. The `mvn test` shows the fnlp-demo fails, not fnlp-core that the POSTaggerTest was in. So I think remove this test.
The error message:
```
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for fnlp-all 2.1-SNAPSHOT:
[INFO] 
[INFO] fnlp-core .......................................... SUCCESS [  5.516 s]
[INFO] fnlp-all ........................................... SUCCESS [  0.003 s]
[INFO] fnlp-dev ........................................... SUCCESS [  0.880 s]
[INFO] fnlp-train ......................................... SUCCESS [  0.975 s]
[INFO] fnlp-app ........................................... SUCCESS [  2.701 s]
[INFO] fnlp-demo .......................................... FAILURE [ 15.912 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  26.122 s
[INFO] Finished at: 2023-10-26T21:10:49-05:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test (default-test) on project fnlp-demo: Execution default-test of goal org.apache.maven.plugins:maven-surefire-plugin:2.12.4:test failed: The forked VM terminated without saying properly goodbye. VM crash or System.exit called ? -> [Help 1]
```

### CODE REVIEW

**Comment by darko-marinov** [comment]
> the location of the test is wrong

Is the location wrong in the commit where the test was reported or in the latest commit?

**Comment by Einsteinnnnn** [comment]
@darko-marinov 

> > the location of the test is wrong
> 
> Is the location wrong in the commit where the test was reported or in the latest commit?

I think it is wrong in the pr-data.csv file, because the actual path was repeated twice. 
Like 
Correct: `org.fnlp.nlp.cn.tag.CWSTaggerTest`
Wrong:   `org.fnlp.nlp.cn.tag.CWSTaggerTest.org.fnlp.nlp.cn.tag.CWSTaggerTest`

**Comment by darko-marinov** [comment]
Indeed, that name looks clearly wrong. If NonDex by default doesn't fail on the test method itself, did you run with a larger `-DnondexRuns`, did you run on the entire test class, and did you on the entire test module? Please reply via email or Campuswire to tell us where your logs are.

**Comment by darko-marinov** [comment]
Thanks for your email.

**Pull request merged**
