### PR TITLE
update tests status in apache/dubbo

### PR DESCRIPTION
**Pull request by ljmcr**
Update blank tests status in apache/dubbo
Using tool "auto-check-moved-or-rename"

### CODE REVIEW

**Comment by darko-marinov** [comment]
What script did you use to find these results?

**Comment by ljmcr** [comment]
> What script did you use to find these results?

I find those commits by manually checking

**Comment by darko-marinov** [comment]
Please see my email. Can you find in *all* projects that start with your letter whether tests are still there or have been `Deleted` or `MovedOrRenamed`?

**Comment by darko-marinov** [comment]
How does the tool you used relate to #1559 ?

**Comment by darko-marinov** [comment]
These changes are rather big. Maybe consider splitting into several PRs. Could you show the output of `git show --name-status SHA | grep FILE.java` for each case?

**Comment by ljmcr** [comment]
> These changes are rather big. Maybe consider splitting into several PRs. Could you show the output of `git show --name-status SHA | grep FILE.java` for each case?

The results I run the command for each testfile based on the commit find by the tool are saved in /home/li261/dubbo/git_show_diff_output.txt 
on my vm: 
fa24-cs527-053.cs.illinois.edu
The result of running the script is saved in: /home/li261/dubbo/output.txt
Do you prefer me to split the PR based on test file or different commits?

**Comment by darko-marinov** [comment]
I've just checked the log (during the exam :).

**Pull request merged**
