### PR TITLE
Update status of gr-data.csv

### PR DESCRIPTION
**Pull request by Suraj-Vashista-BK**
**Repo:** https://github.com/kwahome/sopa-api

**Tests:**
1. io.github.kwahome.sopa.HelperUtilsTests.mapToObjectArrayTest
2. io.github.kwahome.sopa.JSONRendererTests.loggingAtDebugTest
3. io.github.kwahome.sopa.JSONRendererTests.loggingAtErrorTest
4. io.github.kwahome.sopa.JSONRendererTests.loggingAtInfoTest
5. io.github.kwahome.sopa.JSONRendererTests.loggingAtTraceTest
6. io.github.kwahome.sopa.JSONRendererTests.loggingAtWarnTest
7. io.github.kwahome.sopa.StructLoggerConfigTests.contextSupplierTest

**PR:**
1. https://github.com/kwahome/sopa-api/pull/9
2. https://github.com/kwahome/sopa-api/pull/10
3. https://github.com/kwahome/sopa-api/pull/11

Status has been updated to **Opened**.

### CODE REVIEW

**Comment by zzjas** [comment]
Ok to merge @darko-marinov

**Comment by darko-marinov** [comment]
In your changed lines, please replace the last `,` with `;`. You can consider changing the checker to check that lines don't have extra cells.

**Comment by Suraj-Vashista-BK** [comment]
> In your changed lines, please replace the last `,` with `;`. You can consider changing the checker to check that lines don't have extra cells.

Sure professor, can I please know the reason for this change? From what I see in gr-data.csv, we need to put 
Status,PR Link,Notes ( in this order ). I do not see a ```;``` here.

**Comment by darko-marinov** [comment]
Comma is used to separate various cells in one row. If you put `a,b,c,d` it looks like a row with four cells not a row with three cells, `a`, `b`, and `c,d`.

**Comment by darko-marinov** [comment]
In this particular case, you can even delete the old note that was about an old version of NonDex. And as I said, you can get extra credit by changing the checker to automatically check for these cases.

**Comment by Suraj-Vashista-BK** [comment]
> Comma is used to separate various cells in one row. If you put `a,b,c,d` it looks like a row with four cells not a row with three cells, `a`, `b`, and `c,d`.

Sorry , but I still did not understand the requirement here.
From my understanding last column 'Notes' is for comments. And The only place I see ```;``` in gr-data.csv was when the comment had an extra line like this
```
https://github.com/spring-projects/spring-boot,daa3d457b71896a758995c264977bdd1414ee4d4,spring-boot-project/spring-boot-actuator-autoconfigure,org.springframework.boot.actuate.autoconfigure.cloudfoundry.reactive.CloudFoundryWebFluxEndpointIntegrationTests.linksToOtherEndpointsWithRestrictedAccess,OD-Vic,InspiredAFix,,https://github.com/spring-projects/spring-boot/issues/38363;https://github.com/spring-projects/spring-boot/commit/c2156d6803bf304ad710509bfbd706ae265fef3d
```
In my case, I have only 1 line of comment under the 'Notes' columns , prior to that I have the PR link and status which is as per the columns mentioned in the header.

So, I am not quite sure where the ```;``` is needed as I don't see any extra column. 
For now, I have removed the comment as per your latest instructions but I apologies for not quite getting what you said.

**Comment by Suraj-Vashista-BK** [comment]
@darko-marinov is this good to go?

**Comment by darko-marinov** [comment]
In the last column for `Notes` please don't use a comma as it make it look like two columns. If I'm not mistaken, you had in `Notes` (not before it) something like `https://github.com...,please use...`. Your changes now look good, so let me accept them.

**Pull request merged**
