### PR TITLE
Update Test data

### PR DESCRIPTION
**Pull request by bmk15897**
I manually checked the File history to find the commits where the methods were renamed. 
But the body of the tests was different than the earlier version and I found that the newer version of the tests is not flaky. So I am not adding new rows in the IDOFT PR Data for the newer version.

### CODE REVIEW

**Review by xieyt2000 — APPROVED** [review]
I agree this should be removed.

**Comment by darko-marinov** [comment]
If the tests are not flaky, put `DeveloperFixed` and find where they were fixed.

**Comment by bmk15897** [comment]
Apologies, I mistook these for ID tests. As they are UD, I do not know whether they are fixed. Shall I add new rows for these tests?

**Comment by darko-marinov** [comment]
Hard to tell when/if the `UD` tests were fixed, because we had a hard time reproducing them. If they were `MovedOrRenamed` or `Deleted`, just document the commit where it was done. It'd be hard to label as `DeveloperFixed`.

**Comment by bmk15897** [comment]
I have already documented the commit where the tests were deleted. Acc. to IDOFT README, if the test body is different for the renamed tests, the original test should be marked as Deleted and new row should be added with the renamed test. So I should be adding new rows in the pr-data.csv for the renamed tests as it is hard to check the flakiness of UD tests?

**Comment by darko-marinov** [comment]
You can check the `OD-Brit` test `org.apache.dubbo.config.AbstractInterfaceConfigTest.checkStubAndMock6`. The others were `UD` and can be marked just as `Deleted`.

**Comment by bmk15897** [comment]
I ran the test org.apache.dubbo.config.AbstractInterfaceConfigTest.checkStubAndMock6 on its current version and it passed.

**Comment by darko-marinov** [comment]
Was it `OD-Brit` in the reported version?

**Comment by bmk15897** [comment]
No, it wasn't. I ran that one too and it passed.

**Pull request merged**
