### PR TITLE
Added new tests

### PR DESCRIPTION
**Pull request by RugvedB**
Added newly detected tests for https://github.com/authorjapps/zerocode. I ran each test individually to ensure that the test is flaky. The log files are available under the new-tests folder on my VM.

### CODE REVIEW

**Comment by zzjas** [comment]
`grep Across -A2 zerocode* | grep org` only shows 7 tests.

**Comment by RugvedB** [comment]
@zzjas I checked the tests again and I realized that these 2 tests were failing in clean run. I have removed it and updated the PR. In total, there are only 7 flaky tests. Sorry for the inconvenience.

**Comment by darko-marinov** [comment]
Did you run each test individually to confirm that it deterministically pass/fail for various seeds? Please keep the logs for each test.

**Comment by RugvedB** [comment]
Yes I ran the tests individually to confirm that the tests are flaky. The logs are available under the folder new-tests on VM

**Comment by darko-marinov** [comment]
@zzjas please inspect the logs

**Comment by zzjas** [comment]
Ok to merge @darko-marinov

**Pull request merged**
