### PR TITLE
Start.xenit.eu test not reproducible

### PR DESCRIPTION
**Pull request by hofi1**
eu.xenit.alfred.initializr.generator.docker.compose.DockerComposeYmlWriterDelegateTest.testService not reproducible
Logs can be found on the VM (simonh5)

### CODE REVIEW

**Comment by darko-marinov** [comment]
Please split the `gr-data.csv` change into another PR and tag Kaiyao to review.

**Comment by hofi1** [comment]
@kaiyaok2 request review

**Comment by kaiyaok2** [comment]
> @kaiyaok2 request review

Thanks for letting me know! This test was not reported by me, but I'll take a look.

**Comment by kaiyaok2** [comment]
@hofi1 Neither could I reproduce test failures after trying 100 NonDex runs with some random seeds. I'm building with Mac M1 under Java 11 with NonDex 2.1.1.

**Comment by darko-marinov** [comment]
Thanks for confirming. Is the other test is this repo `ID` (or may have been `NOD`)?

**Comment by kaiyaok2** [comment]
> Thanks for confirming. Is the other test is this repo `ID` (or may have been `NOD`)?

The other test seems to be truly `ID` (not `NOD` or `ID-HtF`)

**Comment by hofi1** [comment]
there is a pending PR for the other test (currently in review by zijie)
https://github.com/hofi1/start.xenit.eu/pull/1

**Comment by Ellen99** [comment]
Hey, please take a look at the following [log file](https://github.com/TestingResearchIllinois/idoft/files/13211824/nondex.log) 
Command I run `./gradlew start.xenit.eu:nondexTest --tests=DockerComposeYmlWriterDelegateTest -i`

**Comment by darko-marinov** [comment]
Thanks for the log. I don't know if the issue is (1) different random generators or (2) running all tests together vs. just one in isolation. Did we try the one test with many seeds?

**Comment by hofi1** [comment]
In the meantime, the repository got archived - so there is nothing more to fix

**Pull request merged**
