### PR TITLE
New flaky tests 3

### PR DESCRIPTION
**Pull request by njain2208**
Have added the log files in the VM in the folder flakyTestLogDrools1.

### CODE REVIEW

**Comment by zzjas** [comment]
Same as https://github.com/TestingResearchIllinois/idoft/pull/1181

**Comment by njain2208** [comment]
I have updated the tests; they are also flaky in the new repo. I have updated the commits and have added the new log files in the VM in the folder flakyTestLogDrools1.
The `mvn test` log files have names ending with mvn.

**Comment by zzjas** [comment]
I didn't find logs for these three tests. Could you add logs to them in a new directory?
```
org.drools.model.codegen.execmodel.AccumulateTest.testAccumulateWithIndirectArgument
org.drools.model.codegen.execmodel.AccumulateTest.testNestedAccumulates
org.drools.model.codegen.execmodel.AccumulateTest.testTwoAccumulatesOnPatternWithVarBinding
```

**Comment by njain2208** [comment]
I have added the log for these tests in the flakyTestAccumulateTestLog folder in the VM.

**Comment by zzjas** [comment]
The logs for these two tests don't have failures:
```
org.drools.model.codegen.execmodel.AccumulateTest.testNestedAccumulates
org.drools.model.codegen.execmodel.AccumulateTest.testTwoAccumulatesOnPatternWithVarBinding
```

**Comment by njain2208** [comment]
Some of the tests passed with -DnondexRuns=3 but failed with  -DnondexRuns=5. I have added the log for these tests in the flakyTestAccumulateTestLog folder in the VM.

**Pull request closed without merging**
