### PR TITLE
Adding two new apache/myfaces-tobago tests

### PR DESCRIPTION
**Pull request by mihirgune**

### CODE REVIEW

**Comment by darko-marinov** [comment]
Do you have exact repro steps? Please see #1491 for an example.

Are you running some script to find these tests? Did you try all the modules in this project?

**Comment by mihirgune** [comment]
Hi, I found this repository when I was looking for Apache projects that start with 'm'. I ran nondex with 50 runs on it and found these tests. I managed to run it on the entire repo by using the `-fn` flag in my Maven command, dumping all of the Nondex output in a .log file, and then grepping for `nondex:nondex` on the file.

Sure, I can build a Docker script that runs nondex on this repo to check if there are any flaky tests in it. Should I make it generic, so it is reusable to others as well?

**Comment by darko-marinov** [comment]
If you make your `Dockerfile` generic so it can be used by others **first**, then you can get extra "points". Otherwise, just provide a specific `Dockerfile` for your case.

**Comment by mihirgune** [comment]
Hi!

Please find my Dockerfile and entrypoint.sh scripts attached. (Emailing
because GitHub does not support adding *.sh files as attachments in
comments.)

I have built a Dockerfile to serve as the base for running NonDex tests.
Initially, I considered cloning repositories and running NonDex directly in
the Dockerfile. However, this approach would generate numerous Docker
images for each repository. To avoid this, I’ve separated the process into
a bash script that clones the repository and executes NonDex. This
end-to-end script includes various configurations to customize the NonDex
run and scrapes the NonDex log file to identify flaky tests.

I have built a Dockerfile which will be the base upon which the nondex
tests will run. I initially planned to clone the repository and run nondex
within the Dockerfile, but felt that doing so for each repository would
create a large number of varying Docker images. Hence, I have cloned the
repository and executed nondex within a separate bash script. This
end-to-end script provides a number of configurations to customize your
Nondex run, and also scrapes the nondex log file to get a final set of
flaky tests.

Steps to follow:
1. Build the Dockerfile using the following command ```docker build
--build-arg JAVA_VERSION=17 -t nondex-runner .```. -> The java_version is
configurable.
2. Run the Docker container with arguments for the entrypoint.sh script
- $REPO_URL (compulsory)
- $MODULE - the module upon which nondex is to be executed
- $TESTS - if nondex needs to be executed on specific tests
- $NONDEX_RUNS - the number of runs that nondex needs to be executed for
- $RUN_NONDEX_WITH_FN - if nondex is to be executed using the -fn flag

The script will end with the following logs, indicating the path of the
nondex log file, and the nondex_failures file.
```
Processing NonDex log file: /app/nondex_logs/nondex-20241118-064556.log
Failing tests have been written to:
/app/nondex_logs/nondex-failures-20241118-064556.txt
```

I've tested this script with the various configurations and commands that
are part of the script, and I'd like to share the results I got after
running this script on the following repos to find new flaky tests

Repo - https://github.com/apache/myfaces-tobago
Command - ```docker run   -e REPO_URL=
https://github.com/apache/myfaces-tobago.git   -e RUN_NONDEX_WITH_FN=true
-v $(pwd)/nondex_logs:/app/nondex_logs   nondex-runner```
Detected Flaky Tests output (manually verified) -
[INFO]
org.apache.myfaces.tobago.webapp.TobagoResponseWriterUnitTest#testPassthrough
[INFO]
org.apache.myfaces.tobago.webapp.TobagoResponseWriterUnitTest#testPassthroughInRenderer

Repo - https://github.com/abel533/Mapper
Command - ```docker run -e REPO_URL=https://github.com/abel533/Mapper.git
-v $(pwd)/nondex_logs:/app/nondex_logs nondex-runner```
Detected Flaky tests output (manually verified) -
[INFO] tk.mybatis.solon.test.service.TkMapperServiceTest#all
[INFO] tk.mybatis.solon.test.service.TkMapperServiceTest#exampleQuery
[INFO] tk.mybatis.solon.test.service.TkMapperServiceTest#logicDelInsert
[INFO] tk.mybatis.solon.test.service.TkMapperServiceTest#rawMybatisQuery

Please let me know if you'd like to see any more enhancements, or if any
further information is required from my side to run these scripts.

PS: Sorry for the dodgy formatting, I had to use Gmail, because Github and
Outlook were not picking up my shell script.

Thanks,
Mihir

> Message ID: ***@***.***
> com>
>

# Use a Maven image with a configurable Java version
ARG JAVA_VERSION=17
FROM maven:3.9.4-eclipse-temurin-${JAVA_VERSION}

WORKDIR /app

RUN apt-get update && apt-get install -y git && apt-get clean

# Thanks - https://github.com/TestingResearchIllinois/idoft/pull/1491
ENV MAVEN_OPTS="-XX:+TieredCompilation -XX:TieredStopAtLevel=1"

COPY entrypoint.sh /entrypoint.sh

RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]

**Comment by mihirgune** [comment]
Please ignore the comment here and refer to the email I have sent over to marinov@illinois.edu. Somehow, after I replied to the comment over email, Github decided to paste the Dockerfile in plain-text in the comment here.

**Comment by darko-marinov** [comment]
> Github decided to paste the Dockerfile in plain-text in the comment here.

Please put your work (script, `Dockerfile`) in Markdown in a comment here. The email attachments didn't see to propagate. Even better, for the script, you can open a new PR on IDoFT similar to other `auto-*` directories and scripts.

**Comment by mihirgune** [comment]
Okay, thanks. I'll go ahead and create a PR on IDoFT.
Also, updating the status of these tests to Accepted, as my fix has been merged.

**Comment by darko-marinov** [comment]
Accepting this PR, looking forward to the script.

**Pull request merged**
