### PR TITLE
Changed status of apache/ignite-3 to MovedToGradle

### PR DESCRIPTION
**Pull request by deekshacheruku**
**Previous Pull Request:** https://github.com/TestingResearchIllinois/idoft/pull/952

I accidentally forced pushed my repo to update it to the latest commit of Idoft which closed my previous PR. Sorry for the inconvenience.

**Comments Till Now:**

**Asked to find the exact commit where it has moved to Gradle. Below are the insights. I have used the commit of Gradle Initiation as the SHA.**

*Maven Removal:*
Jira Ticket: [https://issues.apache.org/jira/browse/IGNITE-17487](https://urldefense.com/v3/__https://issues.apache.org/jira/browse/IGNITE-17487__;!!DZ3fjg!8KrpyOUkWTXzZRoF3C2iYLR8LrxXfR1OsXHvt3fYrFnUNCzWvPX0ovzq9q4k11fSLYtQuk1b2cuJfcmUExMUsW3iru0p$)
Pull request: [https://github.com/apache/ignite-3/pull/1421](https://urldefense.com/v3/__https://github.com/apache/ignite-3/pull/1421__;!!DZ3fjg!8KrpyOUkWTXzZRoF3C2iYLR8LrxXfR1OsXHvt3fYrFnUNCzWvPX0ovzq9q4k11fSLYtQuk1b2cuJfcmUExMUsRYn3tEL$)
Commit: [https://github.com/apache/ignite-3/commit/44efe1e23ef8a14713fd8157e2239114903ede7d](https://urldefense.com/v3/__https://github.com/apache/ignite-3/commit/44efe1e23ef8a14713fd8157e2239114903ede7d__;!!DZ3fjg!8KrpyOUkWTXzZRoF3C2iYLR8LrxXfR1OsXHvt3fYrFnUNCzWvPX0ovzq9q4k11fSLYtQuk1b2cuJfcmUExMUscrxK46-$)

*Gradle Initiation:*
Jira Ticket: [https://issues.apache.org/jira/browse/IGNITE-17485](https://urldefense.com/v3/__https://issues.apache.org/jira/browse/IGNITE-17485__;!!DZ3fjg!8KrpyOUkWTXzZRoF3C2iYLR8LrxXfR1OsXHvt3fYrFnUNCzWvPX0ovzq9q4k11fSLYtQuk1b2cuJfcmUExMUseoBVCWc$)
Pull Request: [https://github.com/apache/ignite-3/pull/1032](https://urldefense.com/v3/__https://github.com/apache/ignite-3/pull/1032__;!!DZ3fjg!8KrpyOUkWTXzZRoF3C2iYLR8LrxXfR1OsXHvt3fYrFnUNCzWvPX0ovzq9q4k11fSLYtQuk1b2cuJfcmUExMUsbuTaaen$)
Commit: [https://github.com/apache/ignite-3/commit/2dc567bcaaed4a2999e2bf6c361a72e571a59cd4](https://urldefense.com/v3/__https://github.com/apache/ignite-3/commit/2dc567bcaaed4a2999e2bf6c361a72e571a59cd4__;!!DZ3fjg!8KrpyOUkWTXzZRoF3C2iYLR8LrxXfR1OsXHvt3fYrFnUNCzWvPX0ovzq9q4k11fSLYtQuk1b2cuJfcmUExMUsbkt3UjW$)

**Asked to find if the tests are flaky before and after the gradle shift**

Tests Flaky?

All the logs are in my VM. Id: deeksha5@fa23-cs527-117

*Before Moving To Gradle:*

- I checked the SHA detected (a1aa7fd4e2398c72827777ec5417d67915ff4da3). I couldn't build the project as the artifacts werent available. The commit was made on 10th Jun 2022.
Path: /home/deeksha5/ignite-3/mvn-install-1699924529.log
- I also tried the SHA (4a1baf49e666653e4e2a5e32c292629686259b3b) just before the removal of maven project (pom.xmls) which also yielded same result. The commit was made on Jan 12 2023.
Path: /home/deeksha5/ignite-3/mvn-install-1699924975.log 

*After Moving To Gradle:*

I have trouble running Nondex on the project. CampusWire Post: https://campuswire.com/c/G7A0E96FD/feed/619

### CODE REVIEW

**Comment by deekshacheruku** [comment]
I can create another PR to update the tests in gr-data.csv once I resolve the nondex issue in the project. Will that be fine @darko-marinov @zzjas

**Comment by darko-marinov** [comment]
If you're already closing and reopening PRs, please update this PR to have only one commit.

Also check if these tests were flaky right after being moved to Gradle.

**Comment by deekshacheruku** [comment]
@darko-marinov I have added the tests that are still flaky in ```gr-data.csv```. All the logs can be found in my VM under the path
```/home/deeksha5/ignite-3/flaky-test```. Let me know if anything else is left to investigate. Thanks!

**Comment by darko-marinov** [comment]
For https://github.com/apache/ignite-3/commit/2dc567bcaaed4a2999e2bf6c361a72e571a59cd4 I've noticed "This commit does not belong to any branch on this repository, and may belong to a fork outside of the repository." -- can you please investigate. How did you find that commit in the first place?

Also, for tests that appear not flaky in Gradle, for how many seeds did you run? If tests are fast, can you run for more seeds? For tests that were seemingly fixed, can you find the exact commit where they were fixed (especially if you never before used `git bisect`)?

**Comment by deekshacheruku** [comment]
https://github.com/apache/ignite-3/commit/2dc567bcaaed4a2999e2bf6c361a72e571a59cd4 I found this commit through the JIRA ticket. They were nested commits, I had to go back and check all the commits to find the very inital commits.

**Comment by darko-marinov** [comment]
That commit may have been in a PR and got another SHA when it was merged into the repo. Please find the corresponding commit in the repo itself.

**Comment by deekshacheruku** [comment]
Merged Commit: https://github.com/apache/ignite-3/commit/c91f39cd80dfd143e5ac848486366ad6ed124ce5. I am going to update the PR.

**Comment by darko-marinov** [comment]
Okay, I'll check this likely after my trip, as the change is big. Please also double check all other tests that appear not flaky in Gradle. Learn about `git bisect` if you've not used it before.

**Comment by deekshacheruku** [comment]
I have my progress report 4 due this week. I can make two prs, One for MoveToGradle and the other for adding new tests. So that I could include this PR in the report. Will that work professor?

**Comment by deekshacheruku** [comment]
**Progress Till 16th Nov 2023 1: 40 am**

All the logs can be found in my VM mentioned above in the path ```/home/deeksha5/ignite-3/flaky-test```

For nondexRuns = 50, I have appened the 50 to the name for identification:

ConfigurationAsmGeneratorTest  => Entire test file is deleted  => Should find the SHA 
ConfigurationRegistryTest  => ```testComplicatedPolymorphicConfig``` reported Flaky by Nondex  => Added to gr-data.csv
ConfigurationAnyListenerTest  =>  All the previous 13 tests have been detected Flaky by Nondex  => Added to gr-data.csv
ConfigurationListenerTest  => In 35 tests, 32 tests have been detected Flaky by Nondex  => Will add to gr-data.csv
                                           => ```testNotifyStorageRevisionListener is deleted```  => Should find the SHA
                                           => ```testNotifyStorageRevisionListenerForCurrentConfig is deleted```  => Should find the SHA
                                           => ```testNotifyStorageRevisionListenerWithError``` is deleted  => Should find the SHA
ConfigurationUtilTest  => All the previous 1 test have been detected Flaky by Nondex => Added to gr-data.csv
                                    => removed extra line which does have test method (should do)
AbstractFreeListTest  => All the previous 1 test have been detected Flaky by Nondex  => Will add to gr-data.csv
IgniteCliRunnerTest  => All the previous 2 tests  =>
SchemaConfigurationConverterTest  => All the previous 5 tests  =>
TableValidatorImplTest  => All the previous 1 test  =>
MockedStructuresTest  => All the previous 9 tests  =>
StopCalciteModuleTest  => All the previous 1 test  =>
TestSortedIndexMvStorageTest  => All the previous 6 tests  => 
DataStorageManagerTest  => All the previous 6 tests  =>
PersistentPageMemoryMvPartitionStorageTest  => All the previous 2 tests  =>
VolatilePageMemoryMvPartitionStorageTest  => All the previous 2 tests  =>
IgniteToStringBuilderSelfTest  => All the previous 5 tests  => 4 already added, should check ```testToStringCheckConcurrentModificationExceptionFromMap```

**Comment by darko-marinov** [comment]
The change is too big for me to review and approve. Please split into smaller PRs that are easier to approve.

**Comment by deekshacheruku** [comment]
Sure professor, will split into multiple PRs.

**Comment by zzjas** [comment]
Were all the changes here included in other PRs? If so, I think this PR can be closed. Thanks.

**Comment by darko-marinov** [comment]
If you want to keep this PR, please resolve conflicts.

**Pull request closed without merging**
