### PR TITLE
Update pr-data.csv

### PR DESCRIPTION
**Pull request by same8891**
The test was renamed from core/org.apache.druid.java.util.emitter.core.ParametrizedUriEmitterTest.testEmitterWithParametrizedUriExtractor to processing .org.apache.druid.java.util.emitter.core.ParametrizedUriEmitterTest.testEmitterWithParametrizedUriExtractor. The renamed commit is 08b5951cc53c4fe474a129500c62a6adad78337f
.

### CODE REVIEW

**Comment by darko-marinov** [comment]
The test order seems to be wrong: https://github.com/TestingResearchIllinois/idoft/pull/785/checks

**Comment by same8891** [comment]
Just fix it.

**Comment by darko-marinov** [comment]
Is the test ID in `08b5951cc53c4fe474a129500c62a6adad78337f`? Is it ID in the latest commit?

**Comment by same8891** [comment]
Do you mean the after rename? The rename test is still in the latest version. 08b5951cc53c4fe474a129500c62a6adad78337f is the commit that the old test was moved

**Comment by same8891** [comment]
圖片

**Comment by darko-marinov** [comment]
I meant after rename, sorry if it was not precise. Please don't upload pictures where you can copy text or send links.

**Comment by same8891** [comment]
Sorry for uploading picture.

**Comment by darko-marinov** [comment]
Don't worry about the picture now. Is the test ID in the commit that you report? Is it ID in the latest project commit?

**Comment by darko-marinov** [comment]
Any progress on check if/when the test was `ID`?

**Comment by same8891** [comment]
The test is moved in the commit that I reported. And it is now still in the latest commit.

**Comment by darko-marinov** [comment]
The fact that the test moved doesn't necessarily mean that it remained `ID` or became `ID` or stopped being `ID`. Please run NonDex on those commits to check what the test status was.

**Comment by same8891** [comment]
I have used non-dex to run the test in the latest commit. It still failed when using non-dex.

**Comment by darko-marinov** [comment]
Sorry I don't know what "latest commit" you're referring to. You're trying to add this line:

```
https://github.com/apache/druid,08b5951cc53c4fe474a129500c62a6adad78337f,processing,org.apache.druid.java.util.emitter.core.ParametrizedUriEmitterTest.testEmitterWithParametrizedUriExtractor,ID,,,
```

That line claims that the test `...testEmitter...` is `ID` in commit `08b5951cc53c4fe474a129500c62a6adad78337f`. Did you run that test in that commit?

I understand that a test that was `ID` before the commit and is still flaky now is also likely to be flaky in the commit, but I'd like to see if you ran it. Alternatively, if you didn't run in that specific commit, you can change to the commit in which you did run (maybe that "latest commit" that you're mentioning).

**Comment by same8891** [comment]
I just change the SHA Detected to the version that I have run.

**Comment by darko-marinov** [comment]
Great. In retrospect, the solution was very easy. We/I should have thought of it earlier. :)

**Pull request merged**
