### PR TITLE
update dev-fixed for wildfly

### PR DESCRIPTION
**Pull request by everbrightw**
Update DeveloperFixed status for wildfly

before this fix, tests are failing, logs at:
`/home/yusenw2/wildfly/test_fail_before_pr_2.log`

after this fix, tests are passing, logs at:
`/home/yusenw2/wildfly/test_success_after_pr_2.log`

### CODE REVIEW

**Comment by darko-marinov** [comment]
The code change doesn't look that related. Did you run NonDex for 10 or 100 seeds after the change?

**Comment by everbrightw** [comment]
I did not dive deep why this fix works. I looked into the tests and they look fine to me. They eventually called an external library [wildfly-glow.](https://github.com/wildfly/wildfly-glow) I think this has to do with how their internal logic work or XML config for setup? 
I run with DnondexRuns=10, I can try 100 and update here.

**Comment by everbrightw** [comment]
tests passed with running NonDex for 100 seeds after the change
log: `/home/yusenw2/wildfly/run_100_after_pr.log`

**Comment by everbrightw** [comment]
finding the fix credit to this PR https://github.com/TestingResearchIllinois/idoft/pull/1350 on IDOFT
I was only testing and verifying for tests assigned to me :)

**Comment by darko-marinov** [comment]
Thanks for these. Please feel free to completely focus on `forEach`, no need to add more of the existing tests. If `forEach` is supported well, it could find many new tests.

**Pull request merged**
