### PR TITLE
Added Opened status for Sentinel PR

### PR DESCRIPTION
**Pull request by hermya**
Adding Opened status for time zone dependent test, with PR at: https://github.com/alibaba/Sentinel/pull/3459

### CODE REVIEW

**Comment by darko-marinov** [comment]
Please change the checker with the new category

**Comment by darko-marinov** [comment]
Please rebase your changes on the latest `main` now that I accepted #1356

**Comment by darko-marinov** [comment]
Not sure if you're working on `The file is not properly ordered`.

**Comment by darko-marinov** [comment]
Can you squash 8 commits into 1? You're just adding one new line, so no need for 8 commits to ad one line.

**Comment by darko-marinov** [comment]
This PR currently has some unnecessary changes in `pr-data.csv` (and two commits instead of one).

**Comment by hermya** [comment]
Apologies for taking so many tries to reduce the changes to one commit

**Pull request merged**
