### PR TITLE
13 Discovered Flaky Tests in Wildfly preview/dist module

### PR DESCRIPTION
**Pull request by alexbadia1**
### 13 New Flaky Tests discovered in the latest version of Wildfly:

- org.wildfly.dist.subsystem.xml.StandardConfigsXMLValidationUnitTestCase#testHostSecondary
- org.wildfly.dist.subsystem.xml.StandardConfigsXMLValidationUnitTestCase#testStandalone
- org.wildfly.dist.subsystem.xml.StandardConfigsXMLValidationUnitTestCase#testHost
- org.wildfly.dist.subsystem.xml.StandardConfigsXMLValidationUnitTestCase#testStandaloneHA
- org.wildfly.dist.subsystem.xml.StandardConfigsXMLValidationUnitTestCase#testStandaloneJTS
- org.wildfly.dist.subsystem.xml.StandardConfigsXMLValidationUnitTestCase#testStandaloneRTS
- org.wildfly.dist.subsystem.xml.StandardConfigsXMLValidationUnitTestCase#testStandaloneXTS
- org.wildfly.dist.subsystem.xml.StandardConfigsXMLValidationUnitTestCase#testStandaloneMinimalistic
- org.wildfly.dist.subsystem.xml.StandardConfigsXMLValidationUnitTestCase#testStandaloneActiveMQEmbedded
- org.wildfly.dist.subsystem.xml.StandardConfigsXMLValidationUnitTestCase#testHostPrimary
- org.wildfly.dist.subsystem.xml.StandardConfigsXMLValidationUnitTestCase#testStandaloneFull
- org.wildfly.dist.subsystem.xml.StandardConfigsXMLValidationUnitTestCase#testDomain
- org.wildfly.dist.subsystem.xml.StandardConfigsXMLValidationUnitTestCase#testStandaloneGenericJMS

We are working on a fix as we speak, a tennative PR incoming soon!

You migh also wonder why not the other testcase in the same module: XSDValidationUnitTestCase? We tested NonDex alot on it and couldn't break it (also included in CampusWire Logs)

### Logs (CampusWire)
- https://campuswire.com/c/G7A0E96FD/feed/715

### CODE REVIEW

**Comment by zzjas** [comment]
I think you already have a real PR for these tests? Could you update them to be `Opened`?

**Comment by alexbadia1** [comment]
> I think you already have a real PR for these tests? Could you update them to be `Opened`?

Status changed, with link to PR (https://github.com/wildfly/wildfly/pull/17472). Someone is already looking at it, hopefully it get's merged soon!

Also, I will change the status of the other tests (in the Wildfly PR not included in this idoft PR) in a separate PR to idoft

**Comment by zzjas** [comment]
Great work! Ok to merge @darko-marinov

**Comment by zzjas** [comment]
Actually, can you squash commits to one?

**Comment by zzjas** [comment]
Please squash commits here as well. Thanks.

**Comment by alexbadia1** [comment]
> Please squash commits here as well. Thanks.

Done

**Comment by zzjas** [comment]
Ok to merge @darko-marinov

**Pull request merged**
