### PR TITLE
discover new ID flaky tests and fix them

### PR DESCRIPTION
**Pull request by bjchris32**
Discovered new ID flaky tests and fixed them with a opened PR.

The error log for `com.google.cloud.spring.data.spanner.core.convert.ConverterAwareMappingSpannerEntityWriterTests#writeJsonArrayTest` with `nondexSeed=1223286`:
```
[ERROR]   ConverterAwareMappingSpannerEntityWriterTests.writeJsonArrayTest:384
Argument(s) are different! Wanted:
valueBinder.toJsonArray(
    [{"p1":"some value","p2":"some other value"}, {"p1":"some value","p2":"some other value"}]
);
-> at com.google.cloud.spring.data.spanner.core.convert.ConverterAwareMappingSpannerEntityWriterTests.writeJsonArrayTest(ConverterAwareMappingSpannerEntityWriterTests.java:384)
Actual invocations have different arguments:
valueBinder.toJsonArray(
    [{"p2":"some other value","p1":"some value"}, {"p2":"some other value","p1":"some value"}]
);
-> at com.google.cloud.spring.data.spanner.core.convert.ConverterAwareMappingSpannerEntityWriter.attemptSetIterableValue(ConverterAwareMappingSpannerEntityWriter.java:329)
valueBinder.to(
    "id1"
);
```

The error log for `com.google.cloud.spring.data.spanner.core.convert.ConverterAwareMappingSpannerEntityWriterTests#writeJsonTest` with `nondexSeed=974622`:
```
[ERROR] com.google.cloud.spring.data.spanner.core.convert.ConverterAwareMappingSpannerEntityWriterTests.writeJsonTest -- Time elapsed: 1.132 s <<< FAILURE!
Argument(s) are different! Wanted:
valueBinder.to(
    {"p1":"some value","p2":"some oth...
);
-> at com.google.cloud.spring.data.spanner.core.convert.ConverterAwareMappingSpannerEntityWriterTests.writeJsonTest(ConverterAwareMappingSpannerEntityWriterTests.java:347)
Actual invocations have different arguments:
valueBinder.to(
    "id1"
);
-> at com.google.cloud.spring.data.spanner.core.convert.ConverterAwareMappingSpannerEntityWriter.attemptSetSingleItemValue(ConverterAwareMappingSpannerEntityWriter.java:366)
valueBinder.to(
    {"p2":"some other value","p1":"so...
);
```

The opened real PR(https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/2341) fixed the following test cases:
* com.google.cloud.spring.data.spanner.core.convert.ConverterAwareMappingSpannerEntityWriterTests#writeJsonArrayTest
* com.google.cloud.spring.data.spanner.core.convert.ConverterAwareMappingSpannerEntityWriterTests#writeJsonTest

I've updated the status of these two records.

### CODE REVIEW

**Comment by darko-marinov** [comment]
How did you check if these tests are `ID` or not? NonDex reports flaky tests that it sees both pass and fail. It doesn't claim that the root cause is shuffling. Did you try to run the test individually? Did you run them many times for the same seed(s)? Do they deterministically pass or fail?

**Comment by bjchris32** [comment]
> How did you check if these tests are `ID` or not? NonDex reports flaky tests that it sees both pass and fail. It doesn't claim that the root cause is shuffling. Did you try to run the test individually? Did you run them many times for the same seed(s)? Do they deterministically pass or fail?

Hi @darko-marinov ,

I'll rerun them individually and with same seeds to check if they are really `ID` test.
Thank you for your comments!

**Comment by bjchris32** [comment]
I only kept two newly found PR which was identified as ID after multiple runs with NonDex.
I've temporarily removed other newly found PR in the original PR, which still need some discussion in campuswire post: https://campuswire.com/c/G7A0E96FD/feed/635

**Comment by darko-marinov** [comment]
Accepting now. Fine to add more tests later, with some more logs.

**Pull request merged**
